### ISSUE TITLE
"Domains Being Blocked" number wrapped in unnecessary tag

### ISSUE THREAD

**Issue by FoxBJK** [pi-hole/AdminLTE#10]
Hi,

This problem has to do with something inside of the index.php file, specifically line 170. That particular number (domains being blocked) is wrapped inside a <sup> tag, and unless you're planning to put something below it, it's causing a problem that makes this box inconsistent with the others. Below is a screenshot:

![screenshot_2016-01-11_17-39-50](https://cloud.githubusercontent.com/assets/2916288/12250134/60fdfffe-b88a-11e5-9da8-d81d7f92e086.png)

Never made changes in git before, so I'm afraid to download and upload to fix this on my own for fear of messing other things up, but if you remove this one tag it'll clean up the page and make everything much cleaner.

Thanks!

**Comment by jacobsalmela** [comment]
I originally did this when the list of domains was over a million.  The number was outside the limits of the box.  I don't really know how to adjust the size dynamically based on how long the number is so it stays within the box.

**Comment by FoxBJK** [comment]
There's a size unit you can use for the font called "Viewport units" if you want to try that:
http://caniuse.com/#feat=viewport-units

You can also consider using "word-wrap: break-word;" in place of "white-space: nowrap;" to force the number to break apart if it gets long enough.

I'll play around with my copy of the web UI and see if I can come up with a good fix for the font that'll scale it better.

**Comment by jacobsalmela** [comment]
Let me know if you come up with something.  I'm much better at bash then Web development, but I'll also take a look.

**Comment by DonLexos** [comment]
Since that big list is removed now I believe only thing that needs to be removed is this tag:
`<sup style="font-size: 30px">87,180</sup>` around the number

If you keep the number in the `h3` tag it is displayed exactly as the other ones.

**Comment by FoxBJK** [comment]
Yes, this will work. The only problem is that when the number grows big enough, it breaks out of the bounds of (what should be) its containing box. I haven't had a chance to look into this for a fix, but it's on my radar for "soon"

**Comment by DonLexos** [comment]
Too big would be in the x.xxx.xxx range, that might happen but that could also be for the other fields in a really huge setup. I reckon removing the tag (for) now fixes the issue.

**Comment by FoxBJK** [comment]
So far everything I've found requires scripting, so I'm working on a fix that implements this:
http://jquery-textfill.github.io/

Going to have to add jquery and make a few changes to the HTML code. I'll make sure the look stays the same.

**Comment by Mcat12** [comment]
We already have jQuery, so it should be easy to install.

**Comment by FoxBJK** [comment]
I saw that 1.5.2 was already in the dev branch. Guessing you guys are planning to use it for other stuff?

This text thing is going to take a bit though. I'm also seeing that on the smallest of mobile screens, the problem also exists.

**Comment by Mcat12** [comment]
jQuery should be in all branches, as it's needed to use some other libraries that make up the admin page. We have a lot of stuff in the works currently.

**Comment by FoxBJK** [comment]
Oh, stupid me, just found where the script tags are. Was expecting everything to be in the header

**Comment by Mcat12** [comment]
Just remember to branch off of devel. Look in [here](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md) for contributing tips.

**Comment by Mcat12** [comment]
Any update on this?

**Comment by FoxBJK** [comment]
I'm not really able to replicate this anymore. The web ui has changed since this was posted, and I'm able to use up to 9 digit domain block lists without issue.

If someone gets to a billion blocked domains then maybe we can reopen this
