### ISSUE TITLE
Web Interface shows update reminder even after updating and being up to date

### ISSUE THREAD

**Issue by basseur** [pi-hole/AdminLTE#1008]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated*. (**unknown!**)
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

The Pi-hole Admin Console showed an update available for Web Interface Version v4.3. After running `pihole -up`, I expected the update reminder to be gone and the updated version of the Web Interface to be shown.

**Actual behaviour:**

After running `pihole -up` and rebooting the Raspberry Pi, it still says _Web Interface Version v4.3 (Update available!)_. 
![grafik](https://user-images.githubusercontent.com/32487587/65386587-fbdfc300-dd3d-11e9-939a-cadf3e95bec4.png)

Running `pihole version`, however, shows that the update worked.
![grafik](https://user-images.githubusercontent.com/32487587/65386564-bf13cc00-dd3d-11e9-91d8-f8636997e4a4.png)

**Steps to reproduce:**

`I don't know how to reproduce this as I only have this one Raspberry Pi. `

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`i1sckb6ros`

**Troubleshooting undertaken, and/or other relevant information:**

`pihole -up`
`sudo shutdown -r 0`
updated all packages of the raspbian (`sudo apt update`, `sudo apt upgrade` with accepting updates).

**Comment by PromoFaux** [comment]
@basseur , I see you have closed this issue. Did it resolve itself?

**Comment by jay3ss** [comment]
Just to piggyback on this, I'm having this same issue

**Comment by dschaper** [comment]
Have you cleared the browser cache?

**Comment by dschaper** [comment]
Can you provide us with more information on what exactly you are seeing and what actions you have taken?

**Comment by jay3ss** [comment]
Clearing the cache did it. Thanks for the help. Can't believe that I didn't think of something simple.

**Comment by basseur** [comment]
> @basseur , I see you have closed this issue. Did it resolve itself?

The updated version was shown after a few minutes and I was not sure, if this was due to clearing the cache (Ctrl+Shift+R) at one point (like @jay3ss). Feeling stupid, I closed the issue. 😬

**Comment by PromoFaux** [comment]
Yeah, it would be after doing a refresh of the cache. It also resolves itself after some time!
