### ISSUE TITLE
[Feature Request] Please add support for DHCP options

### ISSUE THREAD

**Issue by jeanbruder** [pi-hole/AdminLTE#1010]
Dear PI-Hole Team,

Please add support for DHCP options in the admin interface. I was using the configuration file of dnsmasq to specify options numbers and values, but dunno now how to manage the options in PI-Hole.

Thx in advance,
Regards,
Jean

**Comment by Mcat12** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net).

Thank you for your understanding.
