### ISSUE TITLE
[Feature Request] multiple domains and servers for conditional routing

### ISSUE THREAD

**Issue by lorodoes** [pi-hole/AdminLTE#1012]
When adding conditional routing it be nice to be able to click a plus sign and add additional servers and domains. For instance I could have multiple domains on a single server that I need to route requests too.

**Comment by Mcat12** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net).

Thank you for your understanding.
