### ISSUE TITLE
Very Old Bootstrap Version. Update to newer Version

### ISSUE THREAD

**Issue by Pazekal90** [pi-hole/AdminLTE#1013]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`9`

---

Link that describes the open vulnerabilities with the Version 3.3.6 that is used at the moment: https://snyk.io/vuln/npm:bootstrap?lh=3.3.6

**Comment by Mcat12** [comment]
Closed by #1022
