### ISSUE TITLE
Very old jQuery and jQueryUI Versions

### ISSUE THREAD

**Issue by Pazekal90** [pi-hole/AdminLTE#1014]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`6`

---
At the moment the following versions are used: 
- jQuery: 2.1.4 https://snyk.io/vuln/npm:jquery?lh=2.1.4
- jQueryUI: 1.11.3 https://snyk.io/vuln/npm:jquery-ui?lh=1.11.3

Dependency management can be very useful at this point. aka Greenkeeper with package.json

**Comment by XhmikosR** [comment]
+1 on updating these and also the other 3rd-party libraries (chart etc). Bootstrap was updated to 3.4.1 in the devel branch, so that's something :)

I'll see if/how I can set up a local development environment on my Windows dev VM and take a stab at updating Bootstrap to v4, but I make no promise :)

**Comment by PromoFaux** [comment]
We're actually starting a move away from the PHP-based dashboard page, and looking to something a bit more modern in react.

See https://github.com/pi-hole/web for more details

**Comment by XhmikosR** [comment]
Oh, I wasn't aware of that. Does it make any sense to submit patches here then? What's the timeframe for the new dashboard?

I don't have any huge patches, just a few [minor things](https://github.com/pi-hole/AdminLTE/pulls/XhmikosR)

**Comment by XhmikosR** [comment]
Oh, nice to see using Bootstrap 4 in the new app :)

We'll release an alpha for v5 without jQuery BTW soon.

**Comment by PromoFaux** [comment]
>What's the timeframe for the new dashboard?

How long is a piece of string? 😏 No ETA as yet, it also depends on the `new/http` branch of `FTL` being merged, and we've got some more plans with `FTL` before the api functionality is merged.

We'll still consider patches to this repo, of course, but we're not expending too much energy in adding new features etc.

**Comment by PromoFaux** [comment]
If you want to play with the new interface, checkout the `development-FTL` branch and make sure you are also running the `new/http` branch of `FTL` by running `pihile checkout ftl new/http` (you can then add `proxy: "http://pi.hole:8080/admin" to your `packages.json` to get live data.

**Comment by XhmikosR** [comment]
@Pazekal90 if you have some time, it might be worth updating some of the other libraries.

Maybe not jQuery itself, but jQuery-UI, moment.js, jquery-confirm, daterangepicker. DataTables could also be worth but it's tricky. The same goes for Chart.js, although I think this might be worth updating.

**Comment by Pazekal90** [comment]
@XhmikosR I will have a look at this in the next two weeks. But first: Have a wonderful christmas time ;)

**Comment by XhmikosR** [comment]
You too :) I have already made a few branches with updates, I just haven't had the time to test them.

https://github.com/pi-hole/AdminLTE/tree/update-chartjs
https://github.com/pi-hole/AdminLTE/tree/update-datatables
https://github.com/pi-hole/AdminLTE/tree/update-jquery

PS. I don't even know where jQuery UI is used TBH

**Comment by XhmikosR** [comment]
I have #1361 which removes the unused jQuery UI, and #1362 which update jQuery to the latest version.

**Comment by XhmikosR** [comment]
Fixed in #1362

**Comment by balazsorban44** [comment]
@PromoFaux I see you mentioned an intent to move to React here: https://github.com/pi-hole/AdminLTE/issues/1014#issuecomment-557905773

But I see the repo has been archived. Has this intent changed since then? I would be happy to help out, maybe even try something like https://nextjs.org/ which is a React framework with lots of (well earned) hype around it.

**Comment by dschaper** [comment]
React has been shelved.

**Comment by balazsorban44** [comment]
I see, thank you! Do contact me, if there will be interest in the future again! 🙂

**Comment by dschaper** [comment]
Sure! I think the most likely approach will be with something like Vue if there is a choice for a framework.
