### ISSUE TITLE
Feature Request: API addition to update Gravity?

### ISSUE THREAD

**Issue by nicedevil007** [pi-hole/AdminLTE#1018]
Hey there,

would it be possible to give us the ability to update gravity over the API?
I'm using node-red for my homeautomation and got a tab there where I can turn on or off the Piholes I'm using. This is a simple way for my girlfriend to do this if I'm not at home and Pihole is anything blocking that shouldn't be blocked.

While I'm able to do so much with your given API with pihole on node-red, I'm missing the possibility to just update my blocklists.

Thank you all good Devs in advance.

**Comment by Mcat12** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net).

Thank you for your understanding.
