### ISSUE TITLE
"Time FTL started" does not honour timezone

### ISSUE THREAD

**Issue by eku** [pi-hole/AdminLTE#1025]
"Time FTL started" does not honour timezone

This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

The docker images runs with timezone 'Europe/Berlin' via TZ environment variable. 
The settings->system page does not honour the timezone for "Time FTL started". Time is always UTC.

## Expected Behavior

Time is displayed with correct timezone.

## Actual Behavior

Always show UTC time.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Create container with TZ: 'Europe/Berlin'.
2. Check TZ in running container with
   ```
   # docker exec -ti pihole bash
   root@9fa8a12ef3a1:/# echo $TZ
   Europe/Berlin```
3.  Load Pi-Hole admin page -> settings -> system

## Debug steps I have tried
<!-- Please attempt these debug steps to see if it helps you resolve or understand your own issue -->

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar <!-- Add links below! -->

<!-- Note: If volumes are your issue, I strongly recommend just starting with fresh volume data -->

<!-- Add any other debugging steps you've taken that maybe relevant information -->

## Context and extra information
<!-- How has this bug affected you? What were you trying to accomplish? -->
<!-- Got any other relevant links to similar issues? -->

## Your Environment 
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Docker Host Operating System and OS Version: Fedora 30
* Docker Version: Docker version 1.13.1, build 47e2230/1.13.1 (Fedora Repo)
* Hardware architecture: x64
* Pi-hole Version v4.3.2 Web Interface Version v4.3.2 FTL Version v4.3.1

**Comment by DL6ER** [comment]
The shown time is directly queried from `pihole-FTL`. This service is (intentionally) entirely unaware of any timezone. The issue you are seeing is due to the lack of a timezone conversion on the client system. We will need to add some Javascript code to achieve this.

**Comment by dschaper** [comment]
Are you using Firefox with the privacy enhancements enabled? That will affect what time is displayed as they feel timezones are a way to fingerprint a browser session.

**Comment by eku** [comment]
@DL6ER 
>  We will need to add some Javascript code to achieve this.

Will this ever happen?

**Comment by dschaper** [comment]
Myabe

**Comment by tmo1** [comment]
> Are you using Firefox with the privacy enhancements enabled? That will affect what time is displayed as they feel timezones are a way to fingerprint a browser session.

I'm seeing the same annoyance despite Firefox ETP off for the site.

**Comment by Kline-** [comment]
> The issue you are seeing is due to the lack of a timezone conversion on the client system.

Are you sure this is the case? It looks like the time being reported is just a string and not an actual date object, unless I'm not understanding something about PHP correctly (which is quite likely).

[get_FTL_data()](https://github.com/pi-hole/AdminLTE/blob/cb7a866ff66cbd67252fb8cad8601870e7fe0d4b/settings.php#L236) looks like it's just dumping out a string, so I don't understand why the client would need to perform timezone conversion.

<pre>docker exec -i -t pihole /bin/bash
root@pihole:/# php -r 'phpinfo();' | grep 'TZ'
ICU TZData version => 2018e
TZ => America/Chicago
$_SERVER['TZ'] => America/Chicago

root@pihole:/# cat /var/run/pihole-FTL.pid 
414

root@pihole:/# php -r 'print_r(trim(exec("ps -p 414 -o lstart")));'
Thu Jan  6 01:02:31 2022</pre>
![image](https://user-images.githubusercontent.com/1126350/148398218-782b952d-fb73-4f64-84e1-091f1f0d7116.png)

**Comment by yubiuser** [comment]
We could switch from 
```
ps -p PID -o lstart
```

to something like

```
date -r /proc/PID '+%a %d %b %Y %R %Z'

Sat 05 Feb 2022 16:28 CET

```

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
