### ISSUE TITLE
Control structures should use curly braces

### ISSUE THREAD

**Issue by dwo** [pi-hole/AdminLTE#1027]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Background**

I was checking out the code and wondered what I might see in [SonarLint](https://www.sonarlint.org/). One of the most common issues raised was the lack of braces around control structures (such as `if`). SonarLint links to two sources can read about why this is important for security: [here](https://wiki.sei.cmu.edu/confluence/display/c/EXP19-C.+Use+braces+for+the+body+of+an+if%2C+for%2C+or+while+statement) or [here](https://wiki.sei.cmu.edu/confluence/display/java/EXP52-J.+Use+braces+for+the+body+of+an+if%2C+for%2C+or+while+statement).

**Expected behaviour:**

- All control structures should use curly braces
- Braces should be consistent within the codebase (ie. always same-line, or always on a new line)

**Actual behaviour:**

Some single-line control structures in the source have no braces.
https://github.com/pi-hole/AdminLTE/blob/34de877ccf0f530690ea3b7c44614872dfdb3d73/api.php#L37-L38

The majority of control structures that do have braces put them on a new line:
https://github.com/pi-hole/AdminLTE/blob/34de877ccf0f530690ea3b7c44614872dfdb3d73/api.php#L24-L27

Some others put the braces on the same line:
https://github.com/pi-hole/AdminLTE/blob/34de877ccf0f530690ea3b7c44614872dfdb3d73/api_FTL.php#L24-L26

**Steps to reproduce:**

You can open the source in IntelliJ IDEA Community and install the SonarLint plugin to see the control structures without braces.

If you wanted to go with whatever if the status quo in the codebase for a standard then...

Opening braces on new line total:
```
~/src/AdminLTE(devel)$ grep -R --exclude-dir=./scripts/vendor --include=*.php -E "^\s*{\s*$" . | wc -l
     441
```

Opening braces on same line total:
```
~/src/AdminLTE(devel)$ grep -R --exclude-dir=./scripts/vendor --include=*.php -E "(for|foreach|if|elseif|else|switch|while)\s*\(.*{\s*$" . | wc -l
     133
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

If you agree with my sentiment, I'd be happy to compose a pull request to make the codebase consistent in this regard: I don't think it would take me long to apply an agreed style using an IDE or Vim macros.

I'm less familiar with what tooling is available in the PHP ecosystem to maintain a codebase to stick to a standard / styleguide in a build or test suite. If you're open to it, maybe there is something we could run on Travis going forward to maintain consistent style and avoid basic lint problems?

**Comment by DL6ER** [comment]
Both links you provided mention the same source for a security issue:

> [...] a maintainer might subsequently add a debug statement or other logic but forget to add opening and closing braces.

> Because of the indentation of the code, it is difficult to tell that the code will not function as intended by the programmer, potentially leading to a security breach.

I don't think this happened to us in the past and I don't really see a code style unification being necessary for three reasons:
1. The code works as it is right now.
2. A code styling change would introduce (as you measured) a large number of changes without any functional benefit.
3. We are slowly running out this web interface in favor of https://github.com/pi-hole/web/ so your invested time would be lost at some point.

Pinging @dschaper @Mcat12 and @PromoFaux for their opinion on this topic.

**Comment by dwo** [comment]
I wanted to contribute something to prevent bugs in the future and make the code easier to read and contribute to. It will be wasted time if the plan is not to keep developing and maintaining this UI, so I'll close my issue. Thanks!

**Comment by dwo** [comment]
Perhaps you could make this future roadmap clearer in the README and/or CONTRIBUTING so that others don't jump into any such wasted time on this?
