### ISSUE TITLE
Login Shortcuts are hidden on larger screens (on dev)

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/AdminLTE#1032]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

7

---
**Expected behaviour:**

In PR #1017 the code has been changed to hide the shortcuts on small screens.

**Actual behaviour:**

The code has been modified to show the shortcuts _only on medium sized screens_. 
However, if the screen is larger, the keyboard shortcuts remain hidden.

**Steps to reproduce:**

- open the [login page](http://pi.hole/admin/index.php?login) (on current dev)
- zoom the site in / out to simulate all screen sizes (`xs, sm, md, lg`)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`-`

**Troubleshooting undertaken, and/or other relevant information:**

@Pazekal90: Please have another look at this.
`visible-md` in [Line 31 of loginpage.php](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/pi-hole/php/loginpage.php#L31) should be replaced by either
- `hidden-xs` or `visible-sm visible-md visible-lg` to hide it only on xtra-small screens
- `hidden-xs hidden-sm` or `visible-md visible-lg` to hide it on xtra-small and small screens.

**Comment by Pazekal90** [comment]
Sorry my fault. I will correct this in another PR.
