### ISSUE TITLE
DNS issue with PiHole

### ISSUE THREAD

**Issue by janvanveldhuizen** [pi-hole/AdminLTE#1034]
When I access my PiHole via it's IP address it works fine:

http://192.168.178.50:

![image](https://user-images.githubusercontent.com/43573150/67471106-267baf00-f64f-11e9-80cf-8a7a7a452fee.png)

But when I use its DNS name:
![image](https://user-images.githubusercontent.com/43573150/67471174-40b58d00-f64f-11e9-8113-524410f1f75a.png)

How can this be explained?

**Comment by dschaper** [comment]
The page you are seeing is a 404 response. `pancake.papasmurf.home` is 404 but instead of just seeing a 404 error from `lighttpd` you get the blockpage instead.

**Comment by janban-outlook** [comment]
I am still having this issue. Even after whitelisting the website.

![image](https://user-images.githubusercontent.com/43573150/82483774-40904980-9ad9-11ea-9736-4054d6923fbf.png)

![image](https://user-images.githubusercontent.com/43573150/82483795-4be37500-9ad9-11ea-96c4-29875fff23e9.png)

How can this be a 404 ??

**Comment by dschaper** [comment]
`curl -I http://pancake.papasmurf.home` will tell you.

**Comment by dschaper** [comment]
If your goal is to use that domain name for the admin page then you'll need to use something like `http://pancake.papasmurf.home/admin/`

**Comment by yubiuser** [comment]
Only `http://pi.hole` will automatically redirect to the admin page. If you use anything other than **pi.hole** then you'll need to go directly to `http://<custom>/admin/`.

This is a security feature to prevent someone external to your network being able to access the admin page.
