### ISSUE TITLE
Underscores ( _ ) considered invalid in Top Lists exclusions

### ISSUE THREAD

**Issue by nightah** [pi-hole/AdminLTE#1036]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The ability to exclude items from within Top Lists if they include an underscore `_`.

**Actual behaviour:**

When attempting to add a Top client with an underscore present the following error is presented:
```
Top Clients entry logstash-elastiflow.nerv_net is invalid (use only host names and IP addresses)!
The settings have been reset to their previous values
```

It also appears that if you add an underscore to the Top Domains / Top Advertisers lists that a similar error is thrown:
```
Top Domains/Ads entry logstash-elastiflow.nerv_net is invalid (use only domains)!
The settings have been reset to their previous values
```

**Steps to reproduce:**

- Login to Pihole
- Navigate to Settings -> API / Web Interface
- Attempt to add an entry in Top Lists which includes an underscore `_`
- Observe error

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`z9rivazfbw`

**Troubleshooting undertaken, and/or other relevant information:**

It appears that there was a change quite a while ago which allowed underscores in to domains https://github.com/pi-hole/pi-hole/pull/1571, without digging to deep I think what has happened is that the validation code for hosts/ip addresses in the top lists was not updated to allow underscores.

Given that we now can see all types of records including SRV I think it's important to also have the abillity to include underscores to exclude said clients or domains.

**Comment by DL6ER** [comment]
> Given that we now can see all types of records including SRV I think it's important to also have the abillity to include underscores to exclude said clients or domains.

I perfectly agree. You are also right about that we just forgot updating the validation logic on the web front end. We will make sure to fix this.

Thanks for using the Pi-hole!

**Comment by DL6ER** [comment]
I might have spoken too soon. I just checked the validator and it seems to be fine, c.f.,
https://regex101.com/r/tWPQvX/1

Indeed, it doesn't allow the domain you mentioned as underscores in the middle of the TLD (`nerv_net`) are considered invalid. Only one leading underscore would be accepted.

Do we need to change this? Also pinging @dschaper for his input on this question.

(The code we're currently using has been taken for here: http://stackoverflow.com/a/4694816/2087442)

**Comment by nightah** [comment]
https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it seems relevant.

While the regex currently being utilised works for SRV records it doesn't work with docker networked domains (the examples I provided).

**Comment by DL6ER** [comment]
Sorry for this to have taken so long to get addressed. See #1129

**Comment by nightah** [comment]
No problems at all, as always thanks for your support @DL6ER.
Looking at the PR I can see that it's linked with the v5.0 milestone, is there a rough estimate of when we expect this version to hit?

**Comment by DL6ER** [comment]
We're about to start the public beta at any point. Code-wise, I think it is ready. All it really seems to wait for is that we find the time to agree that *now* is the right time to start it. @PromoFaux already prepared a blog post some longer time ago IIRC.

**Comment by DL6ER** [comment]
@nightah This has been merged and is available in the currently running Pi-hole v5.0 beta.

**Comment by nightah** [comment]
Thanks @DL6ER.
@diginc any chance you can throw up a beta Docker container for us folk to try, test and support the beta?

**Comment by diginc** [comment]
One pushed earlier today `docker pull pihole/pihole:beta-v5.0`

https://hub.docker.com/layers/pihole/pihole/beta-v5.0/images/sha256-26f537b14589b0b31627691d01c5fa97252cfeec7f498ad99cbe9cb21c3d6c21

**Comment by nightah** [comment]
Ah, my apologies I missed that!
I'll give it a try, thanks :).

**Comment by nightah** [comment]
Can confirm from my perspective this now works as intended, great work with v5 in general team!
