### ISSUE TITLE
Long term query failure

### ISSUE THREAD

**Issue by Jhfelectric** [pi-hole/AdminLTE#1037]
Hi,
Creating this issue asked by @dschaper.
Please be aware that my fix below actually removes the bad domain names from the retrieved list of domains. A better fix would be to either allow non-ascii chars when reading/writing the domain names in the db, or convert non-ascii chars when writing to the db.
Cheers.

_Originally posted by @Jhfelectric in https://github.com/pi-hole/pi-hole/issues/2576#issuecomment-546317127_

Hi, 
Commenting on this as the same error can be observed when the list of domains contains bad chars. In my case, I figured out some of the domain names recorded in the 'queries' table of the SQLite3 database had bad chars or possibly non-ascii chars. While this shouldn't be an issue in most cases, here it seems to break the returned list of domains. While browsing the pihole-FTL.db I found multiple occurences of domains b._dns-sd._udp.?? as well as same starting with db, r, dr and lb. Using only a terminal, I was unable to 'see' those bad chars, they only appeared with ??. 
This can easily be fixed by adding a GLOB clause in the relevant query used to retrieve the domains. I modified the line 115 of file AdminLTE/api_db.php (https://github.com/pi-hole/AdminLTE/blob/38d8e77f999ba5999c013b44f6e8fe808308de7a/api_db.php#L115) like this:

`		$dbquery = "SELECT timestamp, type, domain, client, status FROM queries WHERE  domain NOT GLOB ('*[^'||char(1,45,127)||']*') and timestamp >= :from AND timestamp <= :until ";`

The GLOB clause will reject any domain containing non-ascii chars using a regex.
This solution solved my problem but of course one will miss out those excluded records.

Thanks to these blog entries:
https://discourse.pi-hole.net/t/long-term-data-query-unknown-error-occured/20259/15
http://sqlite.1065341.n5.nabble.com/Finding-records-containing-non-ascii-characters-td86959.html

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
