### ISSUE TITLE
Hovertip displays wrong numbers (Top Clients (blocked only))

### ISSUE THREAD

**Issue by simphide** [pi-hole/AdminLTE#1038]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`6`

---
**Expected behaviour:**

`the hovertip shows the client's percentage of blocked queries and the total amount of blocked queries`

**Actual behaviour:**

`It shows the clients percentage of the blocked queries, but the number behind it is showing the amount of total queries and not the amount of blocked queries`

**Steps to reproduce:**

`Hover over an entry in the list`
![pihole bug](https://user-images.githubusercontent.com/8183517/68068418-d5597280-fd54-11e9-9e4d-dde350ea3b48.png)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

not necessary

**Troubleshooting undertaken, and/or other relevant information:**

-

**Comment by DL6ER** [comment]
Thank you for reporting this bug. We already discovered it's source. It will be fixed by #1040 

Thanks for using the Pi-hole!

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
