### ISSUE TITLE
API.php is returning Json with incorrect type (string instead of integer).

### ISSUE THREAD

**Issue by mwoolweaver** [pi-hole/AdminLTE#1041]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

Gravity Last Updated relative value should be of type int

**Actual behaviour:**

Gravity Last Updated relative value is type string

**Steps to reproduce:**
View json output of api.php

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

sfn4nq9wqf

**Troubleshooting undertaken, and/or other relevant information:**

None as I’m not sure where the error is at in code.

**Comment by DL6ER** [comment]
PHP does not recognize that the value returned from the database is an integer.

https://github.com/pi-hole/AdminLTE/blob/678155fc54bc5a3232eb5da64c1a6fdb49195c3a/scripts/pi-hole/php/gravity.php#L14

From here on, all -- absolute and relative -- values are computed correctly but handled as strings when added to the to be returned array.

**Comment by mwoolweaver** [comment]
You sir are amazing! Patiently waiting for merge into /devel
