### ISSUE TITLE
Chrome 78 do not display Queries Blocked and Percent Blocked properly

### ISSUE THREAD

**Issue by michalzimniak** [pi-hole/AdminLTE#1043]
Im using current version or pihole on ubuntu 16.04LTS using Apache.

On Google Chrome 78 web admin do not shows Queries Blocked and Percent Blocked.

Please check the screenshot:

![image](https://user-images.githubusercontent.com/7513244/68545660-6a044600-03cf-11ea-9c39-d0e36fcb52be.png)

**Comment by dschaper** [comment]
Thanks for the report, can you please run `pihole -d` and get us the token?

**Comment by michalzimniak** [comment]
No problem: https://tricorder.pi-hole.net/x76sm87p63

**Comment by DL6ER** [comment]
@michalzimniak Can you open the "Console" (usually it is hidden in the developer tools, try [F12]) and check whether there are any errors show with Chrome? You may need to reload the page after opening the console.

**Comment by michalzimniak** [comment]
@DL6ER No errors, warnings displayed in js console:

![image](https://user-images.githubusercontent.com/7513244/68549528-28889080-03f9-11ea-8782-c53482c23c37.png)

**Comment by dschaper** [comment]
Can you check the page source and see if there is anything by the `<span id="ads_blocked_today">` element?

**Comment by DL6ER** [comment]
Also, can you please verify that the issue still persists when you (temporarily) disable some (and once all) of your browser plugins?

**Comment by michalzimniak** [comment]
Ahhh, I didn't think about checking it out - its a uBlock rules issue... If uBlock disabled everything works fine:

![image](https://user-images.githubusercontent.com/7513244/68550336-37c00c00-0402-11ea-83be-2b9b9829afa5.png)

Thanks for the fix ;)
