### ISSUE TITLE
inconsistent relative paths (links) in three js files

### ISSUE THREAD

**Issue by vicival** [pi-hole/AdminLTE#1047]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
8

**Expected behaviour:**

 If someone pastes all these AdminLTE files at the root of an "independent"   http://pi.net   website 
(so **not just as a subdirectory** of an Apache root website for eg), **a few features (forms) will not work** (nothing happens when you push those submit buttons) 
**because three .js files contain _an extra '/admin/'_ in some of their  relative paths**, 
so they are 'relativelly' pointing to a directory that does not exist in this web app where all links 
**should be** relative to the root:
 
`{Steps of what you have done to fix this}`

 **Remove** all '/admin/ ' occurrences from these files: 

**/scripts/pi-hole/js/debug.js**

**/scripts/pi-hole/js/network.js**

**/scripts/pi-hole/js/queryads.js**

Here's a pic [https://ibb.co/2tYpkMt](https://ibb.co/2tYpkMt)

**Comment by XhmikosR** [comment]
I believe this was fixed in v5.0.
