### ISSUE TITLE
Unable to set hostnames containing dots

### ISSUE THREAD

**Issue by xorz57** [pi-hole/AdminLTE#1055]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`When I go to the Dashboard page, under the Top Clients categories I should see my hostnames uncut`

**Actual behaviour:**

`When I go to the Dashboard page, under the Top Clients categories I see my hostnames cut just before the first dot appears`

**Steps to reproduce:**

`Go to Settings, under DHCP select one of the currently active DHCP leases (just to be sure) and click the orange paste icon on the right. Then just rename the hostname for that device and click the green plus button on the right side. When you go back to the Dashboard page the names are cut just before the first dot`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Do you mean subdomains? Hostnames can't contain dots as that is the demarcation between domains.

ex: this.host.example.com is a node called 'this' in the subdomain 'host.example.com'.

**Comment by xorz57** [comment]
@dschaper I really don't know if what I did was a good idea or just something dumb. I have 2 devices and I want to give them different names like `mobile.george`, `mobile.nick`. What should appear under top devices I thought would be `mobile.george.lan` and `mobile.nick.lan` but instead I get `mobile.lan` and `mobile.lan`.

**Comment by xorz57** [comment]
Again if the problem is that hostnames must not contain dots that is ok! I didn't know that. But there was no warning to prevent me from using dots. Maybe that can be implemented in the future I guess.

**Comment by dschaper** [comment]
In the example you gave there would be two different domains. `george.lan` and `nick.lan` with hosts in each domain named `mobile`. Similar to how `www.google.com` and `www.apple.com` both have hosts named `www` but in two different domains.

**Comment by xorz57** [comment]
@dschaper I think I understand what you mean now. I have to look up the naming convention I guess. Well ... seems like it is not an actual issue. You can close it if needed! Thanks for explaining!

**Comment by dschaper** [comment]
Glad to help. If you wanted to segregate things you could set up a `mobile.lan` domain with `george.mobile.lan` and `nick.mobile.lan` but that could get a little heavy to maintain along with clients in the `.lan` domain or `wired.lan`. Might just be easier to use a hypen in place of the dot. `george-moblie.lan`.

**Comment by xorz57** [comment]
@dschaper I used a hyphen instead and it works like charm! Thanks a lot and have a nice day!
