### ISSUE TITLE
bad wording on regex whitelist site (in dev)

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/AdminLTE#1056]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Expected behaviour:**
If I am on the [whitelist site](http://pi.hole/admin/list.php?l=white), I would not expect to see heading 'blocking' above the table/s.
Instead I would expect heading like 'Exact <i>un</i>blocking', 'Exact whitelisting' or just 'Exact'

**Actual behaviour:**
<img width="700px" alt="whitelisting" src="https://user-images.githubusercontent.com/28313514/69752046-ac0fe480-1150-11ea-8bb7-8a1244fdbbcf.PNG">

**Steps to reproduce:**
Switch to current dev branch and open the [whitelist site](http://pi.hole/admin/list.php?l=white).

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
`-`

**Troubleshooting undertaken, and/or other relevant information:**
none

**Comment by PromoFaux** [comment]
Good catch... Thanks! Feel free to submit a PR against dev if you would like, or we can fix and credit back to this issue if you would prefer?

**Comment by Th3M3** [comment]
I can gladly make a pull request.

Wich wording would you prefer for the headings?
'Exact _unblocking_' / Wildcard _unblocking_
'Exact _whitelisting_' / Wildcard _whitelisting_
Just 'Exact' or something else?

**Comment by PromoFaux** [comment]
Sorry, saw you reply to this the other day and then i never got around to replying, but looking at your PR you've gone with what I was going to suggest in any case :)

**Comment by PromoFaux** [comment]
It's more or less what we have in the future [react-based web](https://github.com/pi-hole/web), in any case 

![image](https://user-images.githubusercontent.com/1998970/70082860-351c9500-1603-11ea-9e79-e487d07cedfd.png)

**Comment by yubiuser** [comment]
Fixed a long time ago with https://github.com/pi-hole/AdminLTE/pull/1058
