### ISSUE TITLE
Folk pi-hole AdminLTE dashboard for comercial inhouse product.

### ISSUE THREAD

**Issue by brenkem** [pi-hole/AdminLTE#1057]
Sorry for putting this topic here, but we want to use your great dashboard for a product that will only be used in your company. We want to apply a dashboard to a small embedded system to make it easier to use.

Can we use it with the EUPL licence only for our inhouse product? We will not sell it to customers.

Best regards.

P.s.: Maybe we can place a donation after we have finished the project.
(I will delete the "issue" afterwards.)

**Comment by PromoFaux** [comment]
Do you mean just the structure of the dashboard, for completely different information unrealted to Pi-hole?

If so.. we just use a template called AdminLTE , which is freely available from here:

https://adminlte.io/

:)

**Comment by brenkem** [comment]
Hi,

I already checked out the AdminLTE template. But you made some great changes (heavy PHP usage) and also some status information in the sidebar are compatible to your hardware platform.
So we would like to use the header, sidebar, and footer of your web interface.

But I am not sure regarding the license if its okay when we do it that way.
Can you tell me if its okay to use your web interface (maybe make a folk) and use it without selling it to any one. But do we need to make our code public in this case?

**Comment by dschaper** [comment]
Thanks for the question. When it comes to legalities, we aren't the best to be able to advise how to proceed. We do the coding and the lawyers do the lawyering (at a hefty cost.) My personal thoughts, if you're not making something to confuse users and have them believe they are using Pi-hole then fork and go from there. I interpret the copyright and the EUPL license to say that any improvements or changes you make must (should?) be offered back to the upstream (us) and you allow us to use those improvements with our own code, if we would like to. But I don't think it gives us free access to your code base nor requires full disclosure of your code. 

I'm inclined to say "be fair" and do what you think is right. Aside, I always feel bad when people see the AdminLTE panel used in other projects and they think it's someone taking advantage of us when really the whole look is from the AdminLTE project. 

We're moving away from the PHP code anyways and using a different language so the whole thing may just become moot in a near time anyways. I'll let the rest of the team add any thoughts they have as it's all of their work and I don't want to unilaterally speak for everyone.
