### ISSUE TITLE
Space in API token page

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/AdminLTE#1060]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [ ] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The selected token should **not** have whitespace. This is noticeable when copying the raw API key on Android.

**Actual behaviour:**

A newline or whitespace character is added at the end

**Steps to reproduce:**

Visit `http://pi.hole/admin/scripts/pi-hole/php/api_token.php` and inspect the `Raw API Token`

I still haven't got the time to test a potential fix locally. That being said, this probably fixes the issue:

```diff
 scripts/pi-hole/php/api_token.php | 4 +---
 1 file changed, 1 insertion(+), 3 deletions(-)

diff --git a/scripts/pi-hole/php/api_token.php b/scripts/pi-hole/php/api_token.php
index ae6ce9d5..9fd686d5 100644
--- a/scripts/pi-hole/php/api_token.php
+++ b/scripts/pi-hole/php/api_token.php
@@ -11,9 +11,7 @@ if($auth)
     require_once("../../vendor/qrcode.php");
     $qr = QRCode::getMinimumQRCode($pwhash, QR_ERROR_CORRECT_LEVEL_Q);
     $qr->printHTML("10px");
-    print("Raw API Token: ");
-    print($pwhash); 
-
+    echo "<br>Raw API Token: <code>" . $pwhash . "</code>";
   }
   else
   {

````

**Comment by XhmikosR** [comment]
I tried editing `/var/www/html/admin/scripts/pi-hole/php` but the changes weren't being reflected even after restarting lighttpd.

**Comment by XhmikosR** [comment]
This is where I hit this https://github.com/sterrenburg/flutterhole/issues/60#issuecomment-562822736

**Comment by PromoFaux** [comment]
> EDIT: NVM, it appears to be working now. I wonder, how does one restore those files to the default?

The `/admin` directory is just a clone of the repo, so:

```
cd /var/www/html/admin && git reset --hard
```

should do it...

**Comment by XhmikosR** [comment]
Perfect, thanks for the info :)

**Comment by PromoFaux** [comment]
I will try and review your PR(s!) later, if not tomorrow. Tis the season for weekend merriment and all!

**Comment by jdrch** [comment]
Same issue as @XhmikosR reported. Broke Flutterhole for me.

**Comment by XhmikosR** [comment]
This was fixed in  https://github.com/pi-hole/AdminLTE/pull/1061
