### ISSUE TITLE
Unable to maintain black/white list in web interface

### ISSUE THREAD

**Issue by JorenBai** [pi-hole/AdminLTE#1077]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`domains shall be added to the black/white list in the web interface`

**Actual behaviour:**

`An Err MSG:
Failure! Something went wrong, see output below:

Error: attempt to write a readonly database, added 0 domains
`
`
and the black/white list is empty, but view the /etc/pihole/black.list & blacklist.txt & regex.list & whitelist.txt, all of them have contents.
`

**Steps to reproduce:**

`When adding domains`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/rcmojcphtu`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by DL6ER** [comment]
From your debug log, I see you're running the up-to-date `development` version of Pi-hole.

Web: https://github.com/pi-hole/AdminLTE/commit/23ac374ff03f2ba3e0be8df29eedd5596ab11884
Core: https://github.com/pi-hole/pi-hole/commit/2cec9eaf650abffd256b922b55a3933ad925cd66
FTL: https://github.com/pi-hole/FTL/commit/83018ac1dd89cf645f4f5ba41fbd06f7af45d530

The error
```
Error: attempt to write a readonly database, added 0 domains
```
points to incorrect permissions for the directory `/etc/pihole` and/or the database itself `/etc/pihole/gravity.db`

Please check the permissions with
```
ls -lah /etc | grep pihole
ls -lah /etc/pihole/gravity.db
```
both should be owned by `pihole:pihole`.

From your debug log, I also found another error where we forgot to update the lists reader. I will prepare a bug fix for this and come back to you in a few minutes.

Thanks for using the Pi-hole!

**Comment by DL6ER** [comment]
The "bug" was actually none, the corresponding changes are simply not merged to `development` yet. https://github.com/pi-hole/AdminLTE/pull/1078

Check if you can use the list edit interface after running
```
pihole checkout web tweak/domainlist_table
```
(and possibly fixing the permissions as I wrote above).

**Comment by JorenBai** [comment]
> “错误”实际上是没有，相应的更改根本没有被合并`development`。[＃1078](https://github.com/pi-hole/AdminLTE/pull/1078)
> 
> 运行后检查是否可以使用列表编辑界面
> 
> ```
> pihole checkout web tweak/domainlist_table
> ```
> 
> （并可能修复了我上面写的权限）。

```
pi@raspberrypi:~ $ ls -lah /etc | grep pihole
drwxr-xr-x  10 root   root                4.0K Dec 14 06:59 .pihole
drwxr-xr-x   3 pihole pihole              4.0K Dec 15 07:34 pihole
pi@raspberrypi:~ $ ls -lah /etc/pihole/gravity.db
-rw-rw-r-- 1 pihole pihole 8.6M Dec 15 03:29 /etc/pihole/gravity.db
pi@raspberrypi:~ $ pihole checkout web tweak/domainlist_table
  Please note that changing branches severely alters your Pi-hole subsystems
  Features that work on the master branch, may not on a development branch
  This feature is NOT supported unless a Pi-hole developer explicitly asks!
  Have you read and understood this? [y/N] y

  [✓] Fetching branches from https://github.com/pi-hole/AdminLTE.git
  [i] 9 branches available for Web Admin

  [✓] Switching to branch: 'tweak/domainlist_table' from 'refs/heads/tweak/domainlist_table'
Already up to date.
```
The operation is successful, and the results have been attached, i can see the lists are not empty now.
However, when the web interface is operated, it still displays errors
![blacklist](https://user-images.githubusercontent.com/13309787/70855969-483a3980-1f0e-11ea-8b8b-86d28b82c6a3.png)

**Comment by DL6ER** [comment]
Okay, next thing to check is if your user `lighttpd` is member of the group `pihole`. If not, the web interface cannot write to the database.

**Comment by JorenBai** [comment]
> Okay, next thing to check is if your user `lighttpd` is member of the group `pihole`. If not, the web interface cannot write to the database.

```
pi@raspberrypi:~ $ cat /etc/passwd | grep lighttpd
pi@raspberrypi:~ $ groups pihole
pihole : pihole www-data
```
It seems that there is no `lighttpd` user

**Comment by DL6ER** [comment]
Okay, so it seems to be `www-data`, my mistake.

I missed in your message above
> ```
> drwxr-xr-x   3 pihole pihole              4.0K Dec 15 07:34 pihole
> ```

that the folder is not group-writable.

Please try
```
sudo chmod g+w /etc/pihole
sudo -u www-data sqlite3 "/etc/pihole/gravity.db" "INSERT INTO info VALUES ('something','something');"
sudo -u www-data sqlite3 "/etc/pihole/gravity.db" "DELETE FROM info WHERE property = 'something';"
```
It should not say anything when it works.

**Comment by JorenBai** [comment]
> Okay, so it seems to be `www-data`, my mistake.
> 
> I missed in your message above
> 
> > ```
> > drwxr-xr-x   3 pihole pihole              4.0K Dec 15 07:34 pihole
> > ```
> 
> that the folder is not group-writable.
> 
> Please try
> 
> ```
> sudo chmod g+w /etc/pihole
> sudo -u www-data sqlite3 "/etc/pihole/gravity.db" "INSERT INTO info VALUES ('something','something');"
> sudo -u www-data sqlite3 "/etc/pihole/gravity.db" "DELETE FROM info WHERE property = 'something';"
> ```
> 
> It should not say anything when it works.

It works, thank you.
