### ISSUE TITLE
add i18n / multilang support

### ISSUE THREAD

**Issue by dannycolin** [pi-hole/AdminLTE#109]
It would be great to have the administrator interface in our own language.
By the way, I can help with french translation 
##

**Comment by PromoFaux** [comment]
Not a bad shout! 

@Mcat12 does this sound plausible?

**Comment by brantje** [comment]
Should be possible with php / Angular, not sure about  Flask.

**Comment by brantje** [comment]
With commit a225f70 i added translation support for the admin interface.
However, translations don't write them self (to bad..).
So if you willing to help translating, use [this](https://github.com/brantje/AdminLTE/blob/devel/languages/en.json) as template

**Comment by PromoFaux** [comment]
Dutch is good! :wink: 

![image](https://cloud.githubusercontent.com/assets/1998970/16540757/2aa082c8-4067-11e6-9682-eb87db5d7530.png)

**Comment by brantje** [comment]
Translating is not really my thing, but i'll give it a try

**Comment by brantje** [comment]
Translators wanted: https://poeditor.com/join/project/7LnOlpfC3o

**Comment by develmts** [comment]
Catalan Translation done at https://poeditor.com/join/project/7LnOlpfC3o

**Comment by DL6ER** [comment]
What is the current status? I see that much work went into the AngularJS branch concerning i18n translation. I'd like to bring this to the current version (I'm an experienced programmer with some spare time for this project). I could test it with English and German.

What do you think?

**Comment by DL6ER** [comment]
More background: I'm currently writing an article for a quite recognized journal for electronics about how to install pi-hole Raspberry Pi. As the article will be in German, I'm currently thinking that having i18n support could be a good idea.

**Comment by Mcat12** [comment]
The current web interface does not have support for other languages, but the angular rewrite does. @brantje would be more knowledgeable in how feasible it would be to implement other languages in the current web interface.

**Comment by Tntdruid** [comment]
Any new about this?

**Comment by Mcat12** [comment]
Since the original Angular 1 prototype of the web interface, we've moved to a React-based interface which you can fine here: https://github.com/pi-hole/web

It's in development right now, and I plan on adding internationalization soon, but we do welcome pull requests. When it is added to the web interface, the strings on POEditor will be adjusted to fit the new requirements.

**Comment by Mcat12** [comment]
Closing this issue as internationalization will be happening instead on the new web interface.

Follow it here: pi-hole/web#17
