### ISSUE TITLE
Tooltip background not full width of tooltip box in Brave Browser

### ISSUE THREAD

**Issue by tomasnorre** [pi-hole/AdminLTE#1096]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

This might be the place where the tool tip gets rendered.
https://github.com/pi-hole/AdminLTE/blob/38d8e77f999ba5999c013b44f6e8fe808308de7a/scripts/pi-hole/js/index.js#L748

---
**Expected behaviour:**

I would expect the background off the tool tip to be the full width of the tool tip, so that I can read the information in the box. Bright on white, is difficult to read.

**Actual behaviour:**

![Screenshot 2019-12-18 at 10 31 27](https://user-images.githubusercontent.com/1212481/71074430-88a1ed80-2182-11ea-9beb-008186a9ddfc.png)

Here I've changed the background-color for `<canvas id="queryOverTimeChart"> to `grey` to better visualise the problem. 

![Screenshot 2019-12-18 at 10 41 24](https://user-images.githubusercontent.com/1212481/71074753-1e3d7d00-2183-11ea-8c3c-5cadecc2fc5e.png)

**Steps to reproduce:**

* Open my "Brave" Browser
* I logged into my PI Hole admin
* Went to dash board
* Hovered over the graph `Queries over last 24 hours` 

FYI: This is only reproducible in Brave, have testet with Firefox, Safari, Chrome and Opera, non of them had the issue, so it might be really low on priority.

**Comment by DL6ER** [comment]
We're using the popular chart generator `Chart.js` and it seems your issue is already known: https://github.com/chartjs/Chart.js/issues/6411
Feel free to put your comment there as this is the project where it'd need to get fixed in. I don't think we can do anything more for you. Sorry.
