### ISSUE TITLE
lighttpd error - dashboard not accessible

### ISSUE THREAD

**Issue by froedel** [pi-hole/AdminLTE#1107]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
3

---
**Expected behaviour:**
Dashboard overview page

**Actual behaviour:**
Dashboard page not loading, but shows only below icons.

![2019-12-27 20-06-40](https://user-images.githubusercontent.com/59291129/71529368-a1c63f00-28e4-11ea-93f9-9307cf7e50d9.png)`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
qlfx2x7jsd

**Troubleshooting undertaken, and/or other relevant information:**
- pihole -r with repair option as well as reconfiguration
- checking lighttpd service status - service running:

> pi@pi:~ $ sudo service lighttpd status
> ● lighttpd.service - Lighttpd Daemon
>    Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
>    Active: active (running) since Fri 2019-12-27 19:56:15 CET; 20h ago
>  Main PID: 6824 (lighttpd)
>     Tasks: 6 (limit: 2305)
>    Memory: 9.1M
>    CGroup: /system.slice/lighttpd.service
>            ├─6824 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
>            ├─6836 /usr/bin/php-cgi
>            ├─6837 /usr/bin/php-cgi
>            ├─6838 /usr/bin/php-cgi
>            ├─6839 /usr/bin/php-cgi
>            └─6840 /usr/bin/php-cgi
> 
> Dec 27 19:56:17 pi systemd[1]: /lib/systemd/system/lighttpd.service:6: PIDFile= references path below legacy directory /var/run/, updating /var/run/lighttpd.pid
> Dec 27 19:56:17 pi systemd[1]: /lib/systemd/system/lighttpd.service:6: PIDFile= references path below legacy directory /var/run/, updating /var/run/lighttpd.pid
> Dec 27 19:56:18 pi systemd[1]: /lib/systemd/system/lighttpd.service:6: PIDFile= references path below legacy directory /var/run/, updating /var/run/lighttpd.pid
> Dec 27 19:56:19 pi systemd[1]: /lib/systemd/system/lighttpd.service:6: PIDFile= references path below legacy directory /var/run/, updating /var/run/lighttpd.pid
> Dec 27 19:57:53 pi sudo[7866]: www-data : TTY=unknown ; PWD=/var/www/html/admin/scripts/pi-hole/php ; USER=root ; COMMAND=/usr/local/bin/pihole -q -adlist local
> Dec 27 19:57:53 pi sudo[7866]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Dec 27 19:57:53 pi sudo[7866]: pam_unix(sudo:session): session closed for user root
> Dec 27 19:57:54 pi sudo[7898]: www-data : TTY=unknown ; PWD=/var/www/html/admin/scripts/pi-hole/php ; USER=root ; COMMAND=/usr/local/bin/pihole -q -adlist local
> Dec 27 19:57:54 pi sudo[7898]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Dec 27 19:57:54 pi sudo[7898]: pam_unix(sudo:session): session closed for user root

- pihole -d revealed issue between pihole and lighttpd see output below:

> -rw-r--r-- 1 www-data www-data 19512 Dec 27 19:57 /var/log/lighttpd/error.log
> 2019-12-22 00:00:00: (server.c.1759) logfiles cycled UID = 0 PID = 14344 
>    2019-12-27 16:34:27: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  session_start(): Cannot start session when headers already sent in /var/www/html/admin/scripts/pi-hole/php/password.php on line 12
>    2019-12-27 16:34:27: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function check_cors() in /var/www/html/admin/scripts/pi-hole/php/header.php:12
>    2019-12-27 16:34:27: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:
>    2019-12-27 16:34:27: (mod_fastcgi.c.421) FastCGI-stderr: 
>    2019-12-27 16:34:27: (mod_fastcgi.c.421) FastCGI-stderr: 
>    2019-12-27 16:34:27: (mod_fastcgi.c.421) FastCGI-stderr:   thrown in /var/www/html/admin/scripts/pi-hole/php/header.php on line 12
>    2019-12-27 16:34:54: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  session_start(): Cannot start session when headers already sent in /var/www/html/admin/scripts/pi-hole/php/password.php on line 12
>    2019-12-27 16:34:54: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function check_cors() in /var/www/html/admin/scripts/pi-hole/php/header.php:12
>    2019-12-27 16:34:54: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:
>    2019-12-27 16:34:54: (mod_fastcgi.c.421) FastCGI-stderr: 
>    2019-12-27 16:34:54: (mod_fastcgi.c.421) FastCGI-stderr: 
>    2019-12-27 16:34:54: (mod_fastcgi.c.421) FastCGI-stderr:   thrown in /var/www/html/admin/scripts/pi-hole/php/header.php on line 12
>    2019-12-27 16:34:56: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  session_start(): Cannot start session when headers already sent in /var/www/html/admin/scripts/pi-hole/php/password.php on line 12
>    2019-12-27 16:34:56: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function check_cors() in /var/www/html/admin/scripts/pi-hole/php/header.php:12
>    2019-12-27 16:34:56: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:
>    2019-12-27 16:34:56: (mod_fastcgi.c.421) FastCGI-stderr: 
>    2019-12-27 16:34:56: (mod_fastcgi.c.421) FastCGI-stderr: 
>    2019-12-27 16:34:56: (mod_fastcgi.c.421) FastCGI-stderr:   thrown in /var/www/html/admin/scripts/pi-hole/php/header.php on line 12
>    2019-12-27 16:35:52: (server.c.2059) server stopped by UID = 0 PID = 1 
>    2019-12-27 16:36:22: (server.c.1464) server started (lighttpd/1.4.53) 
>    2019-12-27 16:36:22: (server.c.1493) WARNING: unknown config-key: alias.url (ignored) 
>    2019-12-27 16:38:43: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  session_start(): Cannot start session when headers already sent in /var/www/html/admin/scripts/pi-hole/php/password.php on line 12
>    2019-12-27 16:38:43: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function check_cors() in /var/www/html/admin/scripts/pi-hole/php/header.php:12
>    2019-12-27 16:38:43: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:

**Comment by DL6ER** [comment]
> ```
> 2019-12-27 16:34:27: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error: Uncaught Error: Call to undefined function check_cors() in /var/www/html/admin/scripts/pi-hole/php/header.php:12
> ```

Hmm, `check_cors()` is defined here:

https://github.com/pi-hole/AdminLTE/blob/38d8e77f999ba5999c013b44f6e8fe808308de7a/scripts/pi-hole/php/auth.php#L25

Can you check if this file has been changed locally?

What is the output of
```
cd /var/www/html/admin
git status
```
?

**Comment by froedel** [comment]
Hi,
file auth.php seems corrupted and shows the same characters as when calling (in my case) 192.168.175.2/admin via web browser.

> root@pi:/var/www/html/admin/scripts/pi-hole/php# more auth.php 
> ������������������������������������������

Last modification of auth.php was:
> -rw-r--r-- 1 root root 4.9K Nov  3 12:36 auth.php

Output of cd /var/www/html/admin
git status

> root@pi:/var/www/html/admin/scripts/pi-hole/php# cd /var/www/html/admin
> root@pi:/var/www/html/admin# git status
> On branch master
> Your branch is up to date with 'origin/master'.
> nothing to commit, working tree clean

Shall I restore auth.php with code form https://github.com/pi-hole/AdminLTE/blob/38d8e77f999ba5999c013b44f6e8fe808308de7a/scripts/pi-hole/php/auth.php#L25 again?

**Comment by froedel** [comment]
Restored auth.php with original code. Everything works again.

I am unable to resolve the issue why auth.php got corrupted.
Thank you for your support.

Closed.
