### ISSUE TITLE
Change `Time FTL started` to show the date too

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/AdminLTE#1108]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---

I think it would make more sense to show the date and time FTL was started. After one day, currently only the date is shown. We could probably add this in a `time` element https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time like:

```html
<time datetime="2019-12-28T17:49:13+02:00" title="Sat, 28 Dec 2019 17:49:13 +0200">28 December 2019</time>
```

maybe without the timezone, but you get the idea.

Not sure if the info FTL returns contains the date too, I just thought I'd report this.

**Comment by DL6ER** [comment]
This field shows the output of
```
ps -p $(pidof pihole-FTL) -o start
```
which does not include the time (see [here](https://github.com/pi-hole/AdminLTE/blob/38d8e77f999ba5999c013b44f6e8fe808308de7a/settings.php#L1250)). We could maybe change this to showing the last modification date of the PID file, but we need some further discussion if this is truly equivalent.

**Comment by yubiuser** [comment]
Use 
`ps -p $(pidof pihole-FTL) -o lstart` instead

source: [https://www.shellhacks.com/linux-ps-command-get-process-start-time-date/](url)

**Comment by yubiuser** [comment]
Has been fixed a long time ago with https://github.com/pi-hole/AdminLTE/pull/1501
