### ISSUE TITLE
Revisit CSP

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/AdminLTE#1118]
Which file needs `'unsafe-eval'`? We shouldn't allow this IMHO.

And assuming we manage to update all 3rd-party libraries to the latest version, chances are some issues are fixed.

**Comment by yngndrw** [comment]
It looks like it was [originally added for Chart.js](https://github.com/pi-hole/AdminLTE/commit/46df1bddc505cd555a094058092d65abd67368b9) on 2016/05/08, but [Chart.js was then updated](https://github.com/pi-hole/AdminLTE/commit/24d4b63a55d6df3d267e9cc2da28d686b3aa7c77#diff-562aea58d2869312661648106d903cbc) on 2017/10/31. I couldn't find any reference to the eval function in [Chart.js](https://github.com/pi-hole/AdminLTE/blob/master/scripts/vendor/Chart.bundle.min.js) so I suspect it's no-longer required.

**Comment by XhmikosR** [comment]
That sounds perfect! Can you make a PR making CSP stricter after testing it?

**Comment by XhmikosR** [comment]
Fixed by #1377.
