### ISSUE TITLE
Privacy - Query Page and Dom.storage

### ISSUE THREAD

**Issue by ghost** [pi-hole/AdminLTE#1119]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{5}`

---
**Expected behaviour:**

`{The query page should work with dom.storage disabled. Dom.storage can be used in many manipulative ways to track users cross-site and across devices. Users who have dom.storage disabled should also have a way to view the query page. }`

**Actual behaviour:**

`{The part of the code where the issue stems from can be trivially located using the Developer Console. Users who disable dom.storage are unable to see anything on the query page. This is how it looks like if you disable dom.storage in Firefox: }`
[Imgur](https://i.imgur.com/kvFx2Ra.png)

**Steps to reproduce:**

`{This applies only to Firefox: 1) Go to: about:config. 2) Set: dom.storage.enabled to false. 3) Go to the query page of your pi.hole}`

**Troubleshooting undertaken, and/or other relevant information:**
I know that this isn't technically an issue, but rather an improvement. If it can changed by the pi.hole team without extensive effort, then I'm sure a small subset of users would welcome it. Right now one is forced to either be blind in the query log or have dom.enabled (former is an inconvenience (except when you want to figure out why some website isn't working), later is a huge privacy risk).

Thank you for all the work so far.

**Comment by XhmikosR** [comment]
It seems the root cause is that `localStorage` is null in the case of `dom.storage.enabled` set to `false`.

I think we should have a common function to check for locarStorage availability and guard the code. Otherwise, monkey patching it with `localStorage && localStorage.getItem("foo")` might work but I think the other solution is cleaner if we want to check all localStorage instances. If we only care about the queries page, I guess we can go with the second solution.

**Comment by yubiuser** [comment]
Removing "Submitter Attention Required" because we have an open PR linked.

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
