### ISSUE TITLE
display errors on small screens (on group management sites and others)

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/AdminLTE#1127]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

7

---
**Expected behaviour:**

The _Group Management_ sites should also be correctly displayed on small screens (without wrapping out of the viewport)

**Actual behaviour:**

- Currently the sites are not useable on small screens and the pagination looks odd:
  <img width="216" alt="group-domains1" src="https://user-images.githubusercontent.com/28313514/71787342-d9d12e80-3016-11ea-94bc-984838bf2bfb.png">
- Furthermore the vertical spacing between the `<input>` and the following `<label>` looks off. 
  <img width="216" alt="group-domains2" src="https://user-images.githubusercontent.com/28313514/71787370-27e63200-3017-11ea-856c-a413eb1ac180.png">
  (I see this issue on other sites too)

**Steps to reproduce:**

- checkout development and view the web UI on a mobile phone

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`-`

**Troubleshooting undertaken, and/or other relevant information:**

- `<table id="domainsTable" ...>` should have a parent `<div class="table-responsive">` to allow horizonal scrolling (like it is done in `queries.php` and `db_queries.php`).

- to fix pagination, the optimizations rules in `pi-hole.css` should be changed to work for all `dataTables`.

- Class `form-group` should be added to `<div>`s `col-md-6` to achieve a vertical gap between a input field and the next label.
  <img width="216" alt="group-domains3" src="https://user-images.githubusercontent.com/28313514/71787714-93320300-301b-11ea-8ba9-7dde1dd00438.png">
Other sites also need a review on a small screen to find out where `form-group` also is needed.

**Comment by Th3M3** [comment]
> - `<table id="domainsTable" ...>` should have a parent `<div class="table-responsive">` to allow horizonal scrolling (like it is done in `queries.php` and `db_queries.php`).

#1137 solves this. Thanks to @DL6ER.

If i have more free time, I would provide a PR for the open rest.

**Comment by Th3M3** [comment]
> - Class `form-group` should be added to `<div>`s `col-md-6` to achieve a vertical gap between a input field and the next label.


#1163 solves this.

**Comment by yubiuser** [comment]
Fixed a long time ago by https://github.com/pi-hole/AdminLTE/pull/1163
