### ISSUE TITLE
Audit log buttons do nothing on 5.0

### ISSUE THREAD

**Issue by Ghalid** [pi-hole/AdminLTE#1139]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Clicking the Blacklist, Whitelist, and Audit buttons in the Audit Log page should perform their respective functions

**Actual behaviour:**

On the beta 5.0, clicking the Audit button does nothing. Clicking the Whitelist ~and Blacklist buttons~ (see comment below) seem to do nothing either except enable the button below to update the white/blacklists (and when updated, the wanted domains don't appear in the respective list).

**Steps to reproduce:**

1. Open the Audit Log.
2. Attempt to press any of the buttons.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

I think this can be replicated on any install, but if this is still needed then please ask 

**Troubleshooting undertaken, and/or other relevant information:**

- Installed beta 5.0 on a clean VM, could still reproduce

**Comment by Ghalid** [comment]
Correction: The Audit and Whitelist buttons still do nothing.

However, it seems that the Blacklist button sort of works, but really poorly. It adds the wanted domain to the blacklist - however upon refreshing the admin panel you'll find that the DNS server has shut down (I went into Settings and clicked "Restart DNS resolver" to bring it back up). In addition, it added three extra unwanted entries to the blacklist:

- `129` (this number is different each time)
- `blacklist`
- `audit`

<img width="1384" alt="Screen Shot 2020-02-17 at 12 20 32 PM" src="https://user-images.githubusercontent.com/24234921/74674685-e7361880-517f-11ea-93eb-4ca7f1ef3e9c.png">

https://tricorder.pi-hole.net/yunb6gske1

**Comment by DL6ER** [comment]
Sorry, I was busy in real life and, let's just be honest, have forgotten about this issue meanwhile. I'll check it out soon, maybe still today, let's see.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/audit-log-lighttpd-errors-after-pressing-button/28401/2

**Comment by DL6ER** [comment]
Okay, solution proposed in https://github.com/pi-hole/AdminLTE/pull/1169

It would be very nice if you could test our fix with
```
pihole checkout web fix/audit_log
```

**Comment by Ghalid** [comment]
It works a little bit better now, thanks. The audit button now works correctly. However, there's still one important issue:

1. Clicking the Blacklist or Whitelist buttons adds the correct domain to the corresponding list, without any extra domains; but when the button is clicked, FTL crashes (refresh the admin panel to see that this has happened after clicking the button). The log file `pihole-FTL.log` while this happens can be found at https://hastebin.com/eluzusurej.sql

Also, a few quirks that are probably unrelated, but I thought I should mention:
1. There's quite a long time before you see any feedback from when you click the "Audit" button to when the domain disappears (I don't think this is a beta specific issue, I've seen this before on v4).
2. A message at the bottom,
> Important: Note that black- and whitelisted domains are not automatically applied on this page to avoid restarting the DNS service too often. Instead, click on this button, to have the new settings become effective:

exists and the button below enables once either the Whitelist or Blacklist buttons are clicked, though it does not seem that this is necessary since the blacklist/whitelist entries show immediately even without updating gravity. Is this correct?

**Comment by DL6ER** [comment]
I do not see the FTL crash, however, I will check again with your log snippet if I can trace it down.

> There's quite a long time before you see any feedback from when you click the "Audit" button to when the domain disappears (I don't think this is a beta specific issue, I've seen this before on v4).

Yes, there is a built-in delay of three seconds in which actions are collected (the timer resets when adding more domains within the timeout). I do not exactly recall why we added this, however, this is not some trivial code so there was definitely some motivation for this.

> show immediately even without updating gravity. Is this correct?

Yes. Gravity does not need to get updated for any list changes (except adlists, of course) in Pi-hole v5.0. It *should* be sufficient to just add the domains without running gravity. I will check this again, tomorrow, thanks for your feedback, already.

**Comment by DL6ER** [comment]
I checked this but are there more lines above the first one in the snippet you extracted?
```
[2020-02-21 15:30:08.903 22407] get_client_groupids(SELECT COUNT(*) FROM client WHERE ip = '192.168.99.2';) - SQL error step (5): database is locked
```

**Comment by DL6ER** [comment]
I just pushed a few performance improvements for the audit log page. @Ghalid please try if you can confirm an increased performance after updating.

**Comment by Ghalid** [comment]
> I just pushed a few performance improvements for the audit log page. @Ghalid please try if you can confirm an increased performance after updating.

Yes, performance is much better!

I was curious and looked up why the delay was added, and found https://github.com/pi-hole/AdminLTE/pull/534, not sure if this is still an issue?

And yes, your FTL fix worked, I no longer see a crash upon clicking the Whitelist and Blacklist buttons. Thank you so much!

**Comment by DL6ER** [comment]
Thanks for digging out this PR. Auditing a domain does not cause any overhead to FTL. Lists manipulations do, however, I don't expect users to heavily white- / blacklist from the audit log page, so this issue should be largely resolved.

Thanks for using the Pi-hole!
