### ISSUE TITLE
Moving Pihole/#561

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#114]
Moving [this issue from the main Pi-Hole repo](https://github.com/pi-hole/pi-hole/issues/561)  to this one.
##

**Comment by iLlama** [comment]
Having this issue again.. I have been the only one on my network browsing today though which is odd. 

I ran pihole -f and then I was able to view the query log. I guess it grew to large again.

**Comment by Mcat12** [comment]
Duplicate of #130
