### ISSUE TITLE
[release/v5.0] Whitelist shows error box with no error description

### ISSUE THREAD

**Issue by mahowi** [pi-hole/AdminLTE#1148]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`When opening the Whitelist I expect to see the actual whitelist.`

**Actual behaviour:**

`I get a red error box with "Failure! Something went wrong, see output below:" and a white box with no text below`
![20200211_180011](https://user-images.githubusercontent.com/16085973/74261633-cb53f200-4cfb-11ea-867c-f316736ffdc0.jpg)

**Steps to reproduce:**

`Switch to branch "release/v5.0" and open the Whitelist page`

**Comment by mahowi** [comment]
The same empty error box is shown when trying to add something to the blacklist.

**Comment by DL6ER** [comment]
Please check your `/var/log/lighttpd/error.log` for any related PHP errors.

1. Does `pihole -r` fix this?
2. (Only if 1 didn't work!) Does installing `php-intl` fixes this?

**Comment by mahowi** [comment]
I get these PHP errors:
`2020-02-11 18:31:21: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function idn_to_ascii() in /var/www/html/admin/scripts/pi-hole/php/add.php:26
2020-02-11 18:31:21: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:
2020-02-11 18:31:21: (mod_fastcgi.c.421) FastCGI-stderr: #0 {main}
2020-02-11 18:31:21: (mod_fastcgi.c.421) FastCGI-stderr:   thrown in /var/www/html/admin/scripts/pi-hole/php/add.php on line 26`

`pihole -r` didn't fix this but installing `php-intl` did.

**Comment by DL6ER** [comment]
Okay, thanks.

@dschaper Any idea why `php-intl` isn't installed for users by `pihole -r`?

Relevant code:
https://github.com/pi-hole/pi-hole/blob/0a70bbd2558e87448cb9a2d511b5f7b2695cc071/automated%20install/basic-install.sh#L290

This is the fourth time I've seen this. We have a few reports on Discourse as well. I assume it works for most but not all?...

**Comment by dschaper** [comment]
Because the code is trying to install `"${phpVer}-intl"` a.k.s `php7-intl` or `php5-intl` when I think the package is `php-intl`?

**Comment by mahowi** [comment]
The package is `php-intl` which depends on `php7.3-intl`

> Packages providing php-intl
php7.3-intl
(https://packages.debian.org/en/buster/php-intl)

Your code installs `php7.3-intl` but `php-intl` is also needed. So it should be possible to install `php-intl` instead of `${phpVer}-intl` as the later one gets installed as a dependency.

**Comment by dschaper** [comment]
Thank you very much for the information.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/database-error-after-update/27966/11

**Comment by DL6ER** [comment]
This is now fixed. Thanks for your report!

**Comment by MichaIng** [comment]
Hey guys, sorry but you made the wrong assumption and by this broke some other cases: https://github.com/pi-hole/pi-hole/commit/75633f09509f3b1bfe223069bde34696be068e65#commitcomment-37740580

**Comment by mahowi** [comment]
> @mahowi
> Which PHP version do you actually use?
> 
> ```
> php <<< "<?php echo PHP_MAJOR_VERSION ?>"
> php <<< "<?php echo PHP_MINOR_VERSION ?>"
> ```

I'm using version 7.3, which is the only installed version.

> 
> I assume you have PHP7+, then this is used to derive the package strings: https://github.com/pi-hole/pi-hole/blob/75633f09509f3b1bfe223069bde34696be068e65/automated%20install/basic-install.sh#L214-L236
> E.g. it prints 7 and 3, then `php7.3-intl` package is installed, which is in case more correct than `php-intl`, which might pull a wrong version, e.g. when Ondrejs PHP repo is used which recently moved the meta packages to PHP7.4 while users might still have PHP7.3 installed for compatibility or because it was installed before the meta package shift.

That's right, `php7.3-intl` gets installed. But I get the error described in my comment above:

`2020-02-11 18:31:21: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Fatal error: Uncaught Error: Call to undefined function idn_to_ascii() in /var/www/html/admin/scripts/pi-hole/php/add.php:26`
`2020-02-11 18:31:21: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:`
`2020-02-11 18:31:21: (mod_fastcgi.c.421) FastCGI-stderr: #0 {main}`
`2020-02-11 18:31:21: (mod_fastcgi.c.421) FastCGI-stderr: thrown in /var/www/html/admin/scripts/pi-hole/php/add.php on line 26`

Installing the meta package `php-intl` fixes the issue.

**Comment by MichaIng** [comment]
@mahowi 
> I'm using version 7.3, which is the only installed version.

> That's right, php7.3-intl gets installed. But I get the error described in my comment above

Then the webserver does not use PHP7.3 and there is another PHP version installed. Did you check which version `php-intl` pulls? Obviously not `php7.3-intl`.

Please paste outputs of:
```
dpkg -l | grep php
cat /etc/lighttpd/conf-available/15-fastcgi-php.conf
update-alternatives --list php
apt show php-intl
```

**Comment by mahowi** [comment]
> @mahowi
> 
> > I'm using version 7.3, which is the only installed version.
> 
> > That's right, php7.3-intl gets installed. But I get the error described in my comment above
> 
> Then the webserver does not use PHP7.3 and there is another PHP version installed. Did you check which version `php-intl` pulls? Obviously not `php7.3-intl`.
> 
> Please paste outputs of:
> 
> ```
> dpkg -l | grep php

`dietpi@pihole:~$ dpkg -l | grep php`
```
ii  php-apcu                               5.1.17+4.0.11-1             armhf        APC User Cache for PHP
ii  php-common                             2:69                        all          Common files for PHP packages
ii  php7.3-cli                             7.3.14-1~deb10u1            armhf        command-line interpreter for the PHP scripting language
ii  php7.3-common                          7.3.14-1~deb10u1            armhf        documentation, examples and common module for PHP
ii  php7.3-curl                            7.3.14-1~deb10u1            armhf        CURL module for PHP
ii  php7.3-fpm                             7.3.14-1~deb10u1            armhf        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.3-gd                              7.3.14-1~deb10u1            armhf        GD module for PHP
ii  php7.3-json                            7.3.14-1~deb10u1            armhf        JSON module for PHP
ii  php7.3-mbstring                        7.3.14-1~deb10u1            armhf        MBSTRING module for PHP
ii  php7.3-opcache                         7.3.14-1~deb10u1            armhf        Zend OpCache module for PHP
ii  php7.3-readline                        7.3.14-1~deb10u1            armhf        readline module for PHP
ii  php7.3-sqlite3                         7.3.14-1~deb10u1            armhf        SQLite3 module for PHP
ii  php7.3-xml                             7.3.14-1~deb10u1            armhf        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.3-zip                             7.3.14-1~deb10u1            armhf        Zip module for PHP
```

> cat /etc/lighttpd/conf-available/15-fastcgi-php.conf

`dietpi@pihole:~$ cat /etc/lighttpd/conf-available/15-fastcgi-php.conf`
```
# -*- depends: fastcgi -*-
# /usr/share/doc/lighttpd/fastcgi.txt.gz
# https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

## Start an FastCGI server using php-fpm
fastcgi.server += ( ".php" =>
        ((
                "socket" => "/run/php/php7.3-fpm.sock",
                "broken-scriptfilename" => "enable"
        ))
)
```

> update-alternatives --list php

`dietpi@pihole:~$ update-alternatives --list php`
`/usr/bin/php7.3`

> apt show php-intl

`dietpi@pihole:~$ apt show php-intl`
```
Package: php-intl
Version: 2:7.3+69
Priority: optional
Section: php
Source: php-defaults (69)
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 12,3 kB
Depends: php-common, php7.3-intl
Download-Size: 5.996 B
APT-Sources: http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
Description: Internationalisation module for PHP [default]
 This package provides a Internationalisation module for PHP.
 .
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
 .
 This package is a dependency package, which depends on Debian's default
 PHP version (currently 7.3).
```

As you can see, there's only version 7.3 which is also used by Lighttpd.

**Comment by MichaIng** [comment]
@mahowi 
Okay so far so good. Neither `php-intl` is nor `php7.3-fpm` are installed yet . Now when you do `apt install php7.3-fpm` you get the above PHP error on Pi-hole web access?

**Comment by mahowi** [comment]
Since I reported this issue I had to reinstall my Pi. So I installed pihole stable again and switched to release/v5.0 branch. Everything worked fine so I didn't inspect what packages got installed.

When I opened the issue I switched from stable to v5 branch and got the above PHP error.

As I have currently only remote access via ssh to my PiHole, I can do more tests when I get home.

**Comment by MichaIng** [comment]
@mahowi 
Hmm, if you switched to `release/v5.0 branch` but none of the PHP intl packages got installed, probably it runs the old install script (that does not include this dependency) on branch change? Would be interesting to know if `pihole -r` > `Repair` installs the package then.

But interesting that you don't face the error now with no intl package installed 🤔.

**Comment by mahowi** [comment]
I'm using DietPi with Lighttpd and PHP installed before installing pihole.

As I see now I didn't use whitelist since reinstalling. Because now I get   ```
Error, something went wrong!
While executing: attempt to write a readonly database
``` when trying to add something to whitelist although `/etc/pihole` is owned by user pihole.
I'm running `pihole -r` now.

**Comment by MichaIng** [comment]
@mahowi 
Okay, I just added some required fixes/changes to have DietPi install run fine with Pi-hole v5:
```
usermod -aG pihole www-data # fixes readonly database
apt install php7.3-intl # As this is a new v5 dependency module
```

**Comment by mahowi** [comment]
After adding user `pihole` to group `www-data` the readonly error is gone.

But there is still a mystery... :wink:  Pihole is running **without** `php7.3-intl` or `php-intl` installed. :thinking: I still can edit whitelist or blacklist.

**Comment by MichaIng** [comment]
@mahowi 
I am not sure in which case PHP intl is required, obviously not always. @DL6ER @dschaper probably you know this better. However since now the reason for missing PHP intl package is clear and has nothing to do with the meta package being pulled or not, you might want to accept my PR for reverting back to phpVer estimated package: https://github.com/pi-hole/pi-hole/pull/3204

**Comment by mahowi** [comment]
@MichaIng Thanks. I have installed `php7.3-intl` for now.

**Comment by dschaper** [comment]
Try with some IDNs. That's why the IDN package is required.

**Comment by DL6ER** [comment]
> I am not sure in which case PHP intl is required, obviously not always.

Obviously may be a bit much here. I concur with @dschaper: It is needed whenever editing lists (white, black, regex). So one can safely assume it is always needed even if some pages of the web interface do work even without this module.

**Comment by MichaIng** [comment]
@DL6ER 
Yes, sorry I meant that opening the whitelist/blacklist in web UI does not always show the error without the module. Probably depends on actual content. However clearly the module is required to assure the error never shows up.
