### ISSUE TITLE
Feature Request: Show cache hits on queries graph

### ISSUE THREAD

**Issue by yngndrw** [pi-hole/AdminLTE#1158]
Feature request to show the number of cache-hit queries in the "Queries over the selected time period" graph. (Long term data > Graphics)

Currently this graph just shows the [total number of queries (Status is not "Unknown")](https://github.com/pi-hole/AdminLTE/blob/master/api_db.php#L386) and the [number of blocked queries. (Status is "Gravity", "Wildcard" or "Blacklist")](https://github.com/pi-hole/AdminLTE/blob/master/api_db.php#L420)

I don't have a development environment setup for Pi-hole not am I familiar with the codebase / datastore, but it would appear that a [new database query could be added to `api_db.php`](https://github.com/pi-hole/AdminLTE/blob/master/api_db.php#L355-L430) for queries with the [status of 3 ("Cache")](https://github.com/pi-hole/FTL/blob/master/FTL.h#L95) and a [new dataset defined](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/js/db_graph.js#L157-L183) for this additional query on the graph [along with the data pre-processing](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/js/db_graph.js#L125-L139).

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by DL6ER** [comment]
Just shortly revisiting this

> I don't have a development environment setup for Pi-hole

You already have the developing environment for Pi-hole as it is installed automatically. All the files reside in `/var/www/html/admin`. You can just edit stuff where you deem it appropriate (you already referenced code parts) and test it in your live environment. No extra things need to be considered.

Once you are satisfied, you can branch out and commit. This can then be pushed up to Github and a pull request can be opened. We can assist you once you are ready if you like.
