### ISSUE TITLE
Capital letters cause blacklist and whitelist pages to fall over.

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#116]
##### Expected Behaviour:

Sanity check on domain entry for whitelist/blacklist to discount casing.
##### Actual Behaviour:

adding to either list fails when domain contains a capital letter
##### Steps to reproduce this issue:

add a domain with a capital letter.

see [here](https://youtu.be/zjP9isDbUKM)

This may actually be a bug in the script itself...
##

**Comment by brantje** [comment]
what about `str.toLowerCase()`

**Comment by PromoFaux** [comment]
That would probably work on the web frontend, though I think we also will need to update the regex in the scripts themselves.

**Comment by DL6ER** [comment]
The domain part is not case sensitive as you know. `GitHuB.CoM` works just fine. You can add uppercase as you like, but normally there's not a reason to do so.

@PromoFaux I put together PR [#941](https://github.com/pi-hole/pi-hole/pull/941) which should solve the issue both on the web interface as on the terminal.

**Comment by DL6ER** [comment]
Update has been released.
