### ISSUE TITLE
WebInterface update from 4.3.2 to 4.3.3 does not succeed on RaspberryPi

### ISSUE THREAD

**Issue by zorich51** [pi-hole/AdminLTE#1175]
After updating pihole it shows "Web Interface Version 4.3.2 (Update available)"when opening the web interface.

Checking on the console pihole -v shows
Pi-hole version is v4.4 (Latest: v4.4)
AdminLTE version is v4.3.2 (Latest: v4.3.3)
FTL version is v4.3.1 (Latest: v4.3.1)

I tried to update several times since then. The result is always the same:
xxx:~ $ pihole -up
[i] Checking for updates...
[i] Pi-hole Core:	up to date
fatal: The remote end hung up unexpectedly
[i] Web Interface:	up to date
[i] FTL:	up to date

Do you have any idea what's causing this?

I am running pihole on
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
with kernel version
4.19.66-v7+

**Comment by PromoFaux** [comment]
Could you please provide a debug token? `pihole -d`

Thanks

**Comment by zorich51** [comment]
Here's the token: https://tricorder.pi-hole.net/1yvfcydigi

**Comment by PromoFaux** [comment]
OK, that all looks ok, lets take a slightly deeper dive...

What are the outputs of the following commands  (please run them in `/var/www/html/admin`)

`git branch -a`

`git remote -v`

`git status`

**Comment by zorich51** [comment]
Here we are:

pi@raspberrypi:/var/www/html/admin $ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
pi@raspberrypi:/var/www/html/admin $ git remote -v
origin	https://github.com/pi-hole/AdminLTE.git (fetch)
origin	https://github.com/pi-hole/AdminLTE.git (push)
pi@raspberrypi:/var/www/html/admin $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

**Comment by PromoFaux** [comment]
Strange, this also indicates no issue with the local repository.

Thinking about it, we actually had a similar issue [reported on Discourse yesterday](https://discourse.pi-hole.net/t/pihole-up-not-updating-pihole/29055/18)

Does manually updating that directory work? (`sudo git pull`)

If not, the solution with the other user was to go nuclear on the local repository and re-clone it:

```
sudo rm -rf /var/www/html/admin
sudo git clone https://github.com/pi-hole/adminlte /var/www/html/admin
```

Then a `pihole -up` to confirm it's all up to date.

**Comment by zorich51** [comment]
Here's what happened with the first course of action:
pi@raspberrypi:/var/www/html/admin $ sudo git pull
fatal: The remote end hung up unexpectedly

**Comment by zorich51** [comment]
Can the issue with hanging up impact the "nuclear" solution? I mean, I remove the complete directory and the I try to git clone it again. What if the cloning isn't possible because the remote end hangs up on me? Then I am stuck in the middle - am I not?

**Comment by PromoFaux** [comment]
Yeah, that's a fair point. Maybe go half nuclear and make a backup of the admin directory first, that can easily be restored.

It is probably worth troubleshooting the fatal error message first though. From a quick search around it seems it happens when an internet connection is poor:

https://github.com/jim-schwoebel/voicebook/issues/19

There may also be some good advice in this SO thread:

https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning

**Comment by zorich51** [comment]
I tried to save a backup of the admin directory beforehand, but that wasn't 100% successful:
pi@raspberrypi:/var/www/html $ cp -r admin/ /tmp/pihole/
cp: error reading 'admin/.git/objects/pack/pack-d0654eb22a6d075f200c7e849169f7a572d65dd2.pack': Input/output error

Do you know if not having this one file is going to be an issue if I try to restore by copying back?

**Comment by zorich51** [comment]
The pack-file is there. Just don't know if it is corrupted or not. I guess I will just try-out the nuclear solution now and see what happens.

**Comment by PromoFaux** [comment]
I wonder if that was what was causing this issue... may be it's locked/corrupted.

**Comment by zorich51** [comment]
Result look good:
pi@raspberrypi:/tmp/pihole $ sudo rm -rf /var/www/html/admin/
pi@raspberrypi:/tmp/pihole $ sudo git clone https://github.com/pi-hole/adminlte /var/www/html/admin
Cloning into '/var/www/html/admin'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 21587 (delta 0), reused 0 (delta 0), pack-reused 21586
Receiving objects: 100% (21587/21587), 27.78 MiB | 4.39 MiB/s, done.
Resolving deltas: 100% (11324/11324), done.
pi@raspberrypi:/tmp/pihole $ 
pi@raspberrypi:/tmp/pihole $ pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		up to date

  [✓] Everything is up to date!
pi@raspberrypi:/tmp/pihole $ pihole -v
  Pi-hole version is v4.4 (Latest: v4.4)
  AdminLTE version is v4.3.3 (Latest: v4.3.3)
  FTL version is v4.3.1 (Latest: v4.3.1)
pi@raspberrypi:/tmp/pihole $

**Comment by zorich51** [comment]
I just emptied the Safari cache and re-opened pi-hole admin again. It still shows "Web Interface Version: 4.3.2 (Update available)". Hence I ran "pihole updatechecker local" and now it is all OK!

Many thx for your help with this!!!

**Comment by PromoFaux** [comment]
Great stuff, glad you got it resolved :)

Cheers
