### ISSUE TITLE
Blacklist Page crashes, does not fully load when too many domains are in it.

### ISSUE THREAD

**Issue by coffeemesh** [pi-hole/AdminLTE#1182]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
`2`

**Expected behaviour:**

`If there are too many domains, add pagination for Whitelist and Blacklist to ease the loading of the page.`

**Actual behaviour:**

`When trying to load the Blacklist, the browser tab either crashes or takes too long to load. >4 minutes`

**Steps to reproduce:**
1. Get a big Blocklist full of domains, above 140k
2. Open shell on pihole and add them to the blacklist.txt and save
3. restart pihole
4. run `pihole -g -f`
5. Log in to the admin panel and try to load the Blacklist

**Steps of what you have done to fix this**
Disabled all Browser extensions
Closed all other programs in the background,
Restarted the Pi

**Comment by yubiuser** [comment]
Since v5.0 Pi-hole is not using ` blacklist.txt` anymore.

**Comment by coffeemesh** [comment]
> Since v5.0 Pi-hole is not using ` blacklist.txt` anymore.

That is amazing news, thank you for the update! Could you please link me the changeset, or the changed file? I wasn't able to locate it through the search or from the release history.

**Comment by rdwebdesign** [comment]
Here are the code where the lists were removed (_v4.4 to v5.0_):

- https://github.com/pi-hole/pi-hole/compare/v4.4...v5.0#diff-8c2170639fb8be29ee88f8b66b595e33a6c9f11b1080e6f324e66a18b98e31abL14-L15

- https://github.com/pi-hole/pi-hole/compare/v4.4...v5.0#diff-8e13fa9927aabae5439f4ae9d8736f56ab9220296dd931a69cab1e97830a63e3L92-L101

- https://github.com/pi-hole/pi-hole/compare/v4.4...v5.0#diff-db4b5ad6aaf1cab8b965c3b95b3cbac4f1d241e7c85af2fb5c5f51389f17f652L110-L112
