### ISSUE TITLE
[Suggestion + Fix] Add an option to remove the administrator email (by leaving the input box blank) in the web interface.

### ISSUE THREAD

**Issue by AMDBartek** [pi-hole/AdminLTE#1188]
There should be an option for people to remove the administrator email from the web interface (by leaving the input box blank).

This is also a sort of bug as if you make the email box blank it just rewrites the email that was previously entered into the textbox.

More info: https://discourse.pi-hole.net/t/how-can-i-remove-the-administrator-email-from-the-pi-hole-web-interface/29509

![image](https://user-images.githubusercontent.com/46637209/76851641-831b7880-6841-11ea-8897-8dd19dcbf88e.png)

This is due to this code (Credit to TheME for mentioning this on Pi-hole Userspace): https://github.com/pi-hole/AdminLTE/blob/release/v5.0/scripts/pi-hole/php/savesettings.php#L555-L567

It would be better if the web interface (AdminLTE) would allow saving a blank administrator email address, here is the code that would allow the web interface to do so (Credit TheME on Pi-hole Userspace):

```
$adminemail = trim($_POST["adminemail"]);
if(strlen($adminemail) == 0 || !isset($adminemail))
{
	$adminemail = '';
}
if(strlen($adminemail) > 0 && !validEmail($adminemail))
{
$error .= "Administrator email address (".htmlspecialchars($adminemail).") is invalid!<br>";
}
else
{
exec('sudo pihole -a -e \''.$adminemail.'\'');
}
```

P.S. I think that Pi-hole is a great project, I might donate some Bitcoin later!

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/how-can-i-remove-the-administrator-email-address-from-the-pi-hole-web-interface/29509/7

**Comment by AMDBartek** [comment]
Yes, I know the issue was mentioned on the Pi-hole Userspace, I just made a GitHub issue because it's a convenient place to put suggestions (many people do this).

**Comment by dschaper** [comment]
That's a bot.

**Comment by AMDBartek** [comment]
I have updated my issue with the code (credit to TheME on Pi-hole Userspace) required to fix this problem, so if someone could implement this it would be great!

**Comment by AMDBartek** [comment]
I am closing this issue as this was fixed a long time ago.
