### ISSUE TITLE
[Suggestion] Add a way to un-audit domain entries in the Pi-hole web GUI (AdminLTE)

### ISSUE THREAD

**Issue by AMDBartek** [pi-hole/AdminLTE#1191]
There is a section under tools called “Audit Logs” and if you audit a domain and you want to un-audit the domain you have to remove the domain manually from an entry in a text/database file (the type of file depends on the version of Pi-hole) and this may be hard to do for some users, so it would be convenient to have a section under the audit logs that lists all of the domains and beside each listing, it should be a delete icon that will delete the domain from the list of audited domains.

Adding a simple way to un-audit domains would help people who are not as experienced with Pi-hole/Linux.

Some additional info: https://discourse.pi-hole.net/t/how-to-clear-the-audit-log/29522/, https://discourse.pi-hole.net/t/add-a-way-to-un-audit-domain-entries-in-the-pi-hole-web-gui-adminlte/29527

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/add-a-way-to-un-audit-domain-entries-in-the-pi-hole-web-gui-adminlte/29527/1

**Comment by yubiuser** [comment]
Link to the feature request on discourse: https://discourse.pi-hole.net/t/add-a-way-to-un-audit-domain-entries-in-the-pi-hole-web-gui-adminlte/29527
