### ISSUE TITLE
Bugs in 4.3.3 web interface

### ISSUE THREAD

**Issue by jacklul** [pi-hole/AdminLTE#1193]
"Danger Zone" buttons does not work probably because of this warning:
![](https://i.imgur.com/CSjOIQH.png)

DNS cache stats on settings page display no data:
![](https://i.imgur.com/7NFvOqd.png)

I've tested this on two computers and Chrome, Firefox, Opera and Falkon browsers, all with fresh profiles and cache cleaned as well as in private mode.

Scripts:
`scripts/pi-hole/js/settings.js`
`scripts/vendor/jquery.confirm.min.js`
(even when access through IP) return empty, all other scripts seem fine.

What can be the cause?

**Comment by dschaper** [comment]
Run `pihole -d` and get us a token.

**Comment by jacklul** [comment]
> Run `pihole -d` and get us a token.

I've restated Pi-hole recently but it didn't fix the issue.
https://tricorder.pi-hole.net/6drxkajrml

**Comment by jacklul** [comment]
Okay, I found the issue:
`/var/cache/lighttpd/compress/admin/scripts/pi-hole/js/settings.js-gzip-XXXXX`
`/var/cache/lighttpd/compress/admin/scripts/vendor/jquery.confirm.min.js-gzip-XXXXX`

Were completely empty, something had to bug out when those were generated, after removing them they are now filled with correct data.
