### ISSUE TITLE
[Suggestion] Keyboard navigation between grid view pages

### ISSUE THREAD

**Issue by elylv** [pi-hole/AdminLTE#1195]
It would be nice if we could use keyboard navigation in http://pi.hole/admin/queries.php?all (and any other multi-page grid views) to move between pages.  e.g. pressing left-arrow would do the equivalent of clicking "Next", and pressing right-arrow would do the equivalent of clicking "current page minus 1".

Currently, clicking "Next" to navigate through the pages can be a pain, as depending on the contents of the table, the "Next" button moves location as the page lays out, so you can't easily click "Next... Next... Next..." with the mouse, as the "Next" button has moved position.
I also find it a pain to repeatedly click the mouse/touchpad in situations like this, even if the "Next" button did not move, and find keyboard navigation much friendlier.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.
