### ISSUE TITLE
Query Log Client Sort Issue

### ISSUE THREAD

**Issue by yhdesai** [pi-hole/AdminLTE#1196]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

`On the Query log page, When you click on an ip address under client, It should only show queries from that client.

**Actual behaviour:**

`It also shows queries from clients that have the part of their ip in their ip address. For example, If you select the ip 10.0.0.1, It will also show queries from 10.0.0.11`

**Steps to reproduce:**

`1. Go to Query Log`
`  2. Click on a client ip in the client column (preferrably your modem ip(which ends usually with .1) and make sure theres another ip which ends with .11.`
  `3. Now you'll see queries by both the modem ip and the other ip`

****

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/explicit-search-in-pi-hole-admin-console/28893/11

**Comment by georgeglessner** [comment]
The source of the "issue" is [here](https://github.com/pi-hole/AdminLTE/blob/38d8e77f999ba5999c013b44f6e8fe808308de7a/scripts/pi-hole/js/queries.js#L381). In order to fix it, regex would need to be implemented on the search term. 

Would need to look something like the following:

```
 api.$("td:eq(3)").click( function () { if(autofilter()){ api.search( '^\\s' + this.innerHTML+'\\s*$', true, flase ).draw(); $("#resetButton").show(); }});
````

According to the example posted [here](https://datatables.net/reference/api/search())

**Comment by DL6ER** [comment]
Just a quick update: We are currently working on a fix for this. You can already try it, see:
https://discourse.pi-hole.net/t/explicit-search-in-pi-hole-admin-console/28893/16

**Comment by yubiuser** [comment]
Has been fixed:
https://pi-hole.net/2020/07/15/pi-hole-5-1-released/#page-content
