### ISSUE TITLE
"Disable" in dashboard without function

### ISSUE THREAD

**Issue by Bondarz** [pi-hole/AdminLTE#1198]
Hello,

my PiHole cannot be deactivated by clicking disable. neither completely, nor for a few minutes. It then looks as if the loading wheel is no longer turning.

Over Putty "pihole disable 1m" it works.
When I then press Enable, I get the following screenshot:
https://i.imgur.com/yfYeq8k.png

After that it takes a moment until the PiHole activates itself again.
**Strange**: After activating querry logging (Firefox), I can enable Disbale/Enable in the dashboard as usual. With Brave the problem still exists. No Disbale/Enable possible. 

Raspberry Pi1 B Rev 2
Pi-hole Version v4.4 Web Interface Version v4.3.3 FTL Version v4.3.1
Win 10
Fireox 74.0
Brave 1.5.115

**Comment by XhmikosR** [comment]
You should try the latest version and see if the issue persists, but make sure you clear your browser's cache.
