### ISSUE TITLE
custom range is not auto-selected after click on "custom range" in date/time selector in long-term data

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/AdminLTE#1212]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Selecting "Custom Range" should automatically select ‘custom range’ on the left side of the opening extended selector.

**Actual behaviour:**

One has to make at least one click in the date field or change the time before "custom range" on the left side is selected.

**Steps to reproduce:**

Click on the date/time selector in any page under long term data. The extended selector will open. The selection on the left side is still on "last 7 days" instead of "custom range". 

Usually users will select an date/time but I saw that the box automatically selects the time one clicks on the box (say 20:03) but in custom range it rounds to full hour (8:00 pm). I wanted to get this full hour (8:00 pm) but therefor I had to select first a **different** time and than switch back to what I really wanted.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/add-more-statistics-on-per-client-basis/27640/8

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/add-more-statistics-on-per-client-basis/27640/8

**Comment by yubiuser** [comment]
Needs to be fixed upstream.

https://github.com/dangrossman/daterangepicker/issues/1756
https://github.com/dangrossman/daterangepicker/pull/1757
