### ISSUE TITLE
PiHole Network/Audit Icon not displaying / shows Square

### ISSUE THREAD

**Issue by p1r473** [pi-hole/AdminLTE#1215]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The Network and audit log icon should display

**Actual behaviour:**

Icon for Network/Audit log does not display

![image](https://user-images.githubusercontent.com/9235633/79259582-f3c2ae80-7e5a-11ea-8264-a4e210e5181e.png)

**Steps to reproduce:**

I am not sure how to make this happen but it is always like this for me

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/etdyv2bbjm

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

I have no idea how to fix this

**Comment by dschaper** [comment]
All of the icons are FontAwesome Icons. Try Dev Mode in your browser and look for any errors or issues loading assets. (F12)

Also, your log didn't upload anything. Is there a `/var/log/pihole_debug.log` file and does it contain anything?

**Comment by p1r473** [comment]
I tried pihole -d again and its making 0 byte files in /var/log/pihole_debug.log, but Ive pasted the output here: https://pastebin.com/uhbSyP5G

**Comment by p1r473** [comment]
I'm not too sure what I am looking for here
![image](https://user-images.githubusercontent.com/9235633/79292842-217e1680-7ea0-11ea-8cbe-de35e069a9b3.png)

**Comment by p1r473** [comment]
The 0kb file is probably from me running log2ram on the Pi

**Comment by p1r473** [comment]
I deleted all the pihole files from /var/log and now I have a 43kb file. Possibly a permissions error somehow on the last log??
Try this:
https://tricorder.pi-hole.net/raza8rlxpv

**Comment by p1r473** [comment]
I found some fontawesome domains in my blocklists
After whitelisting them, the issue remains

pro.fontawesome.com
use.fontawesome.com
kit-free.fontawesome.com
kit.fontawesome.com
fontawesome-cdn.fonticons.netdna-cdn.com

**Comment by p1r473** [comment]
Issue seems to be localized to Chrome- Firefox displayed the icons fine

**Comment by p1r473** [comment]
There are no errors in the Chrome F12 console

**Comment by p1r473** [comment]
Problem is fixed after disabling this Chrome extension (no idea why)
https://chrome.google.com/webstore/detail/rakuten-express-cash-back/idpbkophnbfijcnlffdmmppgnncgappc
