### ISSUE TITLE
Debug Log upload should be opt-in and not opt-out

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/AdminLTE#1216]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

The checkbox "Upload debug log and provide token once finished" in Tools -> Generate debug log should not be checked by default

**Actual behaviour:**

The checkbox is checked by default.

**Steps to reproduce:**

Go to Tools -> Generate debug log

**Troubleshooting undertaken, and/or other relevant information:**

I noticed this [feature request](https://discourse.pi-hole.net/t/opt-in-on-debug-log/30648) but think this is more an issue than a feature request. The user also reported a possible fix for this:

`<input type="checkbox" id="upload" checked>`
to
`<input type="checkbox" id="upload">`

I think it would be even better if a overlay popup would appear after the debug log is generated, showing the token (for ease of copy& pasting) and asking if the user wants to upload the log.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/opt-in-on-debug-log/30648/2

**Comment by PromoFaux** [comment]
I think the simplest solution in the meantime (and simplest is usually best 😉) is to make the change as suggested.

There would need to be a bit more change in the backend to support your overlay idea (not saying it isn't a good idea!)

Feel free to code up the suggested fix and submit a PR, and if you can come up with something more akin to your popup idea, then by all means work away :)

**Comment by erdnuesse** [comment]
Hi, I opened the feature request / didn't know it was an issue. 
a) can provide more info if needed
b) could also provide fix if web frontend is actually in github
(not my everyday business, but hey, I'll do what I can, if you need resources.)

**Comment by dschaper** [comment]
> showing the token (for ease of copy& pasting) and asking if the user wants to upload the log.

The token is generated server side. If you have one then the log is already uploaded.

**Comment by PromoFaux** [comment]
I think it makes total sense that we make it opt-in instead of opt-out. 

@erdnuesse, I've made a patch for your suggested fix.

**Comment by yubiuser** [comment]
Ok, then it must be a two-step process: first ask for permission and after generating show the token.

**Comment by erdnuesse** [comment]
Thanks, you're all awesome.

**Comment by jfb-pihole** [comment]
I agree with the change to a default opt-out, vs opt-in.  The token pop-up is not needed in my opinion (it isn't provide on the CLI version).  We should change the wording on the checkbox from

"Upload debug log and provide token once finished"

to

"Upload debug log.  See end of log for the token"

**Comment by PromoFaux** [comment]
And it is now merged, will be in the next release

**Comment by aproposnix** [comment]
> I agree with the change to a default opt-out, vs opt-in. The token pop-up is not needed in my opinion (it isn't provided on the CLI version). We should change the wording on the checkbox from
> 
> "Upload debug log and provide token once finished"
> 
> to
> 
> "Upload debug log. See end of log for the token"

The CLI version clearly shows the token at the end of the output. There is no issue there.  

That's not the case for the web interface. In my opinion, and experience, adding the token to the top of the page of the Admin page is far more visible and will reduce the amount of searching and scrolling.

**Comment by erdnuesse** [comment]
> I agree with the change to a default opt-out, vs opt-in. The token pop-up is not needed in my opinion (it isn't provided on the CLI version). We should change the wording on the checkbox from
> 
> "Upload debug log and provide token once finished"
> 
> to
> 
> "Upload debug log. See end of log for the token"

If that's a request for change or suggestion, I would encourage you to open a separate suggestion to follow community standards since this one is closed already to keeping everything organized and trackable.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/enhancement-visibility-of-debug-token-in-web-gui/32051/1

**Comment by dschaper** [comment]
> That's not the case for the web interface. In my opinion, and experience, adding the token to the top of the page of the Admin page is far more visible and will reduce the amount of searching and scrolling.

See my response on Discourse. The amount of work to do it is so entirely not worth it.
