### ISSUE TITLE
Line breaks on dashboard gauge's legend

### ISSUE THREAD

**Issue by R-E-T** [pi-hole/AdminLTE#1220]
On the dashboard, "queries answered by" does not handle long DNS server names too well (text truncated & horizontal scrollbar).

![queries_answered_by](https://user-images.githubusercontent.com/45913113/72064650-9ad3ff00-32dc-11ea-8c0f-807a7a760e8b.png)

I'd suggest to implement line breaks by keeping the DNS domain name and its TLD in a separate row and one or many rows above for any subdomains.

**Comment by DL6ER** [comment]
@R-E-T What would you suggest as alternative?

**Comment by R-E-T** [comment]
I'd suggest to distribute the server name to two lines. Maybe by separating the sub domains from the domain and the tld?

**Comment by Th3M3** [comment]
We could inject `<wbr>` word break opportunities before `.` and `-` characters, e.g. by using
this snippet to update the legend:
```js
var LegendHtml = forwardDestinationPieChart.generateLegend();
var LegendEl = $(LegendHtml);

LegendEl
  .find("li")
  .contents()
  .filter(function () {
    if (this.nodeType == 3) {
      $(this).replaceWith(
        $(this)
          .text()
          .replace(/([\.-])/g, "<wbr>$1")
      );
    }
  });

$("#forward-destinations-legend").html(LegendEl.prop("outerHTML"));
```

and optionally extend css rule to indend text on the second line
<pre>
.chart-legend li {
    cursor: pointer;
<b>    text-indent: -25px;</b>
<b>    margin-left: 25px</b>
}
</pre>

If desired, the `replace` RegEx rule can still be optimized. I'm no expert at it.

<img width="373" alt="wbr" src="https://user-images.githubusercontent.com/28313514/80415199-7a06d800-88d2-11ea-889a-49ff9c1e6b93.png">

But for clarify, this only helps if the server name contains these "break" characters.

**Comment by DL6ER** [comment]
Alternative suggestion:
![Screenshot at 2020-04-27 23-22-17](https://user-images.githubusercontent.com/16748619/80422367-50ec4480-88de-11ea-89a8-55d72f1aa9c2.png)
```js
$("#forward-destinations-legend").css({"word-break": "break-all"})
```
![Screenshot at 2020-04-27 23-24-24](https://user-images.githubusercontent.com/16748619/80422373-55b0f880-88de-11ea-8d3c-b8cefd3fee2b.png)

**Comment by Th3M3** [comment]
Yes, of course we can also do it this way.

Then I would prefer to directly add `word-break: break-all;` to existing `.chart-legend li {}` rule in `pi-hole.css` instead of setting the property via js.

**Comment by DL6ER** [comment]
> instead of setting the property via js.

Sure, this was merely for local reproducibility at the OP's system avoiding to modify code.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
