### ISSUE TITLE
Error when adding first static dhcp entry.

### ISSUE THREAD

**Issue by mwoolweaver** [pi-hole/AdminLTE#1221]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

No error

**Actual behaviour:**

```
There was a problem applying your settings.
Debugging information:
PHP error (2): fopen(/etc/dnsmasq.d/04-pihole-static-dhcp.conf): failed to open stream: No such file or directory in /var/www/html/admin/scripts/pi-hole/php/savesettings.php:84
```
![Screen Shot 2020-04-20 at 1 33 01 PM](https://user-images.githubusercontent.com/5729320/79786718-848e0400-830b-11ea-9638-2d2ec2fdb840.png)

**Steps to reproduce:**

1. Have new install of Pi-hole
2. Enable dhcp
3. Add entry dhcp reservations.
4. This red banner pops up. But doesn't have any adverse effect. Entry does get added and subsequent entries.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

szurygpta7

**Troubleshooting undertaken, and/or other relevant information:**

it appears to just be an error because the file wasn't there before the command to add to it was executed.

**Comment by DL6ER** [comment]
Thanks for your report. This bug is already known and will be fixed by https://github.com/pi-hole/AdminLTE/pull/1206 (still awaiting review + merge).

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/various-issues-after-re-install/31238/29

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
