### ISSUE TITLE
PHP Warning:  unlink(../custom_disable_timer)

### ISSUE THREAD

**Issue by leonardofialho** [pi-hole/AdminLTE#1227]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behaviour:**

When disabling pihole using the web interface a timing file is generated (custom_disable_timer) in the www-root directory. This file will be removed later when the service is reenabled.

**Actual behaviour:**

When PHP display_errors configuration variable is set to ON a warning can be raised when the file does not exists, which is the case of permanently service disabling.

This warning blocks the web interface spinning animation associated to the action (disabling the service).

**Steps to reproduce:**

Enable PHP display_errors configuration environment and play with disabling/enabling the service using the web interface.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/uuy4bp614g (uuy4bp614g)

**Troubleshooting undertaken, and/or other relevant information:**

Disabling the PHP display_errors setting solves the issue.

**Comment by georgeglessner** [comment]
https://github.com/pi-hole/AdminLTE/blob/5ec769d9d8ed70d43e1d774722d6e9a7f5002f14/api.php#L47

```php
if(file_exists("../custom_disable_timer")){
    unlink("../custom_disable_timer");
}
```
