### ISSUE TITLE
invisible popup in some places of the charts

### ISSUE THREAD

**Issue by michal037** [pi-hole/AdminLTE#1232]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I want to see the entire popup on the screen.

**Actual behaviour:**

Popup is partially invisible. It goes aside. I made recordings for the presentation:

https://youtu.be/U4vfTmG8NFw
https://youtu.be/J-sGEW8Wo3E

**Steps to reproduce:**

Use 360x640 resolution on Android Chrome 81.0.4044.117.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

i42f3uc2bi

**Troubleshooting undertaken, and/or other relevant information:**

None

**Comment by yubiuser** [comment]
Thanks for reporting the issue.
I see you're using pihole v4. There will be an (officiall) upgrade to v5.0 soon which[ includes an improved handling of customtooltip](https://github.com/pi-hole/AdminLTE/pull/1147)s. Please report back if the issue still exists in the new version.
Thanks.

**Comment by michal037** [comment]
@yubiuser hmm, then I'll close this issue now. I will wait for the v5.0 release and then will open it again if this problem occurs.
