### ISSUE TITLE
Network Overview : Same MAC with multiple IP appears multiple times

### ISSUE THREAD

**Issue by Tchekda** [pi-hole/AdminLTE#1235]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behaviour:**

Each entry in the Network Overview Page should be identified by it's MAC address and not by it's IP. Because, if the DHCP isn't manage by Pi-Hole, the IP is changing and Pi-Hole should track stats by MAC.

**Actual behaviour:**

Each devices is appearing multiple time in the list because it has change IP multiple times since Pi-Hole is running.

**Steps to reproduce:**

1. Install and run a clean version of Pi-Hole
2. Make some requests through it with a device
3. Change Device IP 
4. Make some requests again
5. Check "Network Overview" page and see this device multiple time : Old IP and New IP

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

jp311gx14n

**Troubleshooting undertaken, and/or other relevant information:**

Didn't find any solution yet but I think the whole stats system should be fixed to make devices identified by their MAC and not by their IP

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by DL6ER** [comment]
We already group and identify devices by their MAC addresses, in fact, this is a unique field and MAC addresses cannot appear multiple times.

Which version of Pi-hole are you using? Can you share a screenshot showing the issue?

**Comment by Tchekda** [comment]
![image](https://user-images.githubusercontent.com/23559888/80964159-aa89cd00-8e10-11ea-95f6-e5727d30553f.png)
Here you are.
```Pi-hole Version v4.4 Web Interface Version v4.3.3 FTL Version v4.3.1```

**Comment by DL6ER** [comment]
The hardware addresses being non-unique was an issue caused by us identifying devices by IP address *and* hardware address in Pi-hole v4.x

This got fixed by https://github.com/pi-hole/FTL/pull/644 and will be automatically resolved for you when upgrading to (soon to be released) version 5.0 of Pi-hole.

**Comment by Tchekda** [comment]
Thank you so much for your reactivity.
