### ISSUE TITLE
Empty Domain is not clickable in the Top Blocked Domains widget

### ISSUE THREAD

**Issue by ErikGulliksen** [pi-hole/AdminLTE#1241]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

In the "Top Blocked Domains" box on the homepage an entry for queries to the empty domain (string "") should somehow be clickable and take me to `/admin/queries.php?domain=`

**Actual behaviour:**

The entry for the empty domain shows up in the list, but as there is no text in the field it's actually not clickable. If I inspect the DOM I see a `<a href="queries.php?domain="></a>` is added, but with no text there it's not clickable.

**Steps to reproduce:**

Reproducible anytime queries to the empty domain shows up in the Top Blocked Domains widget.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

N/A

**Comment by dschaper** [comment]
Debug token please.

**Comment by PromoFaux** [comment]
I'm not entirely sure how an empty domain is even queried or added to the query log.. @DL6ER, any thoughts?

**Comment by dschaper** [comment]
Might not be "empty" but just the `.` root.

**Comment by ErikGulliksen** [comment]
Yes, if I run a `nslookup .` I get an empty domain entry in my query log

**Comment by yubiuser** [comment]
Some work has been put into a feature request improving the link dashboard -> stats. This might be the right place to bring this issue up:
https://discourse.pi-hole.net/t/improve-dashboard-stats-link-to-query-log/30653

**Comment by PromoFaux** [comment]
I've actually got a quick fix for this, which I need to code up and do a PR for, may not make it into v5, but if not it will follow shortly after in v5.1

**Comment by PromoFaux** [comment]
This is fixed in version 5.0
