### ISSUE TITLE
Static DHCP leases configuration table is rendered too short

### ISSUE THREAD

**Issue by SidShetye** [pi-hole/AdminLTE#1243]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

I should be seeing more than 5 entries in the Static DHCP leases configuration section in the "Settings" page. Especially when I do have and expect a larger list. It's a little 

**Actual behaviour:**

![image](https://user-images.githubusercontent.com/2595088/81226205-4fd2ab80-8f9f-11ea-9396-1c26d8fe5822.png)

**Steps to reproduce:**

Add 20 entries to the settings -> Static DHCP leases configuration section

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`aiq8zhplrp`

**Troubleshooting undertaken, and/or other relevant information:**

1. Open the page in Chrome dev tools 
2. select the `Static DHCP leases configuration` element (`<label>Static DHCP leases configuration</label>`) and then go to the wrapper to the table `<table id="DHCPStaticLeasesTable"`. This is the `<div class="dataTables_scrollBody" style="position: relative;overflow: auto;width: 100%;max-height: 200px;">`
3. disable/delete the `max-height: 200px;` snippet and it displays as expected for a lengthy list (say 20 entries)

**Comment by roerigdalgaard** [comment]
it would be great if the lease and reservation table would be with more lines. It's quite an workaround to change the code after every update of the web interface...

**Comment by PromoFaux** [comment]
Pull requests welcome...

**Comment by yubiuser** [comment]
DHCP tables were re-designed with https://github.com/pi-hole/AdminLTE/pull/2042.

The fix was released with https://discourse.pi-hole.net/t/pi-hole-ftl-v5-13-web-v5-10-and-core-v5-8-released/52254/1
