### ISSUE TITLE
LAN DNS Admin Page

### ISSUE THREAD

**Issue by stuartsimpson** [pi-hole/AdminLTE#1245]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
9
---

I have created a new admin page to allow users to manage a LAN Domain Names.  I started with Robin Laurén article **[HOWTO: Using pi-hole as LAN DNS server](https://discourse.pi-hole.net/t/howto-using-pi-hole-as-lan-dns-server/533)** to configure the LAN DNS server and then used the Network Page as a template to create the new page.  The developed work can be found at [piHoleDNSAdmin](https://github.com/stuartsimpson/piHoleDNSAdmin).  Please take a look and if you like it as a group feel free to role it into the pi-hole project if not it was fun creating the page and useful to me.  Have a great day.

**Comment by dschaper** [comment]
Thanks for the links!

I think this may be very similar to what we have in version 5, [Local DNS Records](https://github.com/pi-hole/AdminLTE/blob/release/v5.0/dns_records.php).

![Screenshot_2020-05-07 Pi-hole Admin Console](https://user-images.githubusercontent.com/2782850/81305528-47c44b80-9033-11ea-9c6b-e549ed39374b.png)

**Comment by PromoFaux** [comment]
Hey, thanks for letting us know about your project, looks neat! I always applaud users for coming up with their own solutions - after all, it's how I joined this project years ago... something didn't work quite right, so I rolled up my sleeves and set about finding a solution to it.

Just as an FYI (and not to diminish your hard work already done) but this is a new feature we have already developed for the upcoming 5.0 realease

![image](https://user-images.githubusercontent.com/1998970/81305607-71529680-9076-11ea-9ce5-78b3abbacac3.png)

**Comment by stuartsimpson** [comment]
Well Crap.. lol.. Thanks for the info.  Looking forward to release 5 being out.  Is there a planed release date.

**Comment by yubiuser** [comment]
Your implementation has an alias field - this might be something pihole could pick up?

**Comment by stuartsimpson** [comment]
another thing I added that may be good to add is the button for restarting the DNS server.  I know it can be done on the settings page but it would be nice to have it there after adding an entry.

**Comment by dschaper** [comment]
Clicking the "Add" button restarts all the required processes.

**Comment by jennec** [comment]
Click the Add button doed not restart the DNS server.  Or at very least, if it does, it does not pick up the newly added DSN records.  I always have to Restart the DNS server manually for any new entries to work.

**Comment by stuartsimpson** [comment]
Okay put the new update in place and it looks good there were two issues I had to fix to get it to work with my configuration.  One issue was the list file being hard coded.  The other was that "space" would be the delimiter between IP address and domain name.  Both are simple fixes.  Would you like me to log one ore two issues with my code solutions?
