### ISSUE TITLE
Explain amount input for donation

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [pi-hole/AdminLTE#1246]
- [n] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [y] The issue 
**How familiar are you with the the source code relevant to this issue?:**
0
---
**Expected behaviour:**
select amount to donate, maybe 5, 10, 15, 25, 50 and up.
and an explanation on what will happen in paypal once I get there to fill out a custom amount.
I decided to not donate because I am not sure what exactly "$ 25.00" means.
It looks a lot like 25 dollars, but I'm dutch and to me it looks funny, it also looks a little like twentyfivehundred dollars.
That would not be nice, better stay safe.

**Actual behaviour:**
Straight to paypal.
No explanation.
Not absolutely sure about the amount that I will be donating.
Cancel.

**Steps to reproduce:**
Click donate.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
None

**Troubleshooting undertaken, and/or other relevant information:**
Created issue on github.

**Comment by PromoFaux** [comment]
A `.` is the standard separator for $ amounts, with a `,` being the thousand separator.

I understand in most European countries this is the other way around (usually throws me off when I go on holiday!)

That said, presumably we are talking here about the donate link on the web admin page which goes straight to Paypal.

I wonder if it might be worth us replacing this direct link with a link to:

https://pi-hole.net/donate/

On that page, you will see an option to change between `$`, `€` and `£`, and the correct formatting is applied to each currency.

**Comment by i-n-g-m-a-r** [comment]
Yes, I mean the donate link on the web admin page.
I was not aware of any other donate link.

**Comment by PromoFaux** [comment]
This has been addressed in #1248 and will be reflected in the next release.

I can see how it can be confusing to some. :)
