### ISSUE TITLE
[Cosmetic] Change description of Local DNS Records

### ISSUE THREAD

**Issue by ghost** [pi-hole/AdminLTE#1258]
Local DNS records is supposed to "Custom **host names** from the web GUI through the “Local DNS Records” tab.  This assigns **host names** to IP addresses"

However, the description says: "On this page, you can add **domain**/IP associations", "Add a new **domain**/IP combination", "Add a **domain** (example.com or sub.example.com" and "List of local DNS **domains**"

**Comment by jfb-pihole** [comment]
> Local DNS records is supposed to "Custom host names from the web GUI through the “Local DNS Records” tab. This assigns host names to IP addresses"

These sentences are from the release announcement, and are intended to explain how the new feature works. 

Is there a problem with the wording on the Local DNS Records tab in the Pi-hole web GUI?
