### ISSUE TITLE
Unable to add/delete to or from white/black list thru Admin Console

### ISSUE THREAD

**Issue by zelein** [pi-hole/AdminLTE#126]
##### Steps to reproduce this issue:

I navigate to the white/black list pages and attempt to add a url by hitting the Add button OR enter button. See the album below. 

http://imgur.com/a/6USzo

**Comment by dschaper** [comment]
Try whitelisting just the domain, leave off the `http` portion and see if that allows the listing. We have added code that detects any characters that are not part of a standard domain name and it's probably hitting that colon and backslash and rejecting your requests as a protective measure.

**Comment by zelein** [comment]
That doesn't work either.
Just tried www.google.com and google.com

I can add them through the command line though.

**Comment by zelein** [comment]
I added https://www.google.com through the command line and I also can not delete it through the command line due to the regex. :X

**Comment by dschaper** [comment]
There shouldn't be any URI's in the white/black lists. If you have them, they need to be deleted out and just list the domains plain like a hosts file. There is some code that will take into consideration having `http` or `https` in the lists, but it will cause `dnsmasq` to function in ways that it was not intended to.

**Comment by zelein** [comment]
Okay I've re-installed pi-hole and have removed any trace of http|https and www. from all of my white lists and I am still unable to add anything from the admin console.

**Comment by Mcat12** [comment]
Are you adding it exactly like this? `google.com`
If so, run `cat /var/log/lighttpd/error.log` and post the output.

**Comment by dschaper** [comment]
Can you post the `POST` call and the response from that call? I'd like to see what the contents of the `POST` is exactly to see if there is anything there that may be tripping the sanitize function.

**Comment by zelein** [comment]
2016-08-20 20:15:27: (mod_fastcgi.c.2683) FastCGI-stderr: PHP Fatal error:  Call to undefined function hash_equals() in /var/www/html/admin/php/auth.php on line 49

**Comment by zelein** [comment]
@dschaper If you look at my album in the original post in the second image I have a screenshot of the POST and all of its parameters. There is no Response. According to the error.log (in my post above this one) PHP is erroring out saying hash_equals() is not a function. Could my PHP be out of date?

**Comment by Mcat12** [comment]
Looks like you have an out of date PHP version. We're working on lowering the version requirement (currently 5.6), but for now you will have to either update PHP, only whitelist through the command line, or manually modify a few files (will explain if you want).

**Comment by zelein** [comment]
I've resorted to modifying the txt files for now. I'll work on updating PHP on my pi. I'll report findings here.

**Comment by zelein** [comment]
After some research, it appears the highest available package for Wheezy is 5.4 unless compiled from source. It takes a _really_ long time to do this on a Rpi 2 and ended up failing out the middle of the way through. So it looks like I'm just going to cut losses and upgrade to Jesse since I think it supports higher versions of PHP from the package manager. 

Feel free to call this issue closed.

**Comment by dhsc19** [comment]
@Mcat12 Would you give instruction on what to modify with the PHP files as I am not able to update to the proper PHP version for now.  So, I am interested in this workaround.  Thank you.

**Comment by Mcat12** [comment]
[Here you go.](http://www.reddit.com/r/pihole/comments/54ty50/_/d85j9tv)

**Comment by dhsc19** [comment]
@Mcat12 Thank you!
