### ISSUE TITLE
JSON numerical values should not have thousands separators

### ISSUE THREAD

**Issue by watou** [pi-hole/AdminLTE#127]
##### Expected Behaviour:

In the output of `/admin/api.php?summary`, for example:
```json
{"domains_being_blocked":"99,069","dns_queries_today":"10,436","ads_blocked_today":"227","ads_percentage_today":"2.2"}
```
The numerical values should be more easily machine-readable by expressing them as string values without thousands separator characters, or as JSON number values.

##### Actual Behaviour:
Numerical values are given with thousands separators, which complicates machine readability.

##### Steps to reproduce this issue:
Go to the URI `/admin/api.php?summary` when any numerical value exceeds 999.

**Comment by Mcat12** [comment]
Check out `api.php?summaryRaw` ;)

**Comment by watou** [comment]
Thank you for that; it addresses the issue.  So I suppose this issue should be a note for documentation?

**Comment by Mcat12** [comment]
Sure. All the API commands are listed in the readme as well
