### ISSUE TITLE
Feature request: Authentication for (parts of) web-interface

### ISSUE THREAD

**Issue by jpluimers** [pi-hole/AdminLTE#128]
The web-interface is available to anyone on the (local) network.

This also means that anyone can whitelist/blacklist any domain. This is undesirable in quite a few environments.

Feature request: allow (parts of) the web-interface to require authentication (initially with local usernames/passwords) and allow for role based access (i.e. groups of users have certain rights).
##

**Comment by DL6ER** [comment]
In the current PR #197 we work on authorization for the web interface. If you are not authorized, we will only see a (uncritical) fraction of the data that is available. If you log in, you can access everything. Therefore, I think, we don't need any role based access management.

**Comment by DL6ER** [comment]
Update has been released.
