### ISSUE TITLE
Selected theme is always reverted to "Pi-hole midnight" on page change on branch devel

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/AdminLTE#1282]
**In raising this issue, I confirm the following:**]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Theme selection (https://github.com/pi-hole/AdminLTE/pull/1253) should be saved on page change.

**Actual behaviour:**

Theme is always reverted to "Pi-hole midnight" on page change.

**Steps to reproduce:**

Changes the theme in settings to something else then "Pi-hole midnight" and save. Now click on any other page in pihole's dashboard (e.g. Query log). Theme flips back to  "Pi-hole midnight

**Troubleshooting undertaken, and/or other relevant information:**

Confirmed with Chrome and Firefox, cached cleared multiple times.

```
  Pi-hole version is v5.0-38-gd524f9a (Latest: v5.0)
  AdminLTE version is v5.0-101-g9c6a582c (Latest: v5.0)
  FTL version is vDev-da84864 (Latest: v5.0)
```

**Comment by DL6ER** [comment]
Please try changing your theme using
```
pihole -a theme default-light
pihole -a theme default-dark
pihole -a theme default-dark2
```

Does this work?

**Comment by yubiuser** [comment]
No.

```
nanopi@nanopi:~$ pihole -a theme default-dark
Usage: pihole -a [options]
Example: pihole -a -p password
Set options for the Admin Console

Options:
  -p, password        Set Admin Console password
....
```

**Comment by DL6ER** [comment]
What is the output of
```
cd /etc/.pihole/; git status
```

**Comment by yubiuser** [comment]
```
nanopi@nanopi:~$ cd /etc/.pihole/; git status
On branch development
Your branch is up to date with 'origin/development'.

nothing to commit, working tree clean
```

**Comment by DL6ER** [comment]
Please run `pihole -r`. I suppose you updated by checking out the files in `/etc/.pihole` manually? This doesn't suffice.

**Comment by yubiuser** [comment]
> I suppose you updated by checking out the files in /etc/.pihole manually?

No. Always via pihole checkout.

Will run pihole -r

**Comment by yubiuser** [comment]
`pihole -r repair` solved it.
