### ISSUE TITLE
Cryptic error message when attempting to add a duplicate adlist

### ISSUE THREAD

**Issue by daprice** [pi-hole/AdminLTE#1289]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

A clear message such as “Could not add list because an adlist with that URL is already configured” or similar that accurately describes that the user’s input was invalid because it is a duplicate. I don’t think it makes sense to use the word “error” here, because the interface refusing to add duplicate adlists is intended behavior, not an error.

**Actual behaviour:**

The error message says: 

> Error, something went wrong!
> While executing: UNIQUE constraint failed: adlist.address
> Added 0 out of 1 adlists

The wording of the message is misleading because it appears to describe some kind of internal error, not why the user’s input was invalid.

**Steps to reproduce:**

1. Navigate to the Adlist group management page http://pi.hole/admin/groups-adlists.php
2. In the “Address” field, enter the URL of an adlist that is already in the list (i.e. a duplicate)
3. Select “Add”

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/aky0v6i43q`

**Troubleshooting undertaken, and/or other relevant information:**

Spent a minute rereading the error message and deduced that “While executing: UNIQUE constraint failed” is a cryptic way of saying that I accidentally tried to add a duplicate list

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/AdminLTE/pull/1997
