### ISSUE TITLE
v5 : php script sub.php is missing

### ISSUE THREAD

**Issue by coop-git** [pi-hole/AdminLTE#1297]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
8, I can read/write PHP

---
**Expected behaviour:**

Domains are removed from the whitelist/blacklist when making a POST to admin/api.php?list=black&sub=domain.com
admin/api.php?list=black&add=domain.com works fine

**Actual behaviour:**

Domains are not added to blacklist when making a POST to admin/api.php?list=black&sub=domain.com

**Steps to reproduce:**

do a POST to admin/api.php?list=black&add=domain.com
Check blacklist: domain is added : OK
do a POST to admin/api.php?list=black&sub=domain.com
Check blacklist : domain is still there NOK

**Troubleshooting undertaken, and/or other relevant information:**

Opened api.php to see what it refers to
It refers to add.php and sub.php 
add.php is available but sub.php is missing.

**Comment by Scratchcat1** [comment]
The same applies for making a GET request to admin/api.php?list. The request errors out because get.php is also missing.

**Comment by PromoFaux** [comment]
Looks like the files were removed in this pull request

https://github.com/pi-hole/AdminLTE/pull/1154

@DL6ER , is the idea here that folks consuming the API should use `groups.php` instead?

**Comment by DL6ER** [comment]
Maybe I wasn't aware of the possibility to add and remove domains through the API, at least I'm aware of this feature right now. `groups.php` should be a more than adequate alternative, however, authentication may be an issue.

I cannot submit a patch myself for a few days, neither can I test things, so you won't see a fix for this from me.

**Comment by PromoFaux** [comment]
No rush, enjoy yourself! I may even look at it if I have some time
