### ISSUE TITLE
Number in "Percent Blocked" differs from "blocklist" number

### ISSUE THREAD

**Issue by screendriver** [pi-hole/AdminLTE#1313]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Both numbers should be the same.

**Actual behaviour:**

They are slightly different. I guess because of classic rounding issues with floating point numbers.	

**Steps to reproduce:**

The numbers always differ by .1%

**Troubleshooting undertaken, and/or other relevant information:**

Pi-hole Version v5.0 

<img width="241" alt="Screenshot 2020-05-13 at 14 47 23" src="https://user-images.githubusercontent.com/149248/81814547-372b3e00-9529-11ea-80ac-6440eddf637c.png">

**Comment by yubiuser** [comment]
Something else might be play into this: the orange box in the long term database doesn't consider blocked CNAME when calculating percentage blocked. Might be the same issue here.
https://discourse.pi-hole.net/t/blocked-cname-not-calculated-in-blocked-statistic/33760

**Comment by yubiuser** [comment]
I still do see this on the current dev branches. The numbers differ by `.1`

**Comment by rdwebdesign** [comment]
Fixed by pi-hole/FTL#1284

**Comment by yubiuser** [comment]
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
