### ISSUE TITLE
Adlist group management design problem (width)

### ISSUE THREAD

**Issue by beerisgood** [pi-hole/AdminLTE#1414]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`UI should work, no matter if sidebar is minimised or not`
Screenshot:
![fixed UI](https://user-images.githubusercontent.com/9625159/82028627-306e0980-9696-11ea-8d53-c706e036366a.jpg)

**Actual behaviour:**

`UI break if sidebar isn't minimised`
Screenshot:
![broken UI](https://user-images.githubusercontent.com/9625159/82028643-37951780-9696-11ea-8cfe-bbfdcce54b98.jpg)

**Steps to reproduce:**

`in PiHole Web interface "Group Management" -> "Adlists" -> on right side the UI is broken`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`not needed`

**Troubleshooting undertaken, and/or other relevant information:**

* clear browser (Microsoft Edge) cache -> no solution
* minimise PiHole sidebar -> solution

**Comment by celebrir** [comment]
Welp, apparently it's the same for the Audit log. I'll assume it's a general flaw of the respective container displaying the addresses.

![](https://i.celebrir.com/20-06-18-7GYYV.png)

**Comment by yubiuser** [comment]
This issue was solved by: https://github.com/pi-hole/AdminLTE/pull/1161

(But in turn led to issue https://github.com/pi-hole/AdminLTE/issues/1458)
