### ISSUE TITLE
Queries counter on main page and quiere log aren't equal

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#143]
@TylonHH commented on [Sun Sep 18 2016](https://github.com/pi-hole/pi-hole/issues/700)

On the web interface there are nearly 2k queries (flushed 20 minutes ago).
In the quiere log I see on l at the bottom only a total number of 150.
Shouldn't the numbers be equal? Are your numbers at those places equal?

~~If yes, I would suggest it's because of an different timezones I set, which is not set everywhere?!?!~~
##

**Comment by PromoFaux** [comment]
huh, good catch! Looks like an issue in the PHP somewhere!

![image](https://cloud.githubusercontent.com/assets/1998970/18619609/bb2db062-7df8-11e6-8bce-6e3a312cd571.png)

![image](https://cloud.githubusercontent.com/assets/1998970/18619612/cbec8702-7df8-11e6-9e43-53b431cb322b.png)

**Comment by PromoFaux** [comment]
@tylonHH

I've just checked [another branch of the Admin page](https://github.com/pi-hole/AdminLTE/pull/137) that i've been working on, and It appears that that issue is fixed. We've not merged it yet, though, as it is a _tiny_ bit slower than the current master branch.

If you'd like to check it out and test run the following commands:

````
cd /var/www/html/admin
sudo git fetch
sudo git pull
sudo git checkout FilterQueries
````

and then reload your admin page and check. Let me know your experiences!

**Comment by TylonHH** [comment]
With the other branch the counters match, they are equal. But as you mentioned the page is lagging longer.

**Comment by PromoFaux** [comment]
Yeah, I'll have to go through it and find out what it was that made the results equal, as it wasn't a fix I put in on purpose!

As per performance, I'm not sure if it's my lack of PHP knowledge, or just that we are reaching the limit of log parsing accuracy.

That said, I'd personally rather have the page take a little longer to load, and be accurate, than load quickly and be a bit wrong!

**Comment by TylonHH** [comment]
And now I can't see any queries. Limit reached?
But on the main page I can see 55k queries today (after 10hr).
![screenshot_2016-09-19-09-07-09](https://cloud.githubusercontent.com/assets/18073299/18626261/28ce1b9c-7e54-11e6-80af-d10c16a28933.png)

**Comment by TylonHH** [comment]
Btw, how could I go back to the current branch?

**Comment by PromoFaux** [comment]
To go back just go back into `/var/www/html/admin` and run `sudo git checkout master`
