### ISSUE TITLE
"ads_blocked_today":"0","ads_percentage_today":"0.0"

### ISSUE THREAD

**Issue by xXAzazelXx** [pi-hole/AdminLTE#150]
Hey Guys,

Sorry I'm very new to all this but Pi Hole Admin panel is not updating Ads Blocked Today and % Of Today's Traffic Is Ads.
![1](https://cloud.githubusercontent.com/assets/20146706/19011587/77c3eaa4-87de-11e6-926e-29c8f44710cf.jpg)

##### Expected Behaviour:
* Information on the Pi Hole Admin panel to show Ads Blocked Today and % Of Today's Traffic Is Ads counters.

##### Actual Behaviour:
* Pi Hole Admin panel is not updating Ads Blocked Today and % Of Today's Traffic Is Ads.

##### Steps to reproduce this issue:

* Raspberry Pi Jessie
* Re ran curl -L https://install.pi-hole.net | bash
* /var/log/pihole.log has entries
* ads are blocked
* http://192.168.2.20/admin/api.php returns

`{"domains_being_blocked":"95,364","dns_queries_today":"2,160","ads_blocked_today":"0","ads_percentage_today":"0.0"}`

* I have tried to change permissions too.
`sudo touch /var/log/pihole.log sudo chmod 644 /var/log/pihole.log sudo chown dnsmasq:root /var/log/pihole.log`

**Comment by PromoFaux** [comment]
Could you please run `pihole -d` and at the end of the script, load a pages with ads on to populate the log snippet before ending the script! That will give us a better idea of your setup.

Might also be worth running `cat /var/log/pihole.log | grep gravity` and pasting in the output of that. Thanks!

**Comment by xXAzazelXx** [comment]
Hey, thanks for the quick reply.

http://termbin.com/hb9f

`
pi@RaspberryPi:~ $ cat /var/log/pihole.log | grep gravity
Oct  1 13:36:29 dnsmasq[9076]: read /etc/pihole/gravity.list - 96423 addresses
Oct  1 13:36:47 dnsmasq[9076]: /etc/pihole/gravity.list appload.ingest.crittercism.com is 192.168.2.20
Oct  1 13:36:47 dnsmasq[9076]: /etc/pihole/gravity.list api.mixpanel.com is 192.168.2.20
Oct  1 13:36:47 dnsmasq[9076]: /etc/pihole/gravity.list decide.mixpanel.com is 192.168.2.20
Oct  1 13:36:55 dnsmasq[591]: read /etc/pihole/gravity.list - 96423 addresses
Oct  1 13:37:00 dnsmasq[591]: /etc/pihole/gravity.list settings-win.data.microsoft.com is 192.168.2.20
Oct  1 13:37:58 dnsmasq[591]: /etc/pihole/gravity.list v10.vortex-win.data.microsoft.com is 192.168.2.20
Oct  1 13:38:07 dnsmasq[591]: /etc/pihole/gravity.list www.googleadservices.com is 192.168.2.20
Oct  1 13:38:15 dnsmasq[591]: /etc/pihole/gravity.list dmd.metaservices.microsoft.com is 192.168.2.20
Oct  1 13:43:07 dnsmasq[591]: /etc/pihole/gravity.list www.googleadservices.com is 192.168.2.20
Oct  1 13:45:15 dnsmasq[591]: /etc/pihole/gravity.list s.thebrighttag.com is 192.168.2.20
Oct  1 13:48:07 dnsmasq[591]: /etc/pihole/gravity.list www.googleadservices.com is 192.168.2.20
Oct  1 13:52:17 dnsmasq[591]: /etc/pihole/gravity.list settings-win.data.microsoft.com is 192.168.2.20
`

**Comment by PromoFaux** [comment]
OK, the good news is that it's definitely blocking ads... but I'm not sure why the Php is falling over. Your log isn't all that big I don't think! We do have an issue at the moment where the PHP exceeds max execution time when logs are too big...

how about `ls -l -h /var/log/pihole.log` ?

**Comment by xXAzazelXx** [comment]
pi@RaspberryPi:~ $ ls -l -h /var/log/pihole.log
-rw-r--r-- 1 dnsmasq root 137K Oct  1 14:10 /var/log/pihole.log

**Comment by PromoFaux** [comment]
Yeah, tiny! Um.. What hardware are you running on?

Also.. this may be a silly one, but it might be worth checking your [power supply is up to the job](https://www.raspberrypi.org/help/faqs/#power)

**Comment by PromoFaux** [comment]
Also what class SD card are you using?

**Comment by xXAzazelXx** [comment]
Its running on Raspberry Pi 3, [https://www.raspberrypi.org/products/raspberry-pi-3-model-b/](url)
I don;t know what class SD but it only booting of it, main partition is on USB 3

**Comment by xXAzazelXx** [comment]
Where does the api.php pulls its data from? sorry i couldn't make sense of it, I'm guessing its some log file?
If its /var/log/pihole.log, maybe its not parsing it correctly, some sort of formatting error?

**Comment by PromoFaux** [comment]
Currently it reads from `/var/log/pihole.log` but there should not be any formatting errors, as it's always worked and we have not changed anything in that area recently....! Have you made any other changes to the system?

Maybe try the install script again to sort out the permissions?

**Comment by xXAzazelXx** [comment]
Well I haven't made any major changes but this is the first time me trying to install this so the counter never worked but looking at my redit post its not just me so probably not a change.
[https://www.reddit.com/r/pihole/comments/55bfz9/ads_blocked_today0_admin_counter_issues/](url)

I have ran manual install ( Last times i ran auto)
`sudo pihole uninstal
wget -O basic-install.sh https://install.pi-hole.net
chmod +x basic-install.sh
./basic-install.sh`

same thing

`{"domains_being_blocked":"96,423","dns_queries_today":"21","ads_blocked_today":"0","ads_percentage_today":"0.0"}`

**Comment by scottsweb** [comment]
The UI/API also stopped counting for me today. I am running the docker version on a Raspberry Pi 2 using Jessie Lite. The recent queries log shows that everything is still working. 

Querying the API I get this response:

```
{"domains_being_blocked":"96,432","dns_queries_today":"180","ads_blocked_today":"0","ads_percentage_today":"0.0"}
```

Running `docker exec pihole chronometer.sh -j` I get back:

```
{"domains_being_blocked":"96432","dns_queries_today":"189","ads_blocked_today":"4","ads_percentage_today":"2.11"}
```

The only real error logs I am seeing from the container are:

```2016-10-01 13:00:30: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  parse_ini_file(/etc/pihole/setupVars.conf): failed to open stream: No such file or directory in /var/www/html/admin/data.php on line 3```

All seemed fine yesterday. Could this be a date related issue?

**Comment by xXAzazelXx** [comment]
Raspberry Pi just had a major OS update [https://www.raspberrypi.org/blog/introducing-pixel/](url) but there is always day light savings today where I am..

**Comment by norrkin** [comment]
I'm experiencing this too, weird as it was reporting correctly yesterday.

**Comment by PromoFaux** [comment]
OK, going to get a fresh SD card and install from scratch to see what's happening. What is confusing is that nothing has changed on the master branches for at least a week! Seems odd that any new bugs introduced then would take a week to trickle through....

(If it's any consolation, the new release branch I'm working on doesn't have this issue... but it's not ready for realease yet!!)

**Comment by Cornmeister** [comment]
installed pihole yesterday, 
today I have the same issue.

**Comment by PromoFaux** [comment]
Could each of you tell us:

1. Distro installed (Raspbian/Ubuntu/Arch etc)
2. Hardware installed on.

thanks!

**Comment by Cornmeister** [comment]
Raspberry pi 2+
Running Jessie lite.
`Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux`

**Comment by xXAzazelXx** [comment]
RaspberryPi 3b
Raspbian Jessie lite

**Comment by norrkin** [comment]
Raspberry pi 2+ with jessie lite.

**Comment by PromoFaux** [comment]
Thanks guys. Just downlading jessie lite, then will see what I can do!

**Comment by scottsweb** [comment]
Raspberry Pi 2
Raspbian Jessie Lite
Linux version 4.4.21-v7+ 
Docker version of Pi Hole (latest)

**Comment by PromoFaux** [comment]
OK, good to know it's happening in docker, too!

**Comment by PromoFaux** [comment]
can you all please [pastebin](http://pastebin.com/) your `/var/log/pihole.log` files please?

**Comment by PromoFaux** [comment]
Or termbin if it's easier:

`cat ~/var/log/pihole.log | nc termbin.com 9999`

**Comment by scottsweb** [comment]
Here you go, it is not all the log. Just some of the recent lookups: http://pastebin.com/Y2kuXJfm

**Comment by PromoFaux** [comment]
FOUND THE ISSUE!

It's on [this line](https://github.com/pi-hole/AdminLTE/blob/master/data.php#L270)

Question is, why has it only just kicked in today? will fiddle with an alternative fix and get it pushed out asap!

**Comment by scottsweb** [comment]
So that line is exploding on the space character. I don't have the old logs to compare it to but I wonder if the date change has introduced more spaces:

<img width="977" alt="161001-160540" src="https://cloud.githubusercontent.com/assets/411945/19014901/1cd99c84-87f1-11e6-9735-05f1470e00af.png">

There are two between the month and day value?

**Comment by escapologyBB** [comment]
@PromoFaux you saw this 5 minutes ago, what's the hold-up?   ;-) I'm joking, I love Pi-Hole  and was just going to report that are experiencing the same issues until you  posted and said you saw what the problem was.

Keep up the good work!

**Comment by PromoFaux** [comment]
Yeah, @diginc just pointed out the double space to me.... I guess we just need to parse the line first and remove all double spaces. (If anyone knows how to do that in PHP, you'll save me a lot of googling!)

**Comment by scottsweb** [comment]
`str_replace("  ", " ", $var);` - seems to simple :)

**Comment by PromoFaux** [comment]
Thanks, that works! I was trying ` preg_replace('/\s+/', ' ',$var);` with no joy.

**Comment by diginc** [comment]
``/ {2,}/` only catches 2+ spaces` so would be more efficient

I'll throw up a PR if no one beats me to it.

**Comment by Cornmeister** [comment]
w00h00, great job guys !

**Comment by PromoFaux** [comment]
Y'all! 

Have just released `1.4.2`, so just run `pihole -up` to get the lastest update!

**Comment by Cornmeister** [comment]
I can confirm its working again !

**Comment by scottsweb** [comment]
Thanks for sorting this. It does not seem possible to execute this on the docker container as a temp fix `docker exec -it pihole pihole -up`... I am guessing I will need to wait for a new image to be released?

error:

```
fatal: Not a git repository (or any of the parent directories): .git
/usr/local/bin/pihole: line 59: /etc/.pihole/automated install/basic-install.sh: No such file or directory
```

**Comment by diginc** [comment]
Sorry my docker doesn't support updating that way...the docker way is to just pull a new image that has the new contents baked into it.  I'll cut a new release so you can docker pull.

**Comment by scottsweb** [comment]
Thank you. Much appreciated 🙇

**Comment by Mcat12** [comment]
O.o I didn't add any labels, but Github said I did?

**Comment by Mcat12** [comment]
Maybe there's some random key combo I keep tripping...

**Comment by Tntdruid** [comment]
Thanks for the quick fix :D

**Comment by diginc** [comment]
@scottsweb looks like the new builds are all finished for the main docker tags: https://hub.docker.com/r/diginc/pi-hole/builds/ 

I'm addition to `docker pull` you have either `docker stop` or `docker rm` your current docker container to send it out to pasture before running the new version.

**Comment by scottsweb** [comment]
@diginc thank you! It just updated. I am keeping an eye on my containers with: https://hub.docker.com/r/centurylink/watchtower/

**Comment by xXAzazelXx** [comment]
worked for me!, thanks a lot for your hard work
