### ISSUE TITLE
Pihole Webinterface not writing to Black/Whitelist

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#153]
@gforke97 commented on [Sat Oct 01 2016](https://github.com/pi-hole/pi-hole/issues/739)
##### Expected Behaviour:

Domains added over the Webinterface should be added to the Black/Whitelist
##### Actual Behaviour:

Domains dont get added to /etc/pihole/whitelist.txt or /etc/pihole/blacklistlist.txt
##### Steps to reproduce this issue:

Adding a domain over the Webinterface
![image](https://cloud.githubusercontent.com/assets/19305191/19015396/f21890aa-8803-11e6-93cc-2cd3e26e3fb1.png)
##

**Comment by gforke97** [comment]
Before i used pi.fritz.box/admin/index.php there it said added succesfully but it didnt write to the file, now I tried <pi's IP>/admin/index.php and there it says something went wrong.

**Comment by gforke97** [comment]
Heres the log http://termbin.com/q3mr

**Comment by PromoFaux** [comment]
Couple of things to note:
`2016-09-28 18:07:04: Failed CORS: http://pi.fritz.box vs http://192.168.178.34,http://pi.hole,http://localhost`

Also in your `blacklist.txt` you need to remove anything with a `*` in, as we currently do not support wildcards

**Comment by gforke97** [comment]
heres the new debug file http://termbin.com/z1t6

**Comment by Mcat12** [comment]
Is it working now? There aren't any relevant errors in the log.

**Comment by gforke97** [comment]
Its working now just tested it.

**Comment by DL6ER** [comment]
I close this issue as it is working for the reporter. Feel free to re-open the issue if you see this problem again!
