### ISSUE TITLE
PHP Warning Fatal error:  Allowed memory size

### ISSUE THREAD

**Issue by dschaper** [pi-hole/AdminLTE#155]
@TylonHH commented on [Fri Oct 07 2016](https://github.com/pi-hole/pi-hole/issues/759)

**[BUG | ISSUE] Actual Behaviour:**
The admin page just shows the total number of domains being blocked. The other figures are 0. Also the query log is empty.
But Ads are still blocked on my devices.

I run `piholeLogFlush.sh` with no success.
My `/var/log/pihole.log` is now 4193 big.
I have an RPi 3
With nearly the same setup it works like a charm. What have I done? I completely installed the new update 2.9.2 on top on an other [project](https://github.com/volkszaehler).

Here is my [pihole -d](http://termbin.com/30sk)

---

@dschaper commented on [Fri Oct 07 2016](https://github.com/pi-hole/pi-hole/issues/759#issuecomment-252377113)

Quick check: 
```
cd /etc/.pihole
sudo git status
```
Just to make sure you are on the master branch.

```
cd /var/www/html/admin
sudo git status
```

---

@TylonHH commented on [Fri Oct 07 2016](https://github.com/pi-hole/pi-hole/issues/759#issuecomment-252377351)

yes I'm. Both response with nothing to change.

---

@dschaper commented on [Fri Oct 07 2016](https://github.com/pi-hole/pi-hole/issues/759#issuecomment-252377429)

`ls -lahc /var/log/pihole.log`

---

@TylonHH commented on [Fri Oct 07 2016](https://github.com/pi-hole/pi-hole/issues/759#issuecomment-252377523)

`-rw-r----- 1 dnsmasq root 50K Okt  8 00:37 /var/log/pihole.log`

---

@dschaper commented on [Fri Oct 07 2016](https://github.com/pi-hole/pi-hole/issues/759#issuecomment-252377717)

Okay, this looks like it may be an Admin interface issue. Moving this issue over to that GitHub repository.

**Comment by Mcat12** [comment]
I have a feeling it's a permissions issue. Try `sudo chmod 644 /var/log/pihole.log`.

**Comment by TylonHH** [comment]
You have very good feelings. Now it's working.
Thank you very much
