### ISSUE TITLE
Admin does not load on php 5.3

### ISSUE THREAD

**Issue by bcambl** [pi-hole/AdminLTE#157]
##### Expected Behaviour:
Expect web admin UI to load.

##### Actual Behaviour:
admin UI does not load.
Error in logs:
```
(mod_fastcgi.c.2694) FastCGI-stderr: PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/html/admin/header.php on line 4
```
##### Steps to reproduce this issue:
Deploy using php 5.3.

**Comment by Mcat12** [comment]
Don't know what's going on with those `in progress` labels... It's been doing that at random for awhile.

**Comment by PromoFaux** [comment]
It's either to do with ZenHub or gitApprove...
