### ISSUE TITLE
Whitelist Being Ignored completely (2.9.2 issue on Ubuntu?)

### ISSUE THREAD

**Issue by dschaper** [pi-hole/AdminLTE#159]
@sam24and48 commented on [Mon Oct 10 2016](https://github.com/pi-hole/pi-hole/issues/775)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [x] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:** I have added multiple addresses including msftncsi.com, www.msftncsi.com, support.microsoft.com, and msn.com. We performed this last week and it fixed the issue of limited connectivity on our machines and also the ability to get to pages on support.microsoft.com and confirmed connectivity to msftncsi.com. (However today after the weekend and the 2.9.2 update it is pi-holing all of those addresses)

**[BUG | ISSUE] Actual Behaviour:** It appears to be completely ignoring the whitelist entirely. Today as I have done nslookups on the machines for all of those addresses they are pointing directly to the pi-hole ip. I have rebooted the pi-hole device multiple times along with dnsflushes on the machines multiple times. I can see in the web admin interface where it is flat out pi-holing the address when I go to it even though it is specifically added to the whitelist (example: support.microsoft.com).

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/s1lw`

---

@dschaper commented on [Mon Oct 10 2016](https://github.com/pi-hole/pi-hole/issues/775#issuecomment-252661647)

Hi, how are you adding the domains to the whitelist? Via commandline or via the web interface?

---

@dschaper commented on [Mon Oct 10 2016](https://github.com/pi-hole/pi-hole/issues/775#issuecomment-252662070)

And I do show that support is blacklisted on one of the lists:
```
::: /etc/pihole/list.7.raw.githubusercontent.com.domains (2 results)
diagnostics.support.microsoft.com #Microsoft
support.microsoft.com #Microsoft
```

---

@sam24and48 commented on [Mon Oct 10 2016](https://github.com/pi-hole/pi-hole/issues/775#issuecomment-252665347)

I added it via the web interface

---

@dschaper commented on [Mon Oct 10 2016](https://github.com/pi-hole/pi-hole/issues/775#issuecomment-252665551)

Okay, I'd like to move this issue over to the Web Interface repository for further review. Better venue to handle the questions.

**Comment by Mcat12** [comment]
Run `cat /etc/pihole/gravity.list | grep support.microsoft.com`.

**Comment by sam24and48** [comment]
![pihole1](https://cloud.githubusercontent.com/assets/22749690/19270211/cf4cca7e-8f8c-11e6-8b30-956c5d2a1c09.png)

Here are the results of that command

**Comment by PromoFaux** [comment]
I'm not sure this is a web interface issue. However we'll keep it here instead of moving it about too much! :)

Can you please run `pihole -g` to re-run the gravity script, and then give us the output of the command @Mcat12 asked again? thanks!

**Comment by sam24and48** [comment]
Sooooooo.... here's the output. It appears it stuck this time. I know for a fact I ran that pihole -g yesterday? Did some of the lists get changed since then maybe?

![pihole2](https://cloud.githubusercontent.com/assets/22749690/19270766/9f99e692-8f8f-11e6-8ceb-8f9b7d9d9f34.png)

and here we ran the command again and got no output:
![pihole3](https://cloud.githubusercontent.com/assets/22749690/19270781/ac2b6ee4-8f8f-11e6-8a46-ccde74b4a423.png)

**Comment by PromoFaux** [comment]
We may or may not have introduced an edge-case bug or two in 2.9.2 that doesn't run gravity properly during update, but is resolved by a simple run of `pihole -g` 😊 

We're furiously working on getting that fixed here... https://github.com/pi-hole/pi-hole/pull/774

Anyway, glad it's now working for you, and seems I was right about it not being web interface related. If it happens again, please feel free to reopen the original issue you opened here : https://github.com/pi-hole/pi-hole/issues/775

**Comment by sam24and48** [comment]
Will do, thanks again for your help!
