### ISSUE TITLE
Some QoL requests and minor UI changes

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#161]
@tomose commented on [Fri Oct 14 2016](https://github.com/pi-hole/pi-hole/issues/782)
1. "Ads Blocked Today" -> "Queries Blocked Today"
   Not everything blocked is an ad. Trackers, other malicious domains, etc.
2. "Of Today's Traffic Is Ads" -> "Of Today's Queries Denied"
   Just better wording.
3. QoL request - Be able to set default number of entries in log via web interface (am aware that it can be done manually through editing a file).
4. QoL request - Filter log to show only blocked, unblocked, or all domains.
5. QoL request - Nav page links on top of query log as well (so you don't have to scroll down to move to the next page)

That's it really. Appreciate how great this works. Looking forward to being able to wildcard domains for easier blocking in the future. :)
##

**Comment by PromoFaux** [comment]
Thanks for the suggestions!

We have some work going on in the background that is set to improve the query log page... though first we're making sure that we've got the install scripts absolutely solid! So we can bare some of this in mind for when we make that change..

Could you expand on 3, please? How do you mean by setting number of entries in the log?

Also with 4, you can currently type "Pi-holed" in the search box to get all blocked queries, or "OK!" to get the non-blocked ones...

**Comment by tomose** [comment]
In regards to 3, basically have it default to 10,25,50,100 based on what a person sets it to in the web interface and stay that way until changed. That's all. Right now it resets upon reload. Have that setting stored somewhere.

**Comment by DL6ER** [comment]
@tomose The current status of your requests is:

1. Done
2. Done
3. All data is sent to the client's browser. If you select a different number of of queries to be display, then the server does not get informed about this, i.e. remembering it would be impossible. Not sure if we could construct a more-or-less complicated callback. However, I don't see any benefits.
4. As PromoFaux said, you can search for "OK" or "Pi-holed". You can sort by this field
5. I will look into this, might be possible. However, note that (at least in the current `devel` version) there is also a new option "All" which I added recently. Maybe there is no need for additional nav control on top with "All"?

**Comment by PromoFaux** [comment]
Regards number 3, perhaps a preference stored in setupVars?

**Comment by DL6ER** [comment]
Concerning point no. 4

![screenshot at 2016-11-25 23-30-30](https://cloud.githubusercontent.com/assets/16748619/20636120/5b2206b0-b367-11e6-95c1-944373a95573.png)

Done :stuck_out_tongue_winking_eye:

**Comment by PromoFaux** [comment]
Soon I might actually get 5 mins to sit down and do some coding! You're putting me to shame... ;)

**Comment by DL6ER** [comment]
@PromoFaux Concerning "remember selected value": I checked [here](https://datatables.net/reference/option/lengthMenu) and [there](https://datatables.net/reference/option/pageLength) and reporting the selected option back to the server is not supported.

**Comment by Mcat12** [comment]
We can also look into saving a cookie to remember the selected number of entries.

**Comment by DL6ER** [comment]
@Mcat12 As far as I know datatables does not support to have anything hooked to the selection, so I wouldn't know where to put such code.

**Comment by Mcat12** [comment]
If we're able to add an id or somehow get the element through jQuery, we can add an on-click handler that would handle the cookie. But I'm not sure how feasible that would be. Google is our friend. ;)

**Comment by DL6ER** [comment]
I found how to access it. Let's leave it here for later reference:
`$('select[name=all-queries_length] option:selected').text();`

**Comment by DL6ER** [comment]
I'll add a setting for selecting the default value on the new settings page currently under development.

**Comment by DL6ER** [comment]
Everything except no. 3 has been implemented. Please open a Feature Request on Discourse if you still want it. There users can vote for features. Since all remaining points have been implemented and the Update has been released, I'm closing this issue.
