### ISSUE TITLE
can't make 'a new version is available' overlay close

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#163]
@vinceskahan commented on [Sat Oct 15 2016](https://github.com/pi-hole/pi-hole/issues/785)

Is there a way to close the blasted overlay that nags heck out of us ?   Why aren't you just putting up a small red 'update available' or something ?   

---

@PromoFaux commented on [Sat Oct 15 2016](https://github.com/pi-hole/pi-hole/issues/785#issuecomment-253951317)

Yeah, we hear you on that! It's a bit annoying.. with any luck we'll get it into the next update. (You could always update.. that will get rid of it!)

If you don't want to update, just click anywhere else on the page to make it disappear ...

**Comment by PromoFaux** [comment]
Fixed in #164

**Comment by dschaper** [comment]
Tested.

**Comment by PromoFaux** [comment]
Fixed in next release
