### ISSUE TITLE
Reflective XSS on list.php

### ISSUE THREAD

**Issue by z** [pi-hole/AdminLTE#166]
I believe [list.php](
https://github.com/pi-hole/AdminLTE/blob/master/list.php#L23) is vulnerable to reflective XSS by echoing out the `$_GET['l']` value without any validation or sanitization.

A quick remedy would be to use a check such as the one in [get.php](https://github.com/pi-hole/AdminLTE/blob/master/php/get.php):

```
if($type !== "white" && $type !== "black")
    die("Invalid list parameter");
```

**Comment by PromoFaux** [comment]
Thanks for this, we'll take a look at it and see what we can come up with. Of course if you get to it before us, feel free to submit a pull request!

**Comment by Mcat12** [comment]
It does appear that the CSP rule does prohibit the inline code from running, but to be sure it won't run this will be fixed.
