### ISSUE TITLE
Request: CPU temp in Fahrenheit

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/AdminLTE#176]
i edit the header.php file after every update to show CPU temp in Fahrenheit instead of Celsius, this is a PITA since i must revert the changes so the update will run, if not i get this error:

 [-]  error: Your local changes to the following files would be overwritten by merge:
    header.php
Please, commit your changes or stash them before you can merge.
Aborting
 done!
:::
::: Web Admin version is now at v1.4.3.1a
::: If you had made any changes in '/var/www/html/admin', they have been stashed using 'git stash'

i use this to change to Fahrenheit:
Line 13:     $output = str_replace(["\r\n","\r","\n"],"", $output*9/5)+32;
and:
Line 151:    if ($output > "113") {

is it possible to have this as a builtin option? maybe by clicking on the temp in the admin page will toggle it?
##

**Comment by PromoFaux** [comment]
Certainly something we can look at implementing! Thanks for the suggestion!

**Comment by C4Wiz** [comment]
:+1:

**Comment by DL6ER** [comment]
I'm working on this right now.

**Comment by DL6ER** [comment]
I have this done. However, before starting a pull request for this new feature, I have to wait until my running pull request is merged.

@PromoFaux 
I'm currently not allowed to create branches in the AdminLTE repository. Could someone give me this permission? I have a lot of improvements lying around which I want to give to the community. It would be much easier if I could start the pull requests from branches within this repository.

**Comment by Mcat12** [comment]
You should be able to create multiple branches in your own fork, which could each be it's own pull request. I'll check with Adam on repo permissions though, but you shouldn't be limited in how many pull requests you can make!

**Comment by DL6ER** [comment]
My point is not that I cannot make multiple PR at the same time, but currently my devel branch is out-of-line with yours as the Chart.js upgrades are in there. If I cannot get permission on this repository, then I will just have to wait until my other PR is merged: then our devel branches are in sync again and I can start diverging branches from my own fork.

**Comment by Mcat12** [comment]
You can branch off at [this](https://github.com/DL6ER/AdminLTE/commit/ae2f3a6f4a45140d97eb4b78c6246f65ec0e0483) commit and it will work fine. Your pull request is just waiting on another review, but it should be good to go soon.

**Comment by Mcat12** [comment]
You have been given permission to create branches in this repo, but master and devel are protected.

**Comment by PromoFaux** [comment]
Hold on, I've just removed your perms from this repo.. as you shouldn't need them...!

Although reading over the situation I can understand the state your local fork has gotten into... let this be a lesson on always branching when working on features!

If you need to do more off of `devel` in the mean time then add this as a remote to your local fork:

```
git remote add official https://github.com/pi-hole/AdminLTE.git
```

And then you can branch off of `devel` by running:
```
git branch -b featureBranchName official/devel
```

I think..

**Comment by DL6ER** [comment]
Okay, I can do it like this as well, just though working on the repo itself (not the protected branches though) would be easier. Anyhow, surely I can also use my own fork for this.

NB: We should delete all of our comments here, as they are unrelated to the issue itself.

**Comment by PromoFaux** [comment]
I've just merged your original PR for Charts.JS, so you can now update your `devel` from the official repo to get back to where you need to be (Or just delete the fork and start again!!)

Just remember: Branch branch branch branch branch branch branch branch branch branch and branch again! (Oh, and commit often. And branch.)

**Comment by PromoFaux** [comment]
I'll delete them all in a few mins

**Comment by DL6ER** [comment]
This has been implemented. It will be available in the next release.

**Comment by DL6ER** [comment]
@C4Wiz You will also be able to change the units from the Web UI (via the new "Help Center")

**Comment by C4Wiz** [comment]
very impressive!
