### ISSUE TITLE
Interface issues after update to v1.4.4.2

### ISSUE THREAD

**Issue by darkrangr** [pi-hole/AdminLTE#189]
##### Expected Behavior:
Status to show correctly and enable button to do something. 

##### Actual Behavior:
Status now shows as Starting forever
Enable button when clicked does nothing. I can't see that it ever disables / is disabled

##### Steps to reproduce this issue:
Debian 8.6 
Upgrade from 1.4.3 to 1.4.4.2

**Comment by Mcat12** [comment]
What is the version of Pi-hole? Check `Pi-hole Version` in the lower right of the web interface or run `pihole version`.

**Comment by Mcat12** [comment]
Please create a debug log with `pihole -d` and post the output of `pihole status`

**Comment by darkrangr** [comment]
There is no status command. 

![image](https://cloud.githubusercontent.com/assets/20601906/20113593/d5e2af32-a5a5-11e6-88ea-a65f9f2613e7.png)

**Comment by DL6ER** [comment]
What is with `pihole -d`?

**Comment by Mcat12** [comment]
It creates a debug log so we can help troubleshoot. Also, since you don't have the status command something must have gone wrong with the update. Try `pihole -up`.

**Comment by darkrangr** [comment]
I tried the -up command and it states everything is already up to date. I don't want to provide a debuglog as it has a lot of entries for my private dns mappings. Is there a specific section you'd look me to post?

![image](https://cloud.githubusercontent.com/assets/20601906/20151820/84748b40-a670-11e6-81d0-8100e2e542c3.png)

**Comment by Mcat12** [comment]
That debug log is also of an older layout. In `/etc/.pihole` run `sudo git status` and `sudo git show`.

**Comment by darkrangr** [comment]
![image](https://cloud.githubusercontent.com/assets/20601906/20158706/f3786000-a690-11e6-9493-8b89b207705b.png)

**Comment by Mcat12** [comment]
Run `pihole -r` and choose "Repair".

**Comment by darkrangr** [comment]
Cool - that fixed it. 

install.log if it helps

:::
::: Installing scripts to /opt/pihole... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... already exists!
:::
::: Installing pihole custom index page... Existing page detected, not overwriting
::: Installing sudoer file... done!
:::
::: Installing latest Cron script... done!
::: Configuring iptables for httpd and dnsmasq..
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Cleaning up previous install (preserving whitelist/blacklist)
::: Running gravity.sh
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
::: Getting sysctl.org list... List updated, transport successful!
::: Getting zeustracker.abuse.ch list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: 
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 125634 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 101561 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
::: Whitelisting 7 domains... done!
::: BlackListing 0 domains... done!
::: Formatting domains into a HOSTS file...
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq...
::: Pi-hole blocking is Enabled
