### ISSUE TITLE
Feature request: adding to white/blacklist directly from the Query log

### ISSUE THREAD

**Issue by wilatai** [pi-hole/AdminLTE#193]
Hi,

Every now and then I see requests in the query log page that I actually do want to block but are not blocked yet. Of course (but I haven't personally encountered this situation yet), the other way around is also possible: requests that are pi-holed, but that you want to add to the white list.

If you want to make such a change in white-/blacklisting, you currently have to do this via the white-/blacklist pages. (Manually entering the domain or via a copy/paste action between those pages).

My feature request/suggestion is to be able to also do such white-/blacklisting tasks directly from the query log page in a fast and convenient way via a button after each item in the query log. ("White-/blacklist this domain" depending on its status).

Analogue to how after each row on the white-/blacklist pages, there is a trash can icon to delete the item in question.

What are your thoughts about this idea?

P.S. This is a wonderful project. I know quite a few people, including myself, who are very grateful for what it brings. :)

**Comment by DL6ER** [comment]
I have been working on this lately.

**Comment by DL6ER** [comment]
Please see my PR #194

**Comment by wilatai** [comment]
@DL6ER, that sounds and looks wonderful and very convenient! 😃

**Comment by DL6ER** [comment]
This has been implemented. It will be available in the next release.
