### ISSUE TITLE
Warnings shown to non-admin, Irrelevant warnings can't be disabled at all, Warnings are just plain wrong

### ISSUE THREAD

**Issue by Pingger** [pi-hole/AdminLTE#2153]
### Versions

- Pi-hole:  5.9
- AdminLTE:  5.11
- FTL:  5.14

### Platform

- OS and version:  Ubuntu 20.04 Server Core

- Platform:  lxd

### Expected behavior

"Warnings" being
1. Correct
2. permanently hideable
3. Warnings not being shown without being logged in! 

### Actual behavior / bug

1. Getting 
```
"Long-term load (15min avg) larger than number of processors: 14.9 > 8
This may slow down DNS resolution and can cause bottlenecks."
```
Despite 
    - having 16 Processor-Cores on the Host and only a single one assigned to the container.
    - This Warning being completely irrelevant!
    - The warning annimation annoying the heck out of me.
2. Displaying the Wrong amount of processor cores
3. Warnings are visible

### Steps to reproduce

1. Install PI-Hole
2. Open the Admin UI

## Debug Token

- URL:   https://tricorder.pi-hole.net/efMfHbXk/

### Screenshots

![image](https://user-images.githubusercontent.com/4761298/159131690-b799c4ba-c1b1-4931-9360-3a987df11871.png)

### Additional context

I thought this would be fixed, but after >3 months this issue still persists.

**Comment by yubiuser** [comment]
Disable the check
https://docs.pi-hole.net/ftldns/configfile/#check_load

**Comment by Pingger** [comment]
Does not solve the issue, that warnings are displayed without login!

**Comment by PromoFaux** [comment]
> Does not solve the issue, that warnings are displayed without login!

This bit may have been overlooked - however I have just tried this myself.. I cannot access the messages page unless it is logged in. There is a hint that there are warnings to review, but one still needs to actually log in to see the warnings.

>Also does not resolve wrong information being displayed.

I can't help on this one, @DL6ER, if you have moment free at some point - does the output reported by the OP look right/wrong to you? And is there any kind of useful information OP could provide that might actually help us help them (and/or help them to help themselves)

> I thought this would be fixed, but after >3 months this issue still persists.

Have you reported this before?

And please, improve your tone.
