### ISSUE TITLE
Showing code

### ISSUE THREAD

**Issue by flaxues** [pi-hole/AdminLTE#238]
##### Expected Behaviour:
Load the website normally

##### Actual Behaviour:
Shows the code of the index.php file
https://i.gyazo.com/e2bc8df31097c47d11fb133906eb4fd8.png

##### Steps to reproduce this issue:
Install pi-hole

**Comment by dschaper** [comment]
Can you run `pihole -d` and get us the token for the debug log output.

**Comment by flaxues** [comment]
ifdo1p3ohu

**Comment by Mcat12** [comment]
You have apache and lighttpd fighting over port 80, so you will need to move apache to a different port.

**Comment by flaxues** [comment]
@Mcat12 And how do I do that?

**Comment by Mcat12** [comment]
http://stackoverflow.com/a/26064554

**Comment by flaxues** [comment]
@Mcat12 Wew never thought it was just this small thing! Thanks!!
