### ISSUE TITLE
Issue #194 from the main pi-hole repo

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#27]
Just opening an issue here for [this](https://github.com/pi-hole/pi-hole/issues/194) issue, as it's to do with the web side of things.

**Comment by Mcat12** [comment]
So, we have a security hole? I don't fully understand what he wants us to do.

**Comment by PromoFaux** [comment]
No, I've never been entirely sure what it is. @jacobsalmela tagged it as an enhancement, so I figured he knew what it was about...

**Comment by DonLexos** [comment]
Seems like you tag includes for CSS/JS that are not serverd by yourself?

**Comment by PromoFaux** [comment]
Isnit not just the cdns for jquery and bootstrap?

**Comment by jacobsalmela** [comment]
I just tagged it as an enhancement, but didn't fully look at it.  I guess I don't fully understand what he wanted--something to do with it being coded insecurely, which his department cannot work with, however, I had trouble understanding the original request.  If @Mcat12 doesn't know what he means, than I don't know that the rest of us will.  I just wanted to eliminate any security issues if there really is one.

**Comment by Mcat12** [comment]
I think he may be taking about some JavaScript thing where using "eval" (runs JavaScript code in it's parameter, ex eval("1+1")). I don't think there's a security issue though, as JavaScript is run client side. If there is, it would be nice for him to elaborate.

**Comment by jacobsalmela** [comment]
@magarto, can you elaborate on what you meant in your original issue?  We are a bit confused.

**Comment by Mcat12** [comment]
I just came back to this issue, and I think I understand a bit of what he's saying. This [link](http://www.html5rocks.com/en/tutorials/security/content-security-policy/#inline-code-considered-harmful) he shared does a good summary. Basically, we should move all Javascript to their own files and remove JS code in the html (onclick, etc) and instead use event handlers.

**Comment by jacobsalmela** [comment]
Cool, that makes more sense.
