### ISSUE TITLE
Session timer resets every 10 secs.

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/AdminLTE#274]
##### Expected Behaviour:

session timer should count down to zero and log you out
##### Actual Behaviour:

session counts down from 23:59 to 23:50, then goes back to 23:59
##### Steps to reproduce this issue:
login and look at the session timer

**Comment by DL6ER** [comment]
This is a feature.

Look in the new `Help Center`. The last paragraph under `Main page` ;-)

**Comment by C4Wiz** [comment]
then whats the point of the session timer if it will never expire?

**Comment by DL6ER** [comment]
Well, it does expire on any other page.
