### ISSUE TITLE
Summary doesn't display when accessing through pi.hole

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#277]
![image](https://cloud.githubusercontent.com/assets/1998970/21406421/72e54b48-c7c3-11e6-8d1b-6a18067c369e.png)

![image](https://cloud.githubusercontent.com/assets/1998970/21406428/80b6a5aa-c7c3-11e6-9246-56709e4d49af.png)

**Comment by Mcat12** [comment]
Summary seems to be working fine over here. Do you have a debug log?

**Comment by PromoFaux** [comment]
Just uninstalling and reinstalling again. Something has gone wrong I think.

**Comment by PromoFaux** [comment]
Clearing browser cache fixed it
