### ISSUE TITLE
Possible layout bug on mobile

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#282]
From [reddit comment](https://www.reddit.com/r/pihole/comments/5jlhg5/pihole_210_and_web_admin_20_released_with_lots_of/dbigcz7/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=pihole)

I've done the update on mine and it all went well.

This really is a minor cosmetic issue, but the boxes don't align properly when accessing the admin interface on mobile. It doesn't cause any problems of course, but I thought you may want to know about it :)

http://imgur.com/lDZXj0u

Otherwise, it's working great and you guys do a fantastic job.

**Comment by DL6ER** [comment]
Confirmed. Looking into this.

![screenshot_20161222-220948](https://cloud.githubusercontent.com/assets/16748619/21440475/70401118-c893-11e6-9d64-da8a94c3f240.png)
