### ISSUE TITLE
UI shows no temp, Top Domains and Top Advertisers are mashed up.

### ISSUE THREAD

**Issue by 69si1ma3** [pi-hole/AdminLTE#294]
After update my pi-hole don't show temp in UI ,it shows 0. I'm running it on Orange Pi with Armbian. Sometimes seems that results in Top Domains and Top Advertisers are mashed up.

[https://streamable.com/kx9ib](https://streamable.com/kx9ib)

**Comment by Mcat12** [comment]
Please make a debug token via `pihole -d`.
What is the output of these commands?
```
cat /sys/class/thermal/thermal_zone0/temp
cat /sys/class/hwmon/hwmon0/temp1_input
```

**Comment by 69si1ma3** [comment]
```
cat /sys/class/thermal/thermal_zone0/temp
42
cat /sys/class/hwmon/hwmon0/temp1_input
cat: /sys/class/hwmon/hwmon0/temp1_input: No such file or directory
```
 Is token supposed to be shared here publicly?

**Comment by Mcat12** [comment]
Looks like your OS changed how it shares temperature. When I run the first command, I get `39007` as the output, which is normally how it works. If you divide by 1000, you get `39` which is the temperature in Celsius. On your OS, they automatically covert to plain Celsius. I'll prepare a fix for the next release!

**Comment by Mcat12** [comment]
@69si1ma3 You can replace those lines in `/var/www/html/admin/header.php` with the changed ones in that PR if you want as a short-term fix until the update is released.

**Comment by 69si1ma3** [comment]
Thank You very much! I applied the fix. On the other issue with domain listings, did I got something wrong? Was under assumption that Top Domains list only shows valid domains, not the flushed ones. Also, not sure about amount lists shows, for example: from www.reddit.com while I get 390 hits in Top Domains list, in Top Advertisers from events.redditmedia.com it's 2147 hits. In overall, daily I get ~50% queries blocked, and higher, I don't see any ads, just numbers seems a bit high.

**Comment by DL6ER** [comment]
> just numbers seems a bit high

Well, in your screen recording I see that the Top Domain was reddit with about 250 queries. However, on the ads side, there is google-analytics with > 1400 queries. Given the low percentages on your Top Domains list, I conclude that you visited a lot of different sites and many of them wanted to display ads through Google's analytics.

I'll think about why you see some blocked Domains under Top Domains. I extended my Top Domain list to show 50 entries and I see not a single blocked entry...

**Comment by Mcat12** [comment]
That mashup issue does seem weird, and we'll look into it some more. Does it happen often, with many domains at a time or only one, and is the domain(s) the same one every time?

**Comment by DL6ER** [comment]
Could you do another debug run for us with some more browsing? In the debug token you already posted, you haven't come across any ads.

**Comment by 69si1ma3** [comment]
Domain mashup seems random.
I'll start fresh tomorrow, and will post results.

**Comment by Mcat12** [comment]
We think the issue is because of a difference in how the top domains/ads gets created vs the query log. @DL6ER has started on a fix.

**Comment by DL6ER** [comment]
We have a fix for what you see.

Let me explain to you why you are seeing this: While your pi-hole is disabled (also if only temporarily) there strictly are no Ads, because everything is permitted. Hence, all queries from this period will account for Top Domains rather than Top Ads (only blocked entries go into this one). We change the behavior in the future by identifying whether a domain is an Ad not by the fact if it has been permitted or not but rather by looking into the ad lists (+ blacklist) and see if it is there.
