### ISSUE TITLE
Graphs not updating

### ISSUE THREAD

**Issue by seawhite** [pi-hole/AdminLTE#295]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

**[BUG | ISSUE] Expected Behaviour:**
Graphs should be showing ads blocked and dns queries over a 24 hour period. Please note, I did uninstall and reinstall Pihole yesterday.

**[BUG | ISSUE] Actual Behaviour:**
Currently, it appears to be stuck on the previous day and is not updating with new information. The API is returning the following information:

{"domains_over_time":["44","77","206","326","85","76","51","170","132","40","304","80","74","77","227","73","209","460","317","143","254","43","61","236","122","118","70","49","67","114","75","38","77","55","54","91","93","40","82","55","57","105","75","89","48","65","57","82","74","52","83","140","95","138","227","258","382","439","398","405","98","77","75","49","43","53","55","48","86","39","33","87","82","47","41","59","43","50","60","40","51","50","36","49","74","46","57","40","35","50","49","25","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","28","72","55","56","35","44","69","45","261","97","174","507","143","73","50","38","41","58"],"ads_over_time":["7","7","34","75","18","14","10","17","7","3","73","12","10","9","44","9","46","61","64","44","23","11","16","42","17","12","12","11","18","18","16","13","13","13","11","10","14","11","10","8","13","12","10","15","9","11","9","9","12","5","14","25","18","19","28","36","41","51","70","26","6","9","4","1","2","3","2","3","2","1","0","2","2","1","0","1","3","3","2","3","1","1","0","2","4","1","0","1","2","2","2","2","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","3","2","1","0","4","2","1","48","11","12","47","20","1","1","1","2","2"]}

Picture of the graph:
https://www.dropbox.com/s/k7mdp31noerzl3g/Screenshot%20from%202016-12-24%2015-41-11.png?dl=0

Here is head and tail of pihole.log

root@homeserv:/var/log# head pihole.log 
Dec 23 21:08:34 dnsmasq[19266]: started, version 2.75 cachesize 10000
Dec 23 21:08:34 dnsmasq[19266]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Dec 23 21:08:34 dnsmasq[19266]: warning: ignoring resolv-file flag because no-resolv is set
Dec 23 21:08:34 dnsmasq[19266]: using nameserver 8.8.4.4#53
Dec 23 21:08:34 dnsmasq[19266]: using nameserver 8.8.8.8#53
Dec 23 21:08:34 dnsmasq[19266]: read /etc/hosts - 7 addresses
Dec 23 21:08:34 dnsmasq[19266]: read /etc/pihole/local.list - 4 addresses
Dec 23 21:08:35 dnsmasq[19266]: read /etc/pihole/gravity.list - 52611 addresses
Dec 23 21:08:35 dnsmasq[19266]: query[A] ssl.gstatic.com from 192.168.1.63
Dec 23 21:08:35 dnsmasq[19266]: forwarded ssl.gstatic.com to 8.8.4.4
root@homeserv:/var/log# tail pihole.log 
Dec 24 15:46:29 dnsmasq[19507]: reply clients.l.google.com is 2607:f8b0:4009:80d::200e
Dec 24 15:47:27 dnsmasq[19507]: query[A] clients6.google.com from 192.168.1.63
Dec 24 15:47:27 dnsmasq[19507]: forwarded clients6.google.com to 8.8.4.4
Dec 24 15:47:27 dnsmasq[19507]: forwarded clients6.google.com to 8.8.8.8
Dec 24 15:47:27 dnsmasq[19507]: reply clients6.google.com is <CNAME>
Dec 24 15:47:27 dnsmasq[19507]: reply clients.l.google.com is 172.217.4.238
Dec 24 15:47:27 dnsmasq[19507]: query[AAAA] clients6.google.com from 192.168.1.63
Dec 24 15:47:27 dnsmasq[19507]: forwarded clients6.google.com to 8.8.4.4
Dec 24 15:47:27 dnsmasq[19507]: reply clients6.google.com is <CNAME>
Dec 24 15:47:27 dnsmasq[19507]: reply clients.l.google.com is 2607:f8b0:4009:80c::200e

**[BUG | ISSUE] Steps to reproduce:**
Navigate to front page or hit the API for overTimeData10mins.
http://pihole/api.php?overTimeData10mins

The values are never updating.

**(Optional) Debug token generated by `pihole -d`:**

`j10f8315do`

**Comment by seawhite** [comment]
Actually, it does look like it's updating. Basically it is only showing midnight to midnight instead of showing 24 hours back from the current time. I feel like it should be scrolling, so if it's 4 PM on 12/24, the graph should have the time range of 4 PM 12/23 to 4 PM 12/24. This may be due to me reinstalling yesterday?

**Comment by Mcat12** [comment]
If you uninstalled Pi-hole yesterday and then reinstalled today, then the flush command sent at midnight would not have been executed. So if Pi-hole was not installed at that time, then the logs would not have been flushed. It should fix itself tonight, but if you want to flush the log now you can run `pihole -f`.

**Comment by seawhite** [comment]
Thank you for your response. I checked it again today and it still doesn't appear to be working. I am using Apache instead of Lighttpd so I tried to turn off Apache then use Lighttpd instead but still no go. I did clear my browsers cache and tried in Chrome and Firefox. I am going to look into it more and see if I can come up with anything. Here is todays screenshot:
https://www.dropbox.com/s/gl9b048d74j5hss/Screenshot%20from%202016-12-25%2014-15-38.png?dl=0

root@homeserv:/opt/pihole# ./update.sh 
::: Checking for updates...
:::
::: Pi-hole version is v2.10.1
::: Web Admin version is v2.2
:::
::: Everything is up to date!

**Comment by DL6ER** [comment]
> I checked it again today and it still doesn't appear to be working.

We found a bug that prevents the correct flushing of the logs for some users. We already have a fix for this and will release it soon (currently our team is put on the back burner because of visiting relatives etc. over the holidays).

**Comment by seawhite** [comment]
Awesome! I will give that a shot. Thank you and have a Merry Christmas :)
