### ISSUE TITLE
Reverse DNS lookup for top clients fails on ipv6 addresses

### ISSUE THREAD

**Issue by darkrain-nl** [pi-hole/AdminLTE#302]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{4}_

**[BUG | ISSUE] Expected Behaviour:**
Show host name instead of ipv6 address, combine with ipv4.

**[BUG | ISSUE] Actual Behaviour:**
Ipv6 address is shown, ipv4 is working as expected.
This seems to be a PHP problem, I could not get it to work using the "gethostbyaddr" function in PHP.
I'm not sure why this is not working, searching the internet learns me this should work, but hey I'm not an experienced PHP programmer. Maybe you guys have an idea how to fix this?
![2016-12-27 18_08_25-pi-hole admin console](https://cloud.githubusercontent.com/assets/24763370/21504503/c8528e88-cc5f-11e6-8d98-426572fb125e.png)

**[BUG | ISSUE] Steps to reproduce:**
- Just turn the reverse DNS lookup feature on for Top Clients and use ipv6 across your network.
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`1ejnds0yx6`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Just to clarify: Is this not working for all IPv6 clients, i.e. are the ones which have been resolved all IPv4?

**Comment by DL6ER** [comment]
@darkrain-nl Use this command to check for IPv6 support:

```
php -i | grep -i "IPv6"
```
gives me:
```
IPv6 Support => enabled
```

**Comment by darkrain-nl** [comment]
Yep, gives me the same result.
I found out it is working now so issue closed.

For reference, the problem are the temporary IPv6 addresses and the SLAAC generated addresses from my clients. Those are not resolvable, with my DHCPv6 address is works like it should.
