### ISSUE TITLE
CORS error shown when logging in on installation with non-standard port

### ISSUE THREAD

**Issue by tim-lukacik** [pi-hole/AdminLTE#310]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

**[BUG | ISSUE] Expected Behaviour:**
On successful login I should be redirected to the dashboard.

**[BUG | ISSUE] Actual Behaviour:**
I see an error message - "Failed CORS: http://192.168.1.8:8080 vs http://192.168.1.8, http://192.168.1.8, http://pi.hole, http://localhost"

**[BUG | ISSUE] Steps to reproduce:**

- Install pi-hole with password enabled, change lighttpd port to 8080 (any !80 port)
- Navigate to dashboard and click login and enter credentials
- Error page is displayed. 
- Press browser back button and dashboard is shown and user is successfully logged in.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
This has already been discussed on several platforms and is due to our recent hardening of the security scripts. See [here](https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289/58) for a solution. It will also be fixed by the next update.
