### ISSUE TITLE
Feature Request: Add disk usage to the header

### ISSUE THREAD

**Issue by XaviTorello** [pi-hole/AdminLTE#323]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

8

---
**FEATURE REQUEST**

A Disk usage indicator can be interesting to be integrated inside the header.

The current used percentage for the main partition ("/") and a green/red indicator must be enough to clarify the healthy of the disk.

**Comment by DL6ER** [comment]
Closing this as the PR #324 has also been closed
