### ISSUE TITLE
Feature Request: Adding Filter to taillog

### ISSUE THREAD

**Issue by LarsTi** [pi-hole/AdminLTE#325]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

7{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST]:**

Adding a Filter to the taillog would be quiet easy, Just adding a textbox on top or bottom (or both) of taillog.php and querying this filter by the taillog.js
The advantage would be, that we can track requests by keyword (e.g. the ip of the device getting ads). I am aware that this method wont give you an answer whether the query is also blogged (cause the answer doesn't contain the requesters ip). Nevertheless it would be helpful to reduce the load of messages on larger networks.
Furthermore i know that you can track devices by _queries.php?client=ip_ but this is not live.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Please add your feature request to https://discourse.pi-hole.net so that other users can vote on it. Thanks!
