### ISSUE TITLE
a few design issues/optimizations

### ISSUE THREAD

**Issue by Marcellaoo** [pi-hole/AdminLTE#333]
- [x] left menue: Donate link should open in a new window/tab
- [x] footer: Donate link should open in a new window/tab
- [x] footer: on small devices/browser windows: information " Pi-hole Version v2.11 Web Interface Version v2.3 " is missing
- [x] layer on click pi-hole button: Links "GitHub, Details, Updates" should open in a new window/tab
- [x] layer on click pi-hole button: remove square around logo - not consistent with logo in header, theres no square either
- [x] layer on click pi-hole button: make 23:48 (time information) bold in String "Session is valid for 23:48"
- [x] layer on click pi-hole button: on small devices/browser windows not alignd right (see screenshot1.png)
- [x] on small devices/browser windows: design issue left side (see screenshot1.png)
- [x] on some smaller devices/browser windows: the text is behind the "Log in" Button" (see screenshot2.png and screenshot3.png)
- [x] left menu: menu/site indicator stays on "main page" althoug i am on the login page (see screenshot4.png)

![screenshot1](https://cloud.githubusercontent.com/assets/24915670/21642648/a173177a-d27b-11e6-9af1-7cf86b10afa3.png)
![screenshot2](https://cloud.githubusercontent.com/assets/24915670/21642651/a44b7686-d27b-11e6-8776-03dcc8523800.png)
![screenshot3](https://cloud.githubusercontent.com/assets/24915670/21642652/a667aa52-d27b-11e6-923f-7b02cca3753f.png)
![screenshot4](https://cloud.githubusercontent.com/assets/24915670/21642654/a7f3f01a-d27b-11e6-99ab-9783af46625f.png)

**Comment by Marcellaoo** [comment]
if you want i can complete the review of the existing webinterface. dont know...

**Comment by DL6ER** [comment]
Some of those are already known and will be fixed by the release the is scheduled for today.

**Comment by Mcat12** [comment]
Thanks for this! We'll look through these when we can.

**Comment by Th3M3** [comment]
Actually I am looking how to solve this point:

> footer: on small devices/browser windows: information " Pi-hole Version v2.11 Web Interface Version v2.3 " is missing

Of course, it is possitble to let the version info visible for small screens (e.g. smart phones).
I tried this out and think it would be better to show the version infos in the header's dropdown-menu for small screens instead.
Therefore are changes in `header.php`, `footer.php` & `footer.js` necessary.

Finally it would look like this:
![suppgest1](https://cloud.githubusercontent.com/assets/28313514/26529947/441571ba-43cb-11e7-87da-7988a1f7c239.JPG)

What do the Developers think about it?

**Comment by Mcat12** [comment]
All of the issues have been fixed by the next release.

**Comment by jacobsalmela** [comment]
@Mcat12 can this be closed based on your last comment?

**Comment by jacobsalmela** [comment]
Looks like this is all fixed in v3.2
