### ISSUE TITLE
[Possible Bug] Inaccuracies in Query graphs

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#335]
x-posted from [this reddit post](https://www.reddit.com/r/pihole/comments/5m3con/looks_like_my_pihole_is_doing_good_work/)

**Comment by DL6ER** [comment]
See [this](https://discourse.pi-hole.net/t/queries-over-time-graph-inaccurate/1131) topic on Discourse.

**Comment by DL6ER** [comment]
fixed by Pi-hole Admin Page v2.4
