### ISSUE TITLE
api tailLog not secured

### ISSUE THREAD

**Issue by Links2004** [pi-hole/AdminLTE#360]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---

**[BUG | ISSUE] Expected Behaviour:**

```admin/api.php?tailLog=1``` can not be accessed when not logged in.

**[BUG | ISSUE] Actual Behaviour:**

every user can dump the full log, this can be abused to track what other users are doing.

**[BUG | ISSUE] Steps to reproduce:**

open ```/admin/api.php?tailLog=1```

**Comment by Mcat12** [comment]
Thanks! This will be fixed in the next update.

**Comment by Links2004** [comment]
wow that where fast.
