### ISSUE TITLE
settings.php security vulnerabilities: CSRF and XSS in through $error and $success

### ISSUE THREAD

**Issue by SkyLined** [pi-hole/AdminLTE#365]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1 (first time I looked at it)

---
**VULNERABILITY:**

**Expected Behaviour:**
1) Cross-site requests to change settings using `settings.php` should be prevented using CSRF token.
2) POST data for `settings.php` should not end up in HTML response without HTML entity encoding special characters.

**Actual Behaviour:**
1) There is no CSRF check in `settings.php` or `scripts/pi-hole/php/savesettings.php`, so any website can send fake POST requests to the pi-hole server to change settings without the user's consent. This does require the victim to be logged in to his/her pi-hole server at that time.
2) POST data ends up in HTML response as-is, so any website can make a POST request to the server in a window/iframe and inject arbitrary HTML, including Javascript. Note that executing Javascript is mitigated by CSP.

**Steps to reproduce:**
- Open /admin/settings.php on your pi-hole server.
- Under "API", "Top Domains / Top Advertisers", enter `A<big>B</big><script>alert()</script>`
- Click "Save"

**Suggested fix:**
`/scripts/pi-hole/php/savesettings.php` should encode all special HTML characters in anything it adds to the $success and $error strings, as both are added as-is to the HTML response.

**Notes:**
Your project does not appear to have a way to privately report security issues at this point. It might make sense to set this up so future security issues can be fixed before publicly reporting them.

**Comment by Mcat12** [comment]
Thanks, we're a small team but you can contact us at adblock@pi-hole.net. We'll investigate this issue and hopefully will have a fix very soon!

**Comment by SkyLined** [comment]
Thanks, I understand your situation all to well. I've gone ahead and suggested added the email address to the issue template: https://github.com/pi-hole/AdminLTE/pull/366.

**Comment by DL6ER** [comment]
Another possibility would be to go to our discussion forum [Discourse](https://discourse.pi-hole.net/) and send a private message to one of the developers there. We would take care of broadcasting/redirecting it internally.

Coming back to your issue: Thanks for your report. Fortunately, it is very unlikely that any of the two issues reported by you could cause any harm. While point no. 1 could shuffle around some of the settings it is rather complicated to construct something that uses this. Changing e.g. the API filter settings is not a critical thing but surely we will prevent that from happening. Point no. 2 is completely harmless, but I agree that HTML entity encoding should be added. I will work on that.

**Comment by SkyLined** [comment]
I don't think you should consider XSS harmless: it could allow an attacker to leak the CSRF token and use that to control pretty much everything. Note that CSP as a mitigation against XSS is not bulletproof and that not all browsers support it.

**Comment by Mcat12** [comment]
The only way that the attacker can access the CSRF token or execute those commands is if they're logged in or have stolen the session from a user. By then it doesn't matter if we are using a token or not, because they can parse the page for the CSRF token.
