### ISSUE TITLE
scripts/pi-hole/php/get.php does not check if user is logged in.

### ISSUE THREAD

**Issue by SkyLined** [pi-hole/AdminLTE#367]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1 (first time I look at it)

---
**VULNERABILITY:**

**Expected Behaviour:**
scripts/pi-hole/php/get.php should not provide white-list or black-list if a request is made without authorization.

**Actual Behaviour:**
/admin/scripts/pi-hole/php/get.php?list=(white|black) will return the active white-/blacklist even if the user is not authorized/logged in.

**Steps to reproduce:**
- Log out of your pi-hole.
- Open /admin/scripts/pi-hole/php/get.php?list=white on your pi-hole
- See whitelist
- Open /admin/scripts/pi-hole/php/get.php?list=black on your pi-hole
- See blacklist

**Comment by Mcat12** [comment]
This is intended behavior. Some of the API commands do not require authentication, as they do not leak user privacy or make changes to the system.
