### ISSUE TITLE
"Wrong" entries in blacklist/whitelist can't be removed

### ISSUE THREAD

**Issue by r0ckarong** [pi-hole/AdminLTE#380]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

0

---
**[BUG | ISSUE] Expected Behaviour:**
Entries that are on the black-/whitelist can be removed from the web interface.

**[BUG | ISSUE] Actual Behaviour:**
Certain entries can not be removed because they are no longer accepted or recognized by pihole. They remain on the lists.

**[BUG | ISSUE] Steps to reproduce:**
Add "old accepted format" blocking entry. e.g. "r1---sn-4g5e6nls.gvt1.com" (added via older version of Pihole).
Try to remove string from blacklist via web interface.
The action seems to complete successfully (entry vanishes, modals are updated).
Upon refresh of the page the entry is back.
Still listed in blacklist.txt on the machine itself.

This is a result of and related to #379

**Comment by DL6ER** [comment]
Thanks for your report!
This hast the same origin as the issue you deescribed in #379. I'll therefore close this issue to have a central place for discussions.
