### ISSUE TITLE
Pi-holed (exact) whit green text

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/AdminLTE#381]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

Pi-holed (exact) show as green text on iPad whit Safari browser
Pi-holed (wildcard) does the same green text.

![fullsizerender](https://cloud.githubusercontent.com/assets/72948/22404353/79fb9466-e62f-11e6-8b7f-c23a9c7d0e52.jpg)

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
I cannot reproduce this.
![screenshot at 2017-01-29 14-37-27](https://cloud.githubusercontent.com/assets/16748619/22404400/8c98dba0-e630-11e6-8ac9-1e41f069e6bb.png)

Can you send me a debug token?

**Comment by Tntdruid** [comment]
vxo6c9soku

**Comment by Mcat12** [comment]
Update to the latest version and check if it is still a problem.

**Comment by Tntdruid** [comment]
Gone now no idea why :)

**Comment by Tntdruid** [comment]
Does it too in Google Chrome now

Your debug token is : twv9pgetpz
![2017-01-30_09-41-37](https://cloud.githubusercontent.com/assets/72948/22416699/81391400-e6d0-11e6-9c92-0f0f841ad18a.png)

**Comment by DL6ER** [comment]
Have you checked that you cleared the Browser cache? Especially Chrome is known to cache JS Scripts heavily.

**Comment by Tntdruid** [comment]
Done that so many times now

**Comment by DL6ER** [comment]
Okay, I figured that. If you open the Dev Tools (F12), do you see any errors? You may have to reload the page while having the Dev Tools opened

**Comment by Tntdruid** [comment]
No errors, Text is back to the red color now, no idea why it was green before.

**Comment by DL6ER** [comment]
Then I'll declare that it was a caching issue (that is virtually always the case when it is magically solved at some point).

We all trust that the "Clear Cache" function clears everything, but you never know...
