### ISSUE TITLE
Restore via Pi-hole Teleporter failed

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/AdminLTE#395]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Try to restore via Pi-hole Teleporter fail whit:

The file you are trying to upload is not a .zip file. Please try again.

I use the pi-hole-teleporter.zip from my other pi hole.
**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<gawzorn4h2>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Can you send me the zip file so I can have a look if is maybe corrupted?

Use `<my github user name>@pi-hole.net`

**Comment by Tntdruid** [comment]
Sent

**Comment by DL6ER** [comment]
Have you renamed the file somehow or did you imported it as `pi-hole-teleporter.zip`?

It loads fine on my Pi-hole

**Comment by Tntdruid** [comment]
Changed nothing, only uploaded the pi-hole-teleporter.zip

**Comment by DL6ER** [comment]
The script checks the following two properties:

1. Is the filetype one of
`array('application/zip', 'application/x-zip-compressed', 'multipart/x-zip', 'application/x-compressed');`
2. Is the second part of the string (split at `.`) `zip`

If one of the two fails, then it will error with `The file you are trying to upload is not a .zip file. Please try again.`

**Comment by Tntdruid** [comment]
Still fail whit a clean pi hole install.

**Comment by DL6ER** [comment]
Edit your file `/var/www/html/admin/scripts/pi-hole/php/teleporter.php`:
```
		if(!$continue || !$okay) {
			print_r([$type,$filename,$source,$name]);
			die("The file you are trying to upload is not a .zip file. Please try again.");
		}
```
Please add the new `print_r` statement and tell us what it gives you when you try to import the ZIP file.

**Comment by Tntdruid** [comment]
Array ( [0] => application/octet-stream [1] => pi-hole-teleporter.zip [2] => /tmp/phpMAHZXa [3] => Array ( [0] => pi-hole-teleporter [1] => zip ) ) The file you are trying to upload is not a .zip file. Please try again.

**Comment by DL6ER** [comment]
This explains why it is not working. PHP receives the `zip` file as `application/octet-stream` (instead of `application/zip`) and therefore refuses to process the file as a security measure. Which browser did you use for uploading it? Does it work if you use a different browser?

**Comment by Tntdruid** [comment]
Only have Google Chrome

**Comment by DL6ER** [comment]
Which operating system?

**Comment by Tntdruid** [comment]
Win10 64 bits

**Comment by DL6ER** [comment]
Isn't there an inbuilt browser in Win systems you could use for testing? I will also ask someone of the team with access to a Win machine to try to reproduce your issue.

**Comment by Tntdruid** [comment]
Edge just crash when i open it :)

**Comment by Tntdruid** [comment]
Same whit Firefox

Array ( [0] => application/octet-stream [1] => pi-hole-teleporter.zip [2] => /tmp/phpPtYFek [3] => Array ( [0] => pi-hole-teleporter [1] => zip ) ) The file you are trying to upload is not a .zip file. Please try again.

**Comment by DL6ER** [comment]
Okay, then it is most likely your OS which is to be blame here, since it does not provide the correct MIME type when uploading. Let me think of an alternative implementation for the next release. For now, you should be able to make it working, by removing the `die(...)` line in the portion of the code you modified before.

**Comment by DL6ER** [comment]
I set up a test Pi-hole for you. Please try to upload your file there (see your emails).

**Comment by Tntdruid** [comment]
Works now :)

Array ( [0] => application/octet-stream [1] => pi-hole-teleporter.zip [2] => /tmp/phpyIyVZ9 [3] => Array ( [0] => pi-hole-teleporter [1] => zip ) ) OK

**Comment by Tntdruid** [comment]
@DL6ER 

Same error on the test server

Array ( [0] => application/octet-stream [1] => pi-hole-teleporter.zip [2] => /tmp/phpAoqRq1 [3] => Array ( [0] => pi-hole-teleporter [1] => zip ) ) The file you are trying to upload is not a .zip file. Please try again.

**Comment by DL6ER** [comment]
Okay, Thanks. I will have to modify the validation scheme for the Pi-hole Teleporter.

**Comment by Tntdruid** [comment]
Works whit Firefox

Array ( [0] => [1] => pi-hole-teleporter.zip [2] => /tmp/phpdcWvvG [3] => Array ( [0] => pi-hole-teleporter [1] => zip ) ) OK

Must be Chrome then

**Comment by PromoFaux** [comment]
>Must be Chrome then

What extensions do you have installed?

**Comment by DL6ER** [comment]
STOP!

I already started to code a new scheme on the test server, that is why it is working now.

**Comment by Tntdruid** [comment]
DNSthingy Assistant, Google Publisher Toolbar, Personal Blocklist (by Google), Privacy Badger, Synology Download Station, Synology Note Station
@PromoFaux

**Comment by DL6ER** [comment]
The new validation code is implemented. I will shut down the test server now.

**Comment by Tntdruid** [comment]
You work fast :)
