### ISSUE TITLE
pihole/admin page shows text only

### ISSUE THREAD

**Issue by Mvanmierlo** [pi-hole/AdminLTE#418]
I installed Pihole on my Debian 8.6 (jessie) machine and all is running perfectly.
But after installation I immediately had this issue, which got solved by either a reboot or a repair configuration of Pihole.

But the issue returned due to an forced reboot of the machine and I am not able to solve this issue anymore.
Tried to access the admin page on different machines using different browsers but no change.
I have no errors in in the log files checked these Files :
/var/log/apache2/error.log
/var/log/lighttpd/error.log
 /var/log/pihole.log

I tried the repair option finished without any errors, PiHole is blocking all requests as I expect.

Other issue I've seen that allthough pihole is working, the Pihole -c command shows no stats at all.

I have no clue anymore where to look, how to solve this.

Here my version info : 
:::  Detecting Installed Package Versions:
:::       Pi-hole: v2.12.1
:::       WebUI: v2.4
:::       lighttpd/1.4.35
:::       PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08)
:::       Pi-hole branch:  master
:::       Pi-hole rev:     v2.12.1-0-g5333895
:::       AdminLTE branch: master
:::       AdminLTE rev:    v2.4-0-g406877d

![errorpihole](https://cloud.githubusercontent.com/assets/26039442/23339279/4c5d0296-fc1f-11e6-8e5e-6d0ec78c3c00.JPG)

![image](https://cloud.githubusercontent.com/assets/26039442/23339290/9ed7b854-fc1f-11e6-86b0-0aaf989c0a4c.png)

[pihole_debug.txt](https://github.com/pi-hole/AdminLTE/files/801917/pihole_debug.txt)

**Comment by darkrain-nl** [comment]
Looks to me PHP is not running with the webserver used for PiHole.
Also I see you seem to have 2 webservers running? (Apache and Lighttpd)

**Comment by Mvanmierlo** [comment]
Apache2 is running for sure when I go to the root of my machine I get the apache2 default "it works"  page.
Might have something to do with the installation of [Oscam](http://www.streamboard.tv/oscam/)  I am also running on this box (allthough the admin page for Oscam runs on port 8888 not on 80)

**Comment by darkrain-nl** [comment]
Could it be that PHP is bound to Apache and not Lighttpd as it would be in a normal Pihole installation?
I personally don't have experience with running multiple webservers both with PHP, but I can imagine you need to do some extra configuration to get this working...

**Comment by Mvanmierlo** [comment]
Thank you sir, I did a quick and dirty killal of Apache2 and a  pihole -r which does also a restart of lighthttpd and admin page is showing perfectly now.
Even Oscam is running perfectly so only issue that stand in my way is to disable apache2.

Root cause found, thank you so much pointing me in the right direction !

**Comment by darkrain-nl** [comment]
You're welcome, glad to help.
