### ISSUE TITLE
Typo - There should be a non-breaking space between the numbers and units for temperature

### ISSUE THREAD

**Issue by MattAKAFred** [pi-hole/AdminLTE#422]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---

**[BUG | ISSUE] Expected Behaviour:**
[non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) between temperature value (eg 90) and units (eg °F), read 90 °F, following http://www.bipm.org/en/publications/si-brochure/section5-3-3.html

**[BUG | ISSUE] Actual Behaviour:**
No space. 90°F

**[BUG | ISSUE] Steps to reproduce:**

- Load admin UI with temperature monitor
- Look

Scientist here, sorry about the OCD, just caught my eye. Should be a quick and pain-free fix!

**Comment by DL6ER** [comment]
> non-breaking space between temperature value (eg 90) and units (eg °F), read 90 °F, following ...

i.e. `25&nbsp;&deg;C`

why didn't you propose that in #429 but use an ordinary whitespace there?

**Comment by barisi** [comment]
I've updated the code to have a non-breaking space instead of single whitespace
