### ISSUE TITLE
Wrong sort order on Recent Queries page

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/AdminLTE#425]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Page 1 show from 00:00, page 1318 show the what page 1 should show.

See the screen shots
![page1](https://cloud.githubusercontent.com/assets/72948/23555331/cfd99cd0-0028-11e7-9138-5978c38bf13f.png)

![page1318](https://cloud.githubusercontent.com/assets/72948/23555341/d7e8e1a6-0028-11e7-8804-39d95096a8d1.png)

Pi-hole Version v2.13 Web Interface Version v2.5

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
That might be due to https://github.com/pi-hole/AdminLTE/pull/404. We are currently investigating.

**Comment by DL6ER** [comment]
It may be a bug in DataTables. Previously we had strings like `2017-02-15T21:42:51` which lack whitespace. Now, we corrected the display like `2017-02-15 EST 21:42:51` which causes confusion on the side of DataTables.

**Comment by Tntdruid** [comment]
Sorting is broken too.
