### ISSUE TITLE
Modify dashboard colors to correlate to scheme

### ISSUE THREAD

**Issue by jacobsalmela** [pi-hole/AdminLTE#43]
So it's easier to understand the Queries over time graph, I would like to see the lines and boxes match the colors from the boxes on top of the page.  So the lines should be blue and green (ads blocked and queries)
<img width="744" alt="screen shot 2016-02-22 at 11 10 51 pm" src="https://cloud.githubusercontent.com/assets/3843505/13242457/5f852ae8-d9ba-11e5-93ad-2330479d1915.png">

**Comment by Mcat12** [comment]
We will look into this!

**Comment by jacobsalmela** [comment]
Thanks!
