### ISSUE TITLE
Why is there a padlock in the password field? There probably shouldn't be.

### ISSUE THREAD

**Issue by wjdp** [pi-hole/AdminLTE#442]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
Issue type: Other (Design/UX?)

**[BUG | ISSUE] Expected Behaviour:**

Padlocks are synonymous with SSL/TLS/HTTPS/generally secure things. Placing one in the body of the page is used by many sites (mainly e-commerce) to attempt to raise the user's perception of the site's security. When used on a site that does not employ TLS it's heavily misleading to include a padlock.

_Expected behaviour:_ do not show a padlock on the page, especially when TX/RX over plain HTTP.

**[BUG | ISSUE] Actual Behaviour:**

The password field in the 'log in' dialogue shows a padlock:

![image](https://cloud.githubusercontent.com/assets/1690934/23883804/43cf5a7c-0861-11e7-89db-6b642119e25a.png)

The page has been loaded over plain HTTP. When submitting the form the password is sent in-the-clear:

![image](https://cloud.githubusercontent.com/assets/1690934/23883657/7aa612d0-0860-11e7-93b4-8a35081c36a0.png)

In addition when an incorrect password has been entered a **red padlock** is shown:

![image](https://cloud.githubusercontent.com/assets/1690934/23883854/7e7fdaac-0861-11e7-91a1-7c6128e5a48f.png)

This coloured symbol is used in-browser to represent a broken HTTPS page. Again misleading, just in a different way.

This is software whose users run and maintain themselves. There is no incentive to 'lie' to them about the security of the web interface. Instead be honest about it and let them make informed decisions about how they want to use it.

_Sidenote: I'm sure the intention was not to deceive (again what would be the point?), not raising any accusation. This is just a bugbear of mine._

References (first Google result for "misuse of padlock symbol" 😄): https://www.troyhunt.com/padlock-icon-must-die/

**[BUG | ISSUE] Steps to reproduce:**

Use the login flow.

**Comment by PromoFaux** [comment]
Thanks for the comments! The intention is certainly not meant to decieve :) If you can suggest a better icon to represent 'password' then please do

**Comment by DarkMatterMatt** [comment]
A key?

**Comment by wjdp** [comment]
Think I saw you were using font awesome. The asterisk (fa-asterisk) I would think could work.

Though I would argue that a symbol in this field is unnecessary.
