### ISSUE TITLE
"Queries over time" gap between 16:00 - 18:00?

### ISSUE THREAD

**Issue by jradwan** [pi-hole/AdminLTE#45]
I've been watching my Pi-Hole's admin page for the past few days and it looks like the "Queries over time" pagelet always drops to zero from 16:00 - 18:00 (EST).

I've checked pihole.log and there's definitely activity during that time. It seems strange the graph would drop to 0 between those same times three days in a row.

![image](https://cloud.githubusercontent.com/assets/11047158/13272757/698e309a-da6c-11e5-9c3b-ef3faa17efe2.png)

**Comment by Mcat12** [comment]
Try the installer again. The latest update should fix this. (I had the same issue, #44 fixed it)

**Comment by jradwan** [comment]
I was just coming to report maybe it was GMT-related. When I copied my pihole.log to my other Linux server and used AdminLTE on it, I got a very similar graph, but with the gap shifted about 5 hours (and I'm GMT-5). I'll try the new version and report back, thanks!

![image](https://cloud.githubusercontent.com/assets/11047158/13273675/3f13cc7e-da73-11e5-80da-911108c7d042.png)

**Comment by jradwan** [comment]
Yep, that seems to have fixed it. The "gap" has now shifted between 10pm-ish ahd midnight, which makes sense since that's when everyone in the house has pretty much gone to bed. Then after midnight my backups and such kick off which trigger more DNS activity.

Thanks again!
