### ISSUE TITLE
Typo on default "type" and "version" GET values

### ISSUE THREAD

**Issue by friimaind** [pi-hole/AdminLTE#453]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

5

---
[BUG]:
I think that a NOT (!) is missing on these two conditions:
- https://github.com/pi-hole/AdminLTE/blob/master/api.php#L22
- https://github.com/pi-hole/AdminLTE/blob/master/api.php#L26

[BUG] Expected Behaviour:
the PHP type and version 2 should be the default values if no parameters are passed

[BUG] Actual Behaviour:
the PHP type and version 2 is forced even if there are the GET parameters

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Why should the type and version be included by default? Wouldn't you expect to only get that information if you asked for it? If we invert the current logic, then calling `api.php?version` would not return the version, but `api.php` would.

**Comment by DL6ER** [comment]
I agree with what @Mcat12 said. Reversing the logic doesn't make any sense in this context. Note that both lines you cite will only add parts to the API output. They are not affecting the way in which the API works even a little bit.

**Comment by friimaind** [comment]
Sorry guys, I was thinking that these parameters were used to call the api with a specific version in the future (v1,v2,v3..) and a specific type (php,..).
