### ISSUE TITLE
is_valid_domain_name vulnerable to ReDoS

### ISSUE THREAD

**Issue by koenbuyens** [pi-hole/AdminLTE#464]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

3
---

**[BUG | ISSUE] Expected Behaviour:**
Do not consume a lot of resources when processing a domain name - See https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

**[BUG | ISSUE] Actual Behaviour:**
The pihole consumes a lot of resources when uploading a malicious whitelist file via teleporter.  

**Note**: An attacker can upload a malicious whitelist file via
-  the CSRF vulnerability (https://github.com/pi-hole/AdminLTE/issues/463 )
- modifying the main source of your whitelists/blacklists (i.e. malicious admin or compromised server)

**[BUG | ISSUE] Steps to reproduce:**
- download the attached file redostest.zip and unzip it
- execute `npm install`
- execute `npm start`
- notice that the result, safe regex, returns false; i.e. it is vulenrable to ReDoS

[redostest.zip](https://github.com/pi-hole/AdminLTE/files/888557/redostest.zip)

Alternatively,
- authenticate as an administrator
- upload the attached maliciousconf.zip with malicious via teleporter
- notice that pihole is unresponsive for a while

[maliciousconf.zip](https://github.com/pi-hole/AdminLTE/files/888556/maliciousconf.zip)

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
#463 is fixed in the next release
