### ISSUE TITLE
various pages accessible without being admin

### ISSUE THREAD

**Issue by koenbuyens** [pi-hole/AdminLTE#465]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

3
---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
non-authenticated users should not be able to find ad domain in lists, access debug logs, etc.

**[BUG | ISSUE] Actual Behaviour:**
non-authenticated users can find ad domain in lists, access debug logs, etc

**[BUG | ISSUE] Steps to reproduce:**

- Browse to http://pi.hole/admin/queryads/php Notice that one receives the login screen; i.e. one needs to be authenticated in order to view this page.
![pihole_queryads](https://cloud.githubusercontent.com/assets/17049884/24591386/07a7ac26-17ce-11e7-89b6-f02b232500ca.png)

- Browse to http://pi.hole/admin/scripts/pi-hole/php/queryads.php?domain=google.com and notice that one gets the result.
![pihole_queryads2](https://cloud.githubusercontent.com/assets/17049884/24591385/07a65c40-17ce-11e7-9278-22a5d5c80f5e.png)

- Browse to http://pi.hole/admin/scripts/pi-hole/php/debug.php?upload and notice that on gets debug logs.
![pihole_queryads3](https://cloud.githubusercontent.com/assets/17049884/24591429/fbb27f6c-17ce-11e7-8808-42459eff93c5.png)

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
This intended behavior since the querying for which adlist contains a specific domain is done by the blocking page

**Comment by Mcat12** [comment]
We opened up this function to unauthenticated users because, as mentioned, the block page uses this feature, and currently we don't think it leaks any sensitive information or requires authentication.

**Comment by koenbuyens** [comment]
@DL6ER @Mcat12  what about debug logs?

**Comment by Mcat12** [comment]
Ah, missed that section, sorry. That should be protected.

**Comment by WaLLy3K** [comment]
I think a decent compromise for securing `queryads.php` would be to only allow `localhost` access to it.

**Comment by Mcat12** [comment]
Then the blocking page and web interface (via `pi.hole` or IP) would be unable to use it, if I understand you correctly.
