### ISSUE TITLE
JScript disabled notification prompt.

### ISSUE THREAD

**Issue by Verpz** [pi-hole/AdminLTE#47]
When JS is disabled, the dashboard breaks. I made a project that partially solves this issue.

Thoughts? If you like it, I can commit it in. (I do a lot of web stuff, so I disable my JS a lot for testing and it's really annoying when I load this console wait one minute for nothing to happen and then realise that JS is off.)
Sorry if this comes across as advertising, it's not. I have this on my local version of Pi hole, I'm just seeing if it interests anyone else.
![Pi-Hole Console](http://i.imgur.com/2fd5YTT.png)

**Comment by dschaper** [comment]
I think it looks good, I'm sure the web design folks will comment in a bit, but it's the weekend so they may be not around. Can you PR the code changes?

**Comment by Verpz** [comment]
Sure, have a look at the project here: https://github.com/Verpz/Javascript-Disabled-Warning-Popup

**Comment by dschaper** [comment]
The only thing I can think of off the top of my head would be the issue of adding another CDN into the mix, but that's not something I deal with. (I'm not a full stack developer, still learning front end...) Your issue will get a look over though and we'll let you know. Thanks!

**Comment by Verpz** [comment]
Ok, thanks, still want me to PR?

**Comment by dschaper** [comment]
Yes, please PR...

**Comment by Verpz** [comment]
Just wondering how long on average it takes for a new release of Pi-Hole to come out.

**Comment by PromoFaux** [comment]
The next release will be [soon™](http://wowwiki.wikia.com/wiki/Soon)

In all seriousness, it depends on the amount of activity, and what has been pushed into the development branch. We haven't committed to a regular release schedule, but if there is a release, it's generally on a Sunday.

**Comment by Verpz** [comment]
Okay, thanks :)
