### ISSUE TITLE
system stats incorrect

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/AdminLTE#473]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{6}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
system stats when the dashboard is refreshed be accurate

**[BUG | ISSUE] Actual Behaviour:**
systems stats in particular memory usage are often off by 15%+

**[BUG | ISSUE] Steps to reproduce:**

-view stats on the web GUI
-run `ps -aux`
-compare numbers in terms of memory usage 
-

**(Optional) Debug token generated by `pihole -d`:**

`kjunnco2fe`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
Current web admin stats
` Memory usage:  75.7 %`
current system stats 
approx 60.4%
a few more processes running but nothing using more than 0.5% of RAM

ii do know that stats are not a constantly live update but would have thought they would be a little closer/more accurate

**Comment by Mcat12** [comment]
Perhaps the memory usage jumps to 75.7% while the PHP processes are working on creating the page?

**Comment by technicalpyro** [comment]
doesnt appear so using `watch -d free -m` i have a 512MB VPS and never goes above 330MB in use despite browsing around on the web admin

**Comment by DL6ER** [comment]
Please provide the content of `/proc/meminfo` for further investigation

**Comment by technicalpyro** [comment]
```
technicalpyro@technicalpyro:~$ cat /proc/meminfo
MemTotal:         524288 kB
MemFree:               0 kB
Cached:            39820 kB
Buffers:               0 kB
Active:           186580 kB
Inactive:         262788 kB
Active(anon):     173664 kB
Inactive(anon):   235884 kB
Active(file):      12916 kB
Inactive(file):    26904 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:        524288 kB
SwapFree:         484276 kB
Dirty:                16 kB
Writeback:             0 kB
AnonPages:        409548 kB
Shmem:             75352 kB
Slab:              11408 kB
SReclaimable:       4588 kB
SUnreclaim:         6820 kB

```

with the web admin showing 
` Memory usage:  92.3 %`

**Comment by DL6ER** [comment]
Look at
```
MemFree:               0 kB
```

There is zero free memory!

The dashboard accounts for the fact that `cache` and `buffer` is not really blocked and can be made available if needed, so that value is subtracted:

Cache + Buffer: 39820 kB which is about 7.6 % of your total memory (524288 kB), i.e. 100 % - 7.6% = 92.4% which is almost exactly what the dashboard showed you.

How did you obtain your reading for the total used memory?

**Comment by technicalpyro** [comment]
i used `watch -d free -m` which gives me an updating display refreshing every two second on what is in use or not 
![2017-04-19_12-24-10](https://cloud.githubusercontent.com/assets/24907599/25195537/27c584b2-24fb-11e7-9cb8-6d57a4ba96fd.jpg)

**Comment by DL6ER** [comment]
Here you see that `total = used` and `free = 0` as well, so I don't know where you see the difference. Without buffer and cache you have 46 MB (0f 512 MB) free which is about 9.8% "free" memory left.

**Comment by technicalpyro** [comment]
yeah appears buffers and cache are what is distorting my stats ...

**Comment by DL6ER** [comment]
Your system is anyhow in a very critical state with zero free memory. If you agree, I'd suggest to close this issue, since we have not found something wrong. If you want to have a second look when you have less used memory (maybe restart the machine?) we can also wait.
