### ISSUE TITLE
Alternate case versions of blocked domains listed as "OK" in query log

### ISSUE THREAD

**Issue by G33kDude** [pi-hole/AdminLTE#480]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**
https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/data.php#L416
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

Alternate case versions of blocked domains in the query log would be listed as "Pi-holed".

**[BUG | ISSUE] Actual Behaviour:**

Alternate case versions of blocked domains in the query log are listed "OK" despite really being blocked.

**[BUG | ISSUE] Steps to reproduce:**

Run a DNS query for a domain such as `doubleclick.net`, then run a query for a domain such as `DoubleClick.net`. Both queries return the Pi-Hole's IP address, but in the query log `DoubleClick.net` will show as "OK".

```
G33kDude@localhost ~ $ nslookup doubleclick.net pi.hole
Server:		pi.hole
Address:	192.168.1.2#53

Name:	doubleclick.net
Address: 192.168.1.2

G33kDude@localhost ~ $ nslookup DoubleClick.net pi.hole
Server:		pi.hole
Address:	192.168.1.2#53

Name:	DoubleClick.net
Address: 192.168.1.2
```

![image](https://cloud.githubusercontent.com/assets/437198/25305553/465b1322-274b-11e7-89aa-ab9448584e5a.png)

I think the issue may be caused by the case sensitive array lookup in the [data.php script on line 416](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/data.php#L416). If the `$domain` variable is run through `strtolower` before the lookup, it seems to start working, but there may be other places in the code that this or similar changes need to be made.

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
This appears to be fixed in the next version as FTL handles the case correctly.
