### ISSUE TITLE
Reinstall on Ubuntu 17.04 64bit web interface stucked

### ISSUE THREAD

**Issue by ookangzheng** [pi-hole/AdminLTE#490]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

5
---
<img width="1298" alt="screen shot 2017-05-02 at 14 16 29" src="https://cloud.githubusercontent.com/assets/6301735/25606116/603e13d0-2f42-11e7-9aae-ed8ce2357da3.png">

**Comment by dschaper** [comment]
Is this for the Pi-hole project?

**Comment by ookangzheng** [comment]
Ya lo, once I updated to latest version just now, the web interface couldn't read the log file

**Comment by Mcat12** [comment]
Did you fix the error? If not, run `pihole -d` and share any other info you might have.

**Comment by joepv** [comment]
You have to install the PHP socket extension.
I think in Ubuntu you can add it with the command: `apt-get install php-sockets`
I run a manual install of piHole on openSUSE Leap and after installing the PHP socket extension with the command: `zypper install php7-sockets` it works (after restarting `lighttpd.service`)
