### ISSUE TITLE
not able to update

### ISSUE THREAD

**Issue by nurlennart** [pi-hole/AdminLTE#495]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Webinterface should update

**[BUG | ISSUE] Actual Behaviour:**
Webinterface doesnt update

**[BUG | ISSUE] Steps to reproduce:**

- Update pi-hole
-
-
-
(I dont know if this issue is just for me, or also for everyone else)

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

When I try to update the webinterface, I get the following message and everythings aborts.
`
pi@raspberrypi:~ $ sudo pihole -up
::: Checking for updates...
::: Pi-hole Core:   up to date
::: FTL:            up to date
::: Web Interface:  update available
:::
::: Pi-hole Web Admin files out of date
:::
::: Checking for existing repository...
:::    Updating repo in /var/www/html/admin...*** Error: Could not update local repository. Contact support`

**Comment by PromoFaux** [comment]
Have you made changes to the repo in `/var/www/html/admin`? If so:

`cd /var/www/html/admin`
`sudo git reset --hard`
`sudo git checkout master`

Although we're currently investigating an issue with the version number not showing correctly on `pihole -v`

**Comment by nurlennart** [comment]
If i remember correctly I didnt change anything, I'll try what you suggested though.

**Comment by DL6ER** [comment]
Stop!

**Comment by nurlennart** [comment]
Okay. :D

**Comment by DL6ER** [comment]
See edit above ;-)

**Comment by nurlennart** [comment]
I did what you suggested but it seems like it didn´t change anything, it responded:
```
remote: Counting objects: 118, done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 118 (delta 82), reused 107 (delta 71), pack-reused 0
Receiving objects: 100% (118/118), 84.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (82/82), completed with 41 local objects.
From https://github.com/pi-hole/AdminLTE
 [new tag]         1.2.1-bower -> 1.2.1-bower
 [new tag]         1.3.0      -> 1.3.0
 [new tag]         1.3.1      -> 1.3.1
 [new tag]         v1.2.1     -> v1.2.1
 [tag update]      v3.0.1     -> v3.0.1
```

**Comment by PromoFaux** [comment]
Tell you what. Go nuclear:

```
sudo rm -rf /var/www/html/admin
sudo git clone https://github.com/pi-hole/adminLTE /var/www/html/admin
pihole -up (<- this should tell you you are already up to date)
```

**Comment by DL6ER** [comment]
Okay, very good. Now your repo is up-to-date. Please now try
```
cd /var/www/html/admin
sudo git pull
```

**Comment by PromoFaux** [comment]
Or that ^

**Comment by DL6ER** [comment]
Or nuclear ^^

**Comment by nurlennart** [comment]
I´ll go nuclear, because nuclear sounds cool! 😎

**Comment by nurlennart** [comment]
Nuclear totally worked, thank u very much! 🎉
