### ISSUE TITLE
Hide client hostname

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/AdminLTE#503]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**
Any way to do that now? there was a option in the pre FTL version, gone now.

Looks a bit messy whit  the long ipv6 hostnames.

![chrome_2017-05-11_10-50-33](https://cloud.githubusercontent.com/assets/72948/25941084/75542b4a-3638-11e7-99bb-83e6195f41bb.png)

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
is this something that could be solved using the hosts file?

**Comment by Tntdruid** [comment]
@technicalpyro No idea never done much whit host file

**Comment by technicalpyro** [comment]
`sudo nano /etc/hosts`
using one entry per line use the following syntax:
IP [TAB] hostname

so as an example 
`192.168.1.105 [TAB] Laptop`

once you have added the hosts and ips save the file and restart the device 
then you should see hostnames instead of logn IP's

**Comment by Tntdruid** [comment]
Thats works for the IPv4, IPv6 still show the long name

**Comment by DL6ER** [comment]
Do the same with the IPv6 address :-)

**Comment by technicalpyro** [comment]
could be that you need to know what that long hostname resolves to rather than use the hostname provided via the screenshot

**Comment by Tntdruid** [comment]
@DL6ER Thanks, i just add one for IPv6 i only use that on my lan now :)

**Comment by Tntdruid** [comment]
@technicalpyro my IPS add that name to all IPv6 they use.

**Comment by technicalpyro** [comment]
Ok i think i undertsand however the hosts file is meant to take a IP and turn it into a hostname you can use it in this case by using the IP that the ISP provided hostame refers to to replace their long hostname with your own local copy

**Comment by DL6ER** [comment]
@technicalpyro is right.

Many ISPs do that ... see here (screenshot from my Pi-hole):
![screenshot at 2017-05-23 21-55-25](https://cloud.githubusercontent.com/assets/16748619/26373703/d776622e-4002-11e7-87e2-9e844b8241cc.png)

**Comment by Tntdruid** [comment]
@technicalpyro Works now thanks for the help.
