### ISSUE TITLE
[1.1.3] Bug in query log page

### ISSUE THREAD

**Issue by DonLexos** [pi-hole/AdminLTE#52]
##### Expected Behaviour:
Would expect to see the proper type/domain/client

##### Actual Behaviour:
I see type: `q[32178]` domain `query[A]` and client is `from`

The frontpage does work. Seems something shifted on the query log page.

##### Steps to reproduce this issue:
Running Pi-hole Version v2.5.3 Web Interface Version v1.1.3. Tried `updateDashboard.sh` but that did not fix it, 1.1.3 is really the latest.

**Comment by Mcat12** [comment]
This should be fixed in the latest devel branch. (Just fixed yesterday)

**Comment by Mcat12** [comment]
It seems that something moved the log entries right one. We should really change from hardcoded indexes though.

**Comment by DonLexos** [comment]
Oh ok I checked the wiki and it's not in there I believe.

**Comment by DonLexos** [comment]
But good to know, no clue how to label things (or even know if I am allowed to) but otherwise someone might be able to label in-next-release or something.

**Comment by Mcat12** [comment]
Ya, with how fast everything is going, the changelog gets behind sometimes.

**Comment by DonLexos** [comment]
Found it! No clue how I can link directly to a commit but it's this one [#ddb2aa3](https://github.com/pi-hole/AdminLTE/commit/ddb2aa346d52768d5c367367e0e6bca4b50211d6)

**Comment by Mcat12** [comment]
I don't think you need the #

**Comment by PromoFaux** [comment]
Ah, OK, I just posted a picture in slack with this same thing. :) had an email question about it too. Any chance of pushing the fix to master? Might confuse some users. Otherwise. 

Strip the password stuff out of devel first though.

**Comment by DonLexos** [comment]
I made the link manually since I was unable to find out how. If I do a # I get link options to issues, no clue how you link to commits easily. it's in this pull request #51

**Comment by Mcat12** [comment]
I'll work on sending to master.

**Comment by Mcat12** [comment]
Released

**Comment by DonLexos** [comment]
Great! Thanks!
