### ISSUE TITLE
Dashboard doesnt show stats - browser console has exceptions

### ISSUE THREAD

**Issue by gnfpt** [pi-hole/AdminLTE#523]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
Not familiar
_1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Show the graphs in the dashboard.

**[BUG | ISSUE] Actual Behaviour:**
objectToArray http://192.168.2.241/admin/scripts/pi-hole/js/index.js:17:16
	updateForwardedOverTime/< http://192.168.2.241/admin/scripts/pi-hole/js/index.js:158:26
	j http://192.168.2.241/admin/scripts/vendor/jquery.min.js:2:26920
	fireWith http://192.168.2.241/admin/scripts/vendor/jquery.min.js:2:27738
	x http://192.168.2.241/admin/scripts/vendor/jquery.min.js:4:11251
	b/< http://192.168.2.241/admin/scripts/vendor/jquery.min.js:4:14765

**[BUG | ISSUE] Steps to reproduce:**
Running: Pi-hole Version v3.0.1 Web Interface Version v3.0.1 FTL Version v2.8
Open the PiHole dashboad and the browser developer tools. 
Check the console output.

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Run `pihole -d` for a debug token. Perhaps taking a screenshot of the error would be better?

**Comment by gnfpt** [comment]
Re: [pi-hole/AdminLTE] Dashboard doesnt show stats - browser console has exceptions (#523)






Run pihole -d for a debug token. Perhaps taking a screenshot of the error would be better?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




I've fixed this for a day deleting the log files on my RPI. The next day the issue was back - no stats - and the errors on the console.










-- 
Best regards,
Goncalo Farias

(D)inner not ready:  (A)bort (R)etry (P)izza.
<mid:pi-hole/AdminLTE/issues/523/307663456@github.com>

**Comment by jacobsalmela** [comment]
@gnfpt it appears all of your screenshots show zero queries.  Do you have clients set up to [use Pi-hole as their DNS server](https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245)?  Without any queries, there is nothing to graph.

**Comment by gnfpt** [comment]
If aí recall correctly I had bind installed alongside  with dnsmasq. So it was a matter of which one started 1st. Nevertheless, the console exhibit some js errors that should be polished.

**Comment by jacobsalmela** [comment]
Well if bind was installed, that would cause issues with DNS resolution.

@Mcat12 will you check out the JS errors?

**Comment by Mcat12** [comment]
There should always be at least an empty array returned for those API calls, unless you are not authenticated:
https://github.com/pi-hole/AdminLTE/blob/master/api_FTL.php#L245
https://github.com/pi-hole/AdminLTE/blob/master/api_FTL.php#L284

**Comment by jacobsalmela** [comment]
So the errors something we need to look into?

**Comment by Mcat12** [comment]
I'll have to look into it more next week, but it seems that it is an edge case.

**Comment by jacobsalmela** [comment]
OK thanks.

**Comment by Mcat12** [comment]
I'm unable to replicate this or find a reason it should do this. If it happens again, take a screenshot of the requests that trigger the errors (under the "Network" tab).

**Comment by gnfpt** [comment]
Can you try with an empty dns log file? 

-- 
~/gnf

**Comment by Mcat12** [comment]
I haven't been able to reproduce these errors with an empty log.

**Comment by gnfpt** [comment]
Re: [pi-hole/AdminLTE] Dashboard doesnt show stats - browser console has exceptions (#523)






There should always be at least an empty array returned for those API calls, unless you are not authenticated:
https://github.com/pi-hole/AdminLTE/blob/master/api_FTL.php#L245
https://github.com/pi-hole/AdminLTE/blob/master/api_FTL.php#L284
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



PS: I wasn't authenticated.

-- 
Best regards,
Goncalo Farias

Typos? Blame my cat.
<mid:pi-hole/AdminLTE/issues/523/313780389@github.com>

**Comment by gnfpt** [comment]
Re: [pi-hole/AdminLTE] Dashboard doesnt show stats - browser console has exceptions (#523)






I haven't been able to reproduce these errors with an empty log.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



I don't know if it matters but I believe I wasn't authenticated when it happened.

-- 
Best regards,
Goncalo Farias

"Is it winter yet?" - Zippy
<mid:pi-hole/AdminLTE/issues/523/318239856@github.com>

**Comment by Mcat12** [comment]
>There should always be at least an empty array returned for those API calls, unless you are not authenticated:
> https://github.com/pi-hole/AdminLTE/blob/master/api_FTL.php#L245
> https://github.com/pi-hole/AdminLTE/blob/master/api_FTL.php#L284

If you aren't authenticated, then the API won't try to return any data. However, the summary API calls refresh your session, so you shouldn't have this problem anyways.
