### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/AdminLTE#539]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
The admin page keep time out whit:

ERR_CONNECTION_TIMED_OUT

```
pi@raspberrypi:~ $ service lighttpd status
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: active (running) since Sat 2017-07-01 21:10:17 CEST; 5min ago
  Process: 722 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 802 (lighttpd)
   CGroup: /system.slice/lighttpd.service
           ├─802 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─812 /usr/bin/php-cgi
           ├─830 /usr/bin/php-cgi
           ├─831 /usr/bin/php-cgi
           ├─832 /usr/bin/php-cgi
           └─833 /usr/bin/php-cgi
```
sudo service lighttpd restart does not help, reboot the pi fix the problem for like 2 min.

DNS works normal.

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`v7abg1hx3u`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
This error shows up a ton in your log:
```
2017-07-01 21:13:16: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  fopen(/var/log/pihole.log): failed to open stream: Permission denied in /var/www/html/admin/scripts/pi-hole/php/tailLog.php on line 21
```

What are the permissions on `/var/log/pihole.log`?

**Comment by Tntdruid** [comment]
was owned by root, had to do sudo rm /var/log.pihole.log the pihole -r, the repair did not fix it first time.

**Comment by Mcat12** [comment]
So are you still having the issue?

**Comment by Tntdruid** [comment]
Looks lile the problem is gone now, been running all night now.

**Comment by Tntdruid** [comment]
Looks like ERR_CONNECTION_TIMED_OUT is back again.

**Comment by Mcat12** [comment]
Does it time out every way you access it? IPv4 address, hostname, `pi.hole`, etc

**Comment by Tntdruid** [comment]
Both ip and the pi.hole, going to reinstall the os and pi hole
