### ISSUE TITLE
bad check for success when adding domain to blacklist/whitelist

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/AdminLTE#540]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_5_

---
**[BUG] Expected Behaviour:**
When adding a Domain to the Blacklist or Whitelist, the green Success-Message should come up when adding the domain was really successfully.

**[BUG] Actual Behaviour:**
In `list.js`, the response from `add.php` gets checked.
If it not contains `not a valid argument` or `is not a valid domain`, the Success-Message will be shown.

But if the session is timed out, the response is `Wrong token.`. Because the response gets not checked to that string, the user falsely gets the green Success-Message Box.

For sure, it would work to change line 146/147 in `list.js` to something like
`if ( RegExp("not a valid|wrong token", "i").test(response) ) {`
but I think this is not the ideal way. It would be better to really check for the success response.

Actually, the response is 
<code>  [✓] test.com is a valid domain name!</code> when adding to Blacklist was successfully 
and
<code>  [✓] Pi-hole blocking is Enabled</code> when adding to Whitelist was successfully.
So maybe there should be a similar (and for whitelist a more expressive) respone to be easily able to do the check for success or failure.

Eventually this can be included when fixing https://github.com/pi-hole/pi-hole/issues/1548....

**[BUG] Steps to reproduce:**

- try to add `valid.com` to Blacklist/Whitelist
- try to add `invalid%.com` to Blacklist/Whitelist
- try to add a valid or invalid Domain if session is timed out (or logged out in another Browser's Tab)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
I was on vacation when this was posted, but I will look into it soon!
