### ISSUE TITLE
How about popup notifications?

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/AdminLTE#546]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_5_

---
**[FEATURE REQUEST | QUESTION]:**

How about using popup notifications instead of bootstrap's message boxes?

Especially when backlisting or whitelisting from the Query Log Page, it would be a benefit because these popups always stay fixed on top.

I made some tests with [this js script](https://github.com/mouse0270/bootstrap-notify) and my own css stylesheet.

Something like this:
![notify](https://user-images.githubusercontent.com/28313514/28037687-83260974-65bc-11e7-8cb4-4addcac981d2.gif)

Maybe this could be a feature in one of the next milestones....

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Not a fan of pop ups myself, I wouldn't really want that myself.

**Comment by dschaper** [comment]
Looks cool, but I'd rather have something like hovers over the buttons that show what they are going to do after like a 4 second delay of hover. Maybe that would be better to explain what the buttons all do instead of giving status updates?

**Comment by PromoFaux** [comment]
How about a modal dialog?

**Comment by Mcat12** [comment]
I do like how it doesn't move the page around and how it doesn't get hidden if you scroll away. However, maybe we should also look at adding some icons/indicators around the button area that would do the same thing but be less intrusive and more intuitive? I'm thinking something like a spinning icon for in progress and a temporary checkmark for success.

**Comment by Th3M3** [comment]
@PromoFaux @Mcat12 
This working demo is using a vertically centered modal dialog:
![addtolist](https://user-images.githubusercontent.com/28313514/31628293-8fc039d4-b2b0-11e7-8fe2-e2261ddd0a4e.gif)

**Comment by PromoFaux** [comment]
I like this... Draft up a PR and we can take a closer look! (Probably a few other places around the dashboard that would benefit from this kind of dialog.)

**Comment by Mcat12** [comment]
Added in v3.3
