### ISSUE TITLE
Modularize the admin interface

### ISSUE THREAD

**Issue by Firesphere** [pi-hole/AdminLTE#549]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [ ] The issue I am reporting can be *replicated* _Not really applicable_
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

8
---
**OTHER:**

I have been trying to rewrite the current admin interface, to a modular (pluginable) system. However, this poses the issue of increased memory-usage.

Although it's doubling the memory usage, it's still well within the realms of possibilities, even on a Pi Zero W (which is a Pi Zero, but with wifi)

My approach was using a SQLite database to store the dashboard configuration, and render things more modular (including the option to render using javascript, thus not actively leaving the page when changing to e.g. `Settings` )

Right now, I only have the main Dashboard moduralized to a certain degree, where I just read the SQLite database which determines which graphs/blocks to show and in what order.

This was a one-day-play and far from done, let alone perfect. If you are interested, I'm willing to extend this to making it a full modular overhaul of the dashboard, reducing duplicate code and make it more pluggable (e.g. easily add the speedtest thingy from Reddit)

**Comment by PromoFaux** [comment]
Hey there, sounds great but I'd hold off for a bit if I were you. The admin interface is currently undergoing a bit of an overhaul behind the scenes.. though nothing to show just yet. 

Obviously increased memory usage is no good thing, and we have to be careful that we don't start creeping into the area of adding features that are not really needed for/related to a DNS server. 

That said, we're always interested to see what the community comes up with, so if you can happily take criticism, and don't mind the possibility that your code will be rejected, go ahead and make the pull request!

**Comment by Firesphere** [comment]
No worries, it's just a "one-day fun project" for me so far, just to see what I could do with it.

And yes, of course, I'm used to working on OSS stuff, from rejecting to accepting, to reject-and-take-parts-of-the-PR (and of course give attribution where needed)

At my current job, we have a hackday this friday. I'll take that opportunity to have my employer pay indirectly to me doing my thoughts on what could be improved in a comprehensible package, and you can pick and/or choose what you like about it :)

**Comment by PromoFaux** [comment]
>I'll take that opportunity to have my employer pay indirectly to me doing my thoughts on what could be improved

Excellent way of looking at things :)

**Comment by raid5** [comment]
@PromoFaux I wouldn't mind beta testing the admin UI overhaul when you think it's in a good place!

**Comment by PromoFaux** [comment]
It's a while from public consumption right now, but once it's into `devel` you will be able to try it out using the `pihole checkout web devel` command (or `pihole checkout dev` to test the whole dev version, but bear in mind that that can be VERY BROKEN at any time... with no liability for your cat being killed etc)

**Comment by versavius** [comment]
Is the current Pi-Hole interface the new one? It just could be interesting to have a modular interface ?

**Comment by PromoFaux** [comment]
Not yet, keep an eye on https://github.com/pi-hole/web

**Comment by Mcat12** [comment]
This can be reopened on the new web interface repo, but for now we do not plan to do this for the current PHP web interface.
