### ISSUE TITLE
Division by zero in /var/www/html/admin/data.php on line 17

### ISSUE THREAD

**Issue by eko3alpha** [pi-hole/AdminLTE#55]
##### Expected Behaviour:
Detect if $dns_queries_today is 0 to prevent an error

##### Actual Behaviour:
Division by zero in /var/www/html/admin/data.php on line 17 error and execution stops

##### Steps to reproduce this issue:
Either check if the divisor is 0 or add a very small number ( a / (b + .0000000001)) to prevent this error

**Comment by PromoFaux** [comment]
Ah-hah! This explains a few things...

`api.php` used to just pull the output of `chronometer.sh -j` (in which the divide by zero error was fixed)

Since the introduction of all the lovely graphs, the calculations were moved into `data.php`, but it looks like the fix wasn't ported across.. good catch! Thanks

**Comment by eko3alpha** [comment]
I was actually troubleshooting the panel itself.  The charts were spinning and I didn't see any issues in any of the XHR requests.  Looking through the php logs I found the error, I fixed it locally on my server...  

However the root of the problem was that  dnsmasq failed to start when I rebooted my server.  Im using Ubuntu and not a pi.

Maybe as a future enhancement have the system make sure all necessary services are running?  It would be cool to see an alert warning you that dnsmasq is not running.

I just installed this a few days ago and have yet to play with it.  So far I'm pretty impressed!  Great work!

**Comment by PromoFaux** [comment]
Ah, yeah the Ubuntu thing is a known issue [link 1](https://www.reddit.com/r/pihole/comments/44z1b9/how_to_make_pihole_start_automatically_when_i/czvege9) [link 2](https://github.com/pi-hole/pi-hole/issues/358)

There is a workaround in the above two links, but it's something we're looking into!

**Comment by Mcat12** [comment]
Can you make a pull request with your fix, or just post it here and we'll look at it?

**Comment by PromoFaux** [comment]
This should do it, right?

```php
		if ($dns_queries_today != 0) {
					$ads_percentage_today = $ads_blocked_today / $dns_queries_today * 100; 	
				}
				else {
				 	$ads_percentage_today = 0;
				};
```

**Comment by eko3alpha** [comment]
There are about 3 ways you could do it, I ended up doing...
```
$ads_percentage_today = $dns_queries_today ? ($ads_blocked_today / $dns_queries_today * 100) : 0;

**Comment by PromoFaux** [comment]
Or a fancy one liner :)

**Comment by Mcat12** [comment]
It's a common one line if statement. Java has it too. :)
