### ISSUE TITLE
Graph gets interpolated if there are no queries over a long time (screenshot inside)

### ISSUE THREAD

**Issue by maciboy** [pi-hole/AdminLTE#562]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-holeπ-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I’m reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---

**[BUG | ISSUE] Expected Behaviour:**
Between 2:30am and 9:30am there were no DNS queries, so the graphs should be set to 0 in this interval.

**[BUG | ISSUE] Actual Behaviour:**
For the timespan 2:30-2:39am there are 6 queries. Until the timespan 9:30-9:39am there were no queries, so there are no markers set in the graph. The next marker is correctly set to 56 queries at 9:30am.
However, the graph in this interval with no queries is not set to 0, instead the markers of the 2 timespans with queries are connected and the graph between gets interpolated.
This behavior creates the impression as if there were an increasing number of queries over night, although there no queries at all.

**[BUG | ISSUE] Steps to reproduce:**

- do not generate DNS queries for a longer timespan (~hours) e.g. over night
- go to the pi hole dashboard
- you will see in the graphs that the those point in time where queries were present get connected by an interpolated graph.

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

![bildschirmfoto 2017-08-06 um 16 43 50](https://user-images.githubusercontent.com/19333006/29004535-3637a45c-7ac9-11e7-9d8a-47363cf8db81.png)

**Comment by Mcat12** [comment]
Was the Pi-hole on and working (but no queries) or turned off?

**Comment by maciboy** [comment]
Pi-hole was running. There simply was no device in the network with an active internet connection since all of them were either off or in flight mode, so there were no queries.

**Comment by Mcat12** [comment]
We're working on a fix for the next release of FTL. The issue was that the graph was not getting any information about the time without queries, so it assumed that it should interpolate between those points. FTL will now explicitly tell the graph that there were no queries in that time block.

**Comment by maciboy** [comment]
Thank you so much for this very quick fix!
And of course for this great piece of software all in all!
I was using OpenDNS with some filters before, but this is soo much better :)

**Comment by jacobsalmela** [comment]
Fixed in v3.2
