### ISSUE TITLE
Top Lists does not resolve VPN host names

### ISSUE THREAD

**Issue by DL6ER** [pi-hole/AdminLTE#569]
**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

## 10

---

**[BUG | ISSUE] Expected Behaviour:**

Top Lists shows host names also for devices connected via OpenVPN

**[BUG | ISSUE] Actual Behaviour:**

Top Lists shows only IP addresses for VPN devices but no host names

**[BUG | ISSUE] Steps to reproduce:**

- Connect a device via VPN
- Make some queries

**[BUG | ISSUE] Reason why this is happening:**

`dnsmasq` is not able to reverse lookup VPN IPs, hence `FTL` cannot obtain the corresponding host names

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by jacobsalmela** [comment]
Fixed in v3.2
