### ISSUE TITLE
Add administrative contact address functionality

### ISSUE THREAD

**Issue by WaLLy3K** [pi-hole/AdminLTE#579]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**FEATURE REQUEST:**

[Core PR #1691](https://github.com/pi-hole/pi-hole/pull/1691) introduces functionality which allows admins to specify the email address they can be contacted at on the Block Page and we should also have this functionality within Web Admin. I propose an input underneath "Web User Interface" on the settings page, above the existing two options to tie into `pihole -a email`.

**Comment by kkirsche** [comment]
PR submitted

**Comment by jacobsalmela** [comment]
in v4.0
