### ISSUE TITLE
Query Log Page providing incorrect data

### ISSUE THREAD

**Issue by zeryl** [pi-hole/AdminLTE#61]
##### Expected Behaviour:
Type, domain and client are populated properly

##### Actual Behaviour:
Type shows the domain name (truncated to domain - 1 char), domain shows "from", client is blank

##### Steps to reproduce this issue:
View the query log page

I know that a recent issue was completed to correct something similar, but I am on Web Interface Version 1.1.5, Ubuntu 14.04 LTS, and dnsmasq 2.68

The pi-hole log has the following as a line:

Mar 12 12:10:07 dnsmasq[31352]: reply mqtt.c10r.facebook.com is 31.13.66.3

Perhaps it's a dnsmasq config issue, and I know this isn't on a PI, but for how useful this program is, I tried it anyway.  Everything else is working perfectly!

**Comment by ShoGinn** [comment]
Reddit had a fix for this: 
https://www.reddit.com/r/pihole/comments/49t4hp/query_log_not_being_parsed_correctly/

**Comment by zeryl** [comment]
Yea, I just fixed it the same way.  Looks like https://github.com/pi-hole/AdminLTE/commit/725d0de52af7fcbc159afebcd86fc8d6a8a75a3c broke it, but also "fixed" another issue with it (basically, what I'm seeing).  Odd.

**Comment by ShoGinn** [comment]
I rooted it out to the same https://github.com/pi-hole/AdminLTE/commit/725d0de52af7fcbc159afebcd86fc8d6a8a75a3c fix and could not find out what it actually "fixed"

**Comment by Mcat12** [comment]
#62 Is currently being reviewed before it's merged. If you want to try it out to see if it actually fixes this issue, run `cd /var/www/html/admin` then `git fetch --all` and finally `git checkout fixQueryLog`.

**Comment by ShoGinn** [comment]
Works perfect on my ProxMox VM - Debian 8 etc..

Not sure what data you need, love the change that has the color coding.

**Comment by looterz** [comment]
#62 Fixed it for me, Debian 8.3

**Comment by ndbeals** [comment]
#62 Also fixed it for me, Ubuntu 15.10.
