### ISSUE TITLE
Graph showing wrong date?

### ISSUE THREAD

**Issue by divadsn** [pi-hole/AdminLTE#625]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

6

---
**Expected behaviour:**

I am expecting a graph showing data between 0:00 and 23:59 from 7th of December.

**Actual behaviour:**

![grafik](https://user-images.githubusercontent.com/28547847/33725712-38b14da4-db73-11e7-8182-bacb9fd57093.png)

**Steps to reproduce:**

Update Pi-hole from the previous version using `pihole -up`.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`mr999iaktt`

**Comment by Mcat12** [comment]
I see a similar issue, though for me it's only an off-by-one error on the month.
![screenshot from 2017-12-08 17-00-43](https://user-images.githubusercontent.com/4417660/33787058-949d22d4-dc39-11e7-823c-12daec34baca.png)

**Comment by DL6ER** [comment]
Hmm, this seems to work as expected for me.

![untitled123123](https://user-images.githubusercontent.com/16748619/33788586-71023622-dc73-11e7-9577-0385c16941e0.png)
(it is correct that there was no Internet activity from 10:00 - 17:00)

**Comment by Mcat12** [comment]
@DL6ER Note the month - 11 instead of 12

**Comment by DL6ER** [comment]
Closing as this got fixed in Pi-hole v3.2.1
