### ISSUE TITLE
New interface pulls FTL commit not version number

### ISSUE THREAD

**Issue by xSmick** [pi-hole/AdminLTE#626]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
![1](https://user-images.githubusercontent.com/34348810/33729611-30d0ce74-db4c-11e7-8269-d25c6bc8304c.PNG)

**Actual behaviour:**
![2](https://user-images.githubusercontent.com/34348810/33729612-30e106d6-db4c-11e7-92a1-1372c6b89079.PNG)

![3](https://user-images.githubusercontent.com/34348810/33729613-30ee620e-db4c-11e7-82e9-b6e549322aa6.PNG)

**Steps to reproduce:**
Upgrade to latest version by using 
`sudo pihole -up`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

pjhks98hyw

**Troubleshooting undertaken, and/or other relevant information:**
None

**Comment by Mcat12** [comment]
This is a slight cosmetic issue we're working on. It's actually an issue in the pi-hole/FTL repo, because Travis CI did not build the release in the way we were expecting. It checked out the commit in detached-HEAD mode instead of staying on the master branch.

**Comment by xSmick** [comment]
Gotcha. Feel free to close this unless you want the visual reminder.

**Comment by C4Wiz** [comment]
Still not fixed in the latest release

<img width="517" alt="screen shot 2017-12-23 at 8 23 33 am" src="https://user-images.githubusercontent.com/3883521/34320582-bfaaed1c-e7ba-11e7-8821-ee06483dbbbf.png">

**Comment by DL6ER** [comment]
In fact this is a new issue but only on the dashboard. See #652
