### ISSUE TITLE
Domains in Query Log no longer selectable since v3.2

### ISSUE THREAD

**Issue by steffanson** [pi-hole/AdminLTE#632]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
3

---
****Steps to reproduce and expected behaviour:**

Go the Query Log page and try to select a domain. Then it should be possible to copy (and paste) it. (via ctrl+c/v). 

**Actual behaviour:**

It is not possible to select the domain text. The selection vanishes immediately and the the domain list is filtered.

**Steps to reproduce:**

 I guess it no longer works as the domain fields are now clickable. It could be resolved by adding a "filter button" next to the domain instead.

**Comment by DL6ER** [comment]
I'm not sure how the best solution would look like. More buttons (you can also filter by Type and Client) doesn't seem like an optimal solution. I tried to detect if the user has selected text on `mouseup`, but that doesn't work reliably across browsers. Maybe a checkbox on the QueryLog page like "filter queries on click" that is enabled by default could help?

**Comment by steffanson** [comment]
>  Maybe a checkbox on the QueryLog page like "filter queries on click" that is enabled by default could help?

That wouid probably be the easiest solution. Unless someone else comes up with something better, I'm for it! Thanks. :-)

**Comment by ZeroTester** [comment]
Hi, sorry to jump in.
The checkbox works great, but its state is reversed to *checked* on every page load. It might help the user if that state were remembered.
Also, and this is only cosmetic, the pointer should change on hovering, in order to visually indicate whether the table cell is a clickable button or a selectable text. Tooltip and text decoration should also change accordingly.

**Comment by Mcat12** [comment]
@ZeroTester Please make a new issue for those other requests. Or, make a feature request on Discourse.
