### ISSUE TITLE
Doughnut chart too small

### ISSUE THREAD

**Issue by steffanson** [pi-hole/AdminLTE#635]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behaviour:**

![graphic2](https://user-images.githubusercontent.com/17642285/33805695-604c2e6e-ddbd-11e7-92a0-b1f33a71e2cc.png)

**Actual behaviour:**

![graphic](https://user-images.githubusercontent.com/17642285/33805697-62c721bc-ddbd-11e7-950f-9514c51be951.png)

**Steps to reproduce:**

As soon as there are too many destinations (two columns) the chart becomes too small or vanishes completely. I use a resolution of 1680x1050. I use PiHole 3.2

**Comment by DL6ER** [comment]
A kind of workaround would be to make their canvas greater to have the two additional forward destinations fit in there. However, this will again fail if you add yet another two forward destinations.

We haven't expected that users push things to this level of extreme...

The proper solution would likely be to either
- remove the legend altogether (show the forward destination only on hover)
- limit the legend to at may one column (I don't know of that can be done easily)

Asking @pi-hole/approvers regarding their opinions.

**Comment by Mcat12** [comment]
Removing the legend (only on hover) sounds fine. Or, if possible make the legend vertically scrollable.

**Comment by steffanson** [comment]
> if possible make the legend vertically scrollable.

I think this would be a reasonable solution.

**Comment by wilgert** [comment]
This insight might be useful when fixing this issue: https://stackoverflow.com/questions/43229626/how-to-fix-chart-legends-width-height-with-overflow-scroll-in-chartjs
