### ISSUE TITLE
PHP Warning when using the audit page

### ISSUE THREAD

**Issue by KN4CK3R** [pi-hole/AdminLTE#642]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

After clicking on "Audit" on the `auditlog.php` page no php warning gets generated.

**Actual behaviour:**

After clicking on "Audit" on the `auditlog.php` page the following php warnings get generated:
```
PHP Warning:  preg_split(): Delimiter must not be alphanumeric or backslash in /var/www/html/admin/scripts/pi-hole/php/auth.php on line 122
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/admin/scripts/pi-hole/php/auth.php on line 123
```

**Steps to reproduce:**

Click on "Audit" on the `auditlog.php` page.

**Problem:**
The current code looks like `$domains = preg_split('\s+', $_POST['domain']);`. The delimiter is missing for the pattern. I don't know whats the preferred delimiter but `'~\s+~'` fixes the problem.

**Comment by dschaper** [comment]
Fixed in #682
