### ISSUE TITLE
FTLs version is displayed as vDev on master

### ISSUE THREAD

**Issue by DL6ER** [pi-hole/AdminLTE#652]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

## 10

---
**Expected behaviour:**

`FTL`'s version should be shown like this on the dashboard:
![screenshot at 2017-12-23 00-39-30](https://user-images.githubusercontent.com/16748619/34314931-c21003e4-e779-11e7-8cf5-b2d2b68c0c7e.png)

**Actual behaviour:**

`FTL`'s version should is shown like this on the dashboard:
![screenshot at 2017-12-23 00-31-10](https://user-images.githubusercontent.com/16748619/34314935-c94e7e7e-e779-11e7-9779-3d124114e00e.png)

**Steps to reproduce:**

Update to Pi-hole v3.2.1

**Comment by bcutter** [comment]
Seems like FTL version showed is going even more crazy from update to update, currently:

 **Pi-hole Version v3.2.1 Web Interface Version v3.2.1 FTL Version vDev (v2.13.2 , v2.13.2 )**

**Comment by DL6ER** [comment]
@bcutter This is an issue in the dashboard. `FTL` cannot prevent it from happening regardless of how often it gets updated :-)

**Comment by bcutter** [comment]
OK so tell me whom to tell about this so it get fixed. Main app?

**Comment by Mcat12** [comment]
It is already fixed in development.

**Comment by bcutter** [comment]
Ah OK so I guess I/we just need to wait. THX for the update!

**Comment by dschaper** [comment]
Fixed in #682
