### ISSUE TITLE
Currently active DHCP lease mac addresses are all in caps

### ISSUE THREAD

**Issue by stosoorok** [pi-hole/AdminLTE#658]
DHCP lease mac addresses are always all in caps and when adding these to static list it won't work. If adding mac address manually to /etc/dnsmasq.d/04-pihole-static-dhcp.conf everything works great.

**Comment by DL6ER** [comment]
**You must follow the template instructions. Failure to do so will result in your issue being closed.**

I'm sorry but everyone has to play according to the same rules. 

Please also give some more insight in a new issue what you mean exactly by
> and when adding these to static list **it won't work**

**Comment by stosoorok** [comment]
If you add dhcp leases to static list, there are all addresses in caps even if your mac is not. It's a bug, try it!

**Comment by dschaper** [comment]
MAC's are not case sensitive, they are hex encoded, doesn't matter.

**Comment by stosoorok** [comment]
I have many device's on my network and none get static ip if added via Admin GUI. If I add manually in terminal with small fonts then it gets the specified ip.

**Comment by DL6ER** [comment]
**You still have missed to fill out the issue template.**

Can you confirm that it **does not work** if you add them manually in the terminal in caps?

**Comment by dschaper** [comment]
https://superuser.com/questions/547591/ifconfig-who-decided-that-mac-address-should-be-lowercase 

As a certified network engineer I can tell you that the issue is somewhere else. MAC addresses are not case sensitive.

**Comment by stosoorok** [comment]
@DL6ER Yes it does not work if I add same addres in upper case!

New filled template: https://github.com/pi-hole/AdminLTE/issues/665
_
Sorry for this one, this is my first. :)
