### ISSUE TITLE
Currently active DHCP lease mac addresses are all in upper case

### ISSUE THREAD

**Issue by stosoorok** [pi-hole/AdminLTE#665]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I want to add static ip-s to my devices via admin panel

**Actual behaviour:**

All active dhcp leases show mac addresses in upper case but on my device (Raspberry pi3) ifconfig show lower case mac addresses. If I add addresses from active leases button on admin panel my devices won't get specified ip addresses. If I add mac address in lower case manually in terminal /etc/dnsmasq.d/04-pihole-static-dhcp.conf the device gets specified ip address.

**Steps to reproduce:**

Find device where ifconfig shows mac address in lower case. Try to add your device to static dhcp list from admin panel and then check your device ip what address did it get.

**Comment by dschaper** [comment]
What is the MAC listed for `arping -c1 <ip-address>`?

**Comment by stosoorok** [comment]
```
pi@pihole:~ $ sudo arping -I eth0 -c 1 192.168.1.30
ARPING 192.168.1.30
60 bytes from b8:27:eb:66:39:bb (192.168.1.30): index=1 time=3.019 msec
```

**Comment by dschaper** [comment]
And what does your arp cache look like, `arp -a`

**Comment by dschaper** [comment]
Try setting the MAC to uppercase, run a `ping -b 192.168.1.255` and then check your arp cache and see if there are any devices that do not have an IP address.

**Comment by stosoorok** [comment]
```
pi@pihole:~ $ arp -a
? (192.168.1.2) at ec:b1:d7:64:fd:44 [ether] on eth0
android-1345096aea4bc9.local (192.168.1.149) at 10:4f:a8:00:af:c2 [ether] on eth0
? (192.168.1.1) at 1c:87:2c:67:c0:00 [ether] on eth0
playertest.local (192.168.1.45) at b8:27:eb:66:39:bb [ether] on eth0

```
Playertest.local is now inserted with uppercase and works fine. 
/etc/dnsmasq.d/04-pihole-static-dhcp.conf
dhcp-host=B8:27:EB:66:39:BB,192.168.1.45,playertest

```
pi@pihole:~ $ ping 192.168.1.45
PING 192.168.1.45 (192.168.1.45) 56(84) bytes of data.
64 bytes from 192.168.1.45: icmp_seq=1 ttl=64 time=0.610 ms
64 bytes from 192.168.1.45: icmp_seq=2 ttl=64 time=0.594 ms

```

I deleted arp cache, maybe this was it? I'll try with other devices too.

**Comment by dschaper** [comment]
It's possible to have a bad arp cache, it should time out but the cache is local to the machine. A bad cache on a local box shouldn't prevent another machine from getting assignments. But let us know if the issue persists.

**Comment by stosoorok** [comment]
I have tried with many different devices and no problem anymore. Bad arp cache was the problem. Everything works great, thanks!
