### ISSUE TITLE
query log unresponsive

### ISSUE THREAD

**Issue by DL6ER** [pi-hole/AdminLTE#672]
@technicalpyro commented on [Thu Jan 18 2018](https://github.com/pi-hole/FTL/issues/207)

**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{3}_

---

**[BUG | ISSUE] Expected Behaviour:**
ability to view all queries in the query log when selected

**[BUG | ISSUE] Actual Behaviour:**
when clicking the all queries (instead of queries for the last 10 minutes) the web interface freezes

**[BUG | ISSUE] Steps to reproduce:**

-go to query log
-filter if you wish
-select the link at the top to view all rather than just the last 10 minutes
-

**Log file output [if available]**

` kqwkw2i045`

**Device specifics**

Hardware Type: rPi2B
OS: Raspbian stretch

i believe this to be an FTL error as it would seem to me to be the page hangs while trying to load the data my other thought is it is an admin interface issue but unsure f which 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

---

@DL6ER commented on [Thu Jan 18 2018](https://github.com/pi-hole/FTL/issues/207#issuecomment-358693474)

Thank you for your report. However, this is no `FTL` issue but rather an issue with the web interface.

Proof: Open your browser and log into your Pi-hole dashboard. Open a new tab and browse to http://pi.hole/admin/api.php?getAllQueries
The fact that the page successfully loads means that both `FTL` as well as the PHP API are working as expected:
![screenshot_v](https://user-images.githubusercontent.com/16748619/35107245-bcce6ec8-fc70-11e7-8834-1d7d1d8a7209.png)

However, if the very same data is queried from the Query Log page, the request does never finish:
![screenshot_q](https://user-images.githubusercontent.com/16748619/35107270-cd82b896-fc70-11e7-9cf6-66bf6bc088c4.png)

What is interesting is that one CPU core will jump to 100% and will stay there for about one minute.
![screenshot_c](https://user-images.githubusercontent.com/16748619/35107566-94c4d3da-fc71-11e7-8907-581eb8f1d8ae.png)
Note that the delay may be more or less depending on your CPU performance and number of queries in the log. After this period of extensive CPU usage, the Query Log works as expected and does show all data as expected:
![screenshotgg](https://user-images.githubusercontent.com/16748619/35107607-b424a78c-fc71-11e7-8f02-b890f8cff122.png)

**Comment by technicalpyro** [comment]
thanks for moving this @DL6ER 
![2018-01-18_10-09-17](https://user-images.githubusercontent.com/24907599/35107886-b684edaa-fc37-11e7-9755-46cb0ff43728.jpg)

the image shows what i think may be the issue the api call is taking a lot more resourses than it should ?? I'm not really one hundred percent sure what I'm looking at here

**Comment by DL6ER** [comment]
I ran a performance study and it seems like that most of the time is spend in `QuickSort`. I'm quite sure that it worked fine only a few days ago and we haven't released any updates for this page since longer.

![screenshot at 2018-01-18 17-19-21](https://user-images.githubusercontent.com/16748619/35108454-e76e51c2-fc73-11e7-8dbe-77e4e2de4fac.png)

**Comment by technicalpyro** [comment]
i have noticed this happening for a little while but was out of town on business so i couldn't say exactly how long its been happening resurfaced for me today when trying to do some traffic analytics

**Comment by DL6ER** [comment]
Another performance measurement, another (as in completely different) result...

![screenshot at 2018-01-18 17-27-38](https://user-images.githubusercontent.com/16748619/35108848-ed0e5054-fc74-11e7-9c00-4ba012cb0204.png)

**Comment by Mcat12** [comment]
Seems to work OK on Firefox. On Chrome, it was hitting the CPU so hard I couldn't get any performance data off of it. 😕

**Comment by technicalpyro** [comment]
personally i see similar behaviour regardless of which browser i use.  have tested the following:
Chrome
Firefox unresponsive then get this error 
```
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://pi.hole/admin/scripts/vendor/jquery.min.js:2
```
Waterfox
TOR browser

i know all but one of those is a firefox derivative however it is what is installed on my system at the moment 

i will note firefox does seem to handle it better but still not ideal

**Comment by DL6ER** [comment]
Confirmed that it is still working fine (`all` takes about 1.5s to load) for this version with Firefox
![screenshot at 2018-01-21 11-31-17](https://user-images.githubusercontent.com/16748619/35193125-af8c0880-fe9e-11e7-8db7-afd9c64fef2d.png)

Compare this to 15 seconds with `Vivaldi` (based on Chromium)
![screenshot at 2018-01-21 11-33-52](https://user-images.githubusercontent.com/16748619/35193144-f7e070ee-fe9e-11e7-9694-f43686b6bbac.png)

and 7 seconds with `Chrome Version 56.0.2924.87 (64-bit)`

This is for @5,000 queries within `FTL`'s scope and with having everything running (except the browsers, of course) on a Raspberry Pi 3.

**Comment by anudeepND** [comment]
I have this similar issues with the latest version of Pi-Hole, the query log page becomes unresponsive having selected only 100 domains per page.

![screenshot_20180121-165906](https://user-images.githubusercontent.com/26179946/35193715-dcc55cb0-fecc-11e7-9285-5d5b0feddcc4.png)

**Comment by technicalpyro** [comment]
@Mcat12  @DL6ER  is this something that would be solved by the new web interface potentially?

**Comment by Mcat12** [comment]
Potentially. It depends on how the table library works.

**Comment by Mcat12** [comment]
But, we are looking into server-side pagination, so it would load pages quicker.

**Comment by technicalpyro** [comment]
i have switched to firefox from chrome.  for a multitude of reasons but it does work.  

This makes me feel that it is a browser issue more than a pihole issue but i dont know the code or optimization well enough to say that 100%

**Comment by stordoff** [comment]
Commenting to note that this appears to be Chrome specific (or at least worse there). For me, Chrome hangs for seems like a indefinite period (>30s - long enough for Chrome to give the "Page not responding" warning, and for me to take to loading up another browser instead). Both Firefox (Quantum) and Microsoft Edge load the same page in 5-10s.

**Comment by rscoleNZ** [comment]
Just to add my 2c, I also see this issue on Chrome. Version 63.0.3239.132. I must admit, I have seen it intermittently for around 2 weeks now. And in that time I have rebuilt the pi for unrelated reasons. As mentioned above, MS Edge does eventually load the page, but Chrome never does. I am only seeing this on the one client, which happens to be a smart TV with around 27,000 requests, mostly to Netflix follows by Sony. Chrome causes my cpu to run at 100% according to the W10 task manager, MS Edge only makes it peak around 30% if I am reading it correctly.

Pi-hole Version v3.3 Web Interface Version v3.3 FTL Version v3.0 
Chrome. Version 63.0.3239.132
Microsoft Edge 41.16299.15.0
OS Windows 10

**Comment by DL6ER** [comment]
Closing this as it is not a Pi-hole related issue. It is more a general issue with DataTables and Chromium based browsers. It works absolutely fine with other products such as, e.g. Mozilla's Firefox.
I'd like to stress that this issue appeared out of nowhere as the corresponding scripts in the Query Log have not been altered in months when this issue first came up (shortly after the announcement of the Spectre and Meltdown patches, beginning of 2018).

**Comment by wkearney99** [comment]
I don't know that I'd close it quite so quick.  It'd be better to have a little more insight as to why it's happening.  

That and does it really pull a request for ALL records?  Yikes, on mine that returns 7,683,927 bytes of data for 97,850 records.

**Comment by DL6ER** [comment]
This is a browser related issue and, unfortunately, we have no insight into why it is happening. The only thing we know is that it happens for Chrome and all of its spin-offs and that it happens on all operating systems.

Also, 7 megabytes of data should not be an issue in your internal network, right? But that is also the reason for we load only the data of the most recent 10 minutes by default. The future API that is currently under development will handle server-side pagination and as such will only send small chunks.

**Comment by jjssoftware** [comment]
I'm sure this won't help because what I'm about say is already known:

I see this phenomenon on Chromium Version 64.0.3282.140 (Official Build) Built on Ubuntu, running on LinuxMint 18.3 (64-bit)

I agree with the analysis performed by @DL6ER above, it's hanging around doing a lot of work in the sort / quicksort area.

I know that this is not a newly introduced problem, I've been seeing this behavior for a while on pihole 3.2.1 and also 3.3 now. That would mean it's been present in at least Chromium builds through 61 <-> 64

It's easy to trigger this using the steps to reproduce mentioned above.

**Comment by guilhermeoc97** [comment]
I was able to reproduce the issue with Edge and IE on my local server. Wouldn't implementing Server-side processing with DataTables solve this, since you wouldn't fetch every single query log entry and would just fetch the amount that the user wanted to see.
