### ISSUE TITLE
Audit log should be split between allowed queries and blocked queries

### ISSUE THREAD

**Issue by ail1020** [pi-hole/AdminLTE#677]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

When I audit a blocked query, I'd expect it to show up again in allowed queries if in the future it isn't being blocking any longer.

**Actual behaviour:**

If I audit a blocked query and later it starts being allowed (because it was removed from a blocklist) I don't get a chance to audit it in allowed queries.

**Steps to reproduce:**

Create a custom blocklist and add it to the blocklists in pi-hole (or just blacklist it) and update gravity.
Hit the domain and be blocked
Audit the blocked domain in the audit log.
Remove the domain from the blocklist and update gravity.
Hit the domain and be forwarded.
Check audit log for allowed query.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A - auditlog shares same file if audited under allowed queries or blocked queries.

**Troubleshooting undertaken, and/or other relevant information:**

Submit this issue in case it's a quick fix for someone familiar with the code. Will try understanding code later to do a pull request if not.

**Comment by fredericdepuydt** [comment]
Just noticed this problem today as I added some domains to my personal blacklist that I already audited before.

**Comment by ail1020** [comment]
I looked at the fix for this a while ago and it looks like it spreads across multiple github projects in order to have a separate audit log for both allowed and blocked domains. Plus we'd have to decide how to handle the already audited domains in everyone's list. With the new interface and FTL to come out, it's probably best to wait for that at this point. Currently, I only audit the allowed list and anything I want to blacklist I open in the query log to blacklist so it doesn't audit.
