### ISSUE TITLE
Fill Dashboard stats without JavaScript

### ISSUE THREAD

**Issue by bugreport0** [pi-hole/AdminLTE#678]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`8`

---
**Expected behaviour:**

`(Static) Dashboard summary statistics should be visible while browsing with JavaScript disabled.`

**Actual behaviour:**

`Dashboard summary statistics are initially shown as '---' while browsing with JavaScript disabled.`

**Steps to reproduce:**

`Disable JavaScript in your browser and navigate to the Pi-hole Dashboard (v3.2.1).`

**Troubleshooting undertaken, and/or other relevant information:**

`Looking at 'index.php' and 'index.js' we can statically populate / initialize the statistics by either calling the Pi-hole JSON API from 'index.php' (not preferred) or directly getting the stats (preferred) and setting up the H3.statistic tag contents. `

**Comment by Mcat12** [comment]
JavaScript is a requirement of the web interface. Please make an exception for sites such as the web interface when you want to use them.
