### ISSUE TITLE
Settings > DNS > Custom 1 (IPv4) - displaying custom host#port incorrectly

### ISSUE THREAD

**Issue by mhorne484** [pi-hole/AdminLTE#680]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

When using a custom host#ip combination in setupVars.conf -> /etc/dnsmasq.d/01-pihole.conf the web UI should display the port correctly.
`127.0.0.1#54`

**Actual behaviour:**

Input mask is affecting display of custom port

![screenshot from 2018-02-04 10-33-10](https://user-images.githubusercontent.com/12196996/35776561-d5968aa2-0996-11e8-929d-f27de7b3edde.png)

**Steps to reproduce:**

Enter a custom port into setupVars.conf when installing pihole
`PIHOLE_DNS_1=127.0.0.1#54`
View the settings page
http://pihole/admin/settings.php?tab=dns

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not required.

**Troubleshooting undertaken, and/or other relevant information:**

Located the custom input mask in `scripts/vendor/jquery.inputmask.extensions.js:27-59`. Appears the mask is only used in settings.php so updating the mask to allow port definitions should be possible without affecting other parts of the UI.

**Comment by DL6ER** [comment]
We might just get rid of `jquery.inputmask.extensions.js`, it also caused problems with IPv6 and I think I removed it there already.

**Comment by Toakan** [comment]
Removing it just removes the IP validation. There is still an underlying problem where it does not recognise port seperation (#,:,;)

![image](https://user-images.githubusercontent.com/7566941/36096939-72122e68-0ff0-11e8-8bb3-361f8717dbd8.png)

**Comment by DL6ER** [comment]
Okay, so it fails at [this](https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/php/savesettings.php#L184-L199) validation that check for if the entered custom addresses are valid. We'd have to add another validation function for this kind of option (maybe `validateIPwithPort()`).

**Comment by Toakan** [comment]
You'd want to write it to accept either null port definition or with a port defined. 

Guess this wouldn't be too bad if you defaulted it to 53 when left empty and you could include it into the first function listed rather than create a new function?

`for($i=1;$i<=4;$i++)
{
        if(array_key_exists("custom".$i,$_POST))
        {
        $IP = $_POST["custom".$i."val"];
                if(validIP($IP) OR !preg_match('(\b(?:\d{1,3}\.){3}\d{1,3}\b)([?#][0-9]{1,4})',$IP))
                        {
                                array_push($DNSservers,$IP);
                        }
                        else
                        {
                        $error .= "IP (".htmlspecialchars($IP).") is invalid!<br>";
                        }
        }
}
`
Using the above I have it working on my test pi with the JS mentioned prior commented out.

**Comment by Toakan** [comment]
See below for working.

![image](https://user-images.githubusercontent.com/7566941/36107846-37e3cdb4-1013-11e8-8122-4b1e0844f76c.png)

Again for not.

![image](https://user-images.githubusercontent.com/7566941/36107882-52a3325c-1013-11e8-9c59-78b925924708.png)

It is worth noting that using an incorrect seperator "~" actually wipes out all other DNS entries.
Trhowin

**Comment by bjoe2k4** [comment]
Any update on this? This problem basically hits everyone trying to use DoT, DoH or dnscrypt.

**Comment by bjoe2k4** [comment]
@DL6ER Thanks! But why the need for an additional field? Why not just use the above four fields with port in # syntax?

**Comment by DL6ER** [comment]
@bjoe2k4 because `#` is a comment in bash (and we store the parameters in a file that is interpreted by bash) and hence everything after it (the port) would just get ignored. I don't really want to add support for back and forth translation...

**Comment by bjoe2k4** [comment]
@DL6ER  Are you sure? I'm having `PIHOLE_DNS_1=127.0.0.7#5353` in `setupVars.conf` and it seems to work just fine (except for the web gui).

```
#!/bin/bash

t=127.0.0.1#5353
echo $t
t=127.0.0.1 #5353
echo $t
```

```
~$ bash comment.bash
127.0.0.1#5353
127.0.0.1
```

**Comment by DL6ER** [comment]
Oh, you're probably right. I started to work on this at some point and never finished the dashboard changes. I will revisit this when I find the time.

**Comment by Sk1pp3r** [comment]
Well, I have the latest version, and I still have this issue; not being able to set the port, the UI doesn't allow that, and when I try to set the custom DNS with port during installation, it says it's invalid.

![issue](https://user-images.githubusercontent.com/2412881/41005002-3fd5ec36-690b-11e8-9b23-1098219a6a9b.png)

**Comment by Mcat12** [comment]
You are on v3.3.1, not the FTLDNS beta.

**Comment by klara31** [comment]
When will this feature be promoted to production?

**Comment by Toakan** [comment]
@klara31 Not until the FTLDNS beta is concluded.

If you want to implement it yourself now, you can use the code from https://github.com/pi-hole/AdminLTE/issues/680#issuecomment-364960494 to add it yourself.

**Comment by adamgoldberg** [comment]
Can anyone post or point me to a patch that implements the code described in "#680 (comment)" directly above?

**Comment by oldjamey** [comment]
@adamgoldberg Take a [look at this article](https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0) about setting up dnscrypt-proxy.  It won't show up in the GUI, but it works.  Look at the part about "If you are running an older version of pi-hole" or something along those lines.  Those are the files and params you need to edit in order to achieve what you are wanting, if I am not mistaken.
