### ISSUE TITLE
DHCP and Random MAC + no Access for not in the Mac List

### ISSUE THREAD

**Issue by bobybobybob** [pi-hole/AdminLTE#685]
I have read and understood the contributors guide.  ==> no because my mother language is not english and understand most not. Maybe you can make netherland translation. 
    The issue I am reporting can be replicated.  ==>  yes
    The issue I am reporting isn't a duplicate (see FAQs, closed issues, and open issues).   => you know it better. look like i am first with that problem

**How familiar are you with the the source code relevant to this issue?:**
1 

---
**Expected behaviour:**
Some Internet Device have option for random MAC and fill up the DHCP Database. It would be nice for some rule like if Hostname = blabla then set DHCP IP in pool 192.168.2. 50-60   
or
in other case  if match MAC  12:00:3F:XX:XX  where XX is random

and what would also great, never give a IP is not in known MAC List and only show a Page like "Haha you see nothing - phone the admin if you like internet"

**Actual behaviour:**
Random MAC User are new user in Database and fill it up

**Steps to reproduce:**
use a freeware tool to generate random MAC Adress for your networkcard

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-
dont know

**Troubleshooting undertaken, and/or other relevant information:**
no solution, better DHCP Server is need

**Comment by dschaper** [comment]
What would stop a client from setting their own hostname and stealing the IP address of another device? 

The way DHCP works, it's expected that you have some control over the clients that are attached to you LAN. DHCP isn't smart enough to know what MACs are good and which ones are not, it just knows the pool of IPs to hand out and which network segment to apply them to. It may be possible to only hand out to a whitelist of known MAC addresses, but matching on random MACs is not something I think is possible.

**Comment by dschaper** [comment]
Possible:
```
dhcp-host=11:22:33:44:55:66,set:known 
dhcp-ignore=tag:!known
```

**Comment by bobybobybob** [comment]
> What would stop a client from setting their own hostname and stealing the IP address of another device?

I only can speek to own that one have a Samsung Galaxy 8 Smartphone or Tablett and everytime it connect to WLAN, it connect with new random MAC. I dont know who is that Person but i see that hostsame still the same. 

Set the DHCP Hold Time low will help not overflow but it will be a problem in big enviroment with many many people

**Comment by Mcat12** [comment]
Why do the devices create new MAC addresses? The issue really lies with those devices not using a singluar MAC address, because that is required for DHCP to work as intended.
