### ISSUE TITLE
Query log not working

### ISSUE THREAD

**Issue by hoshsadiq** [pi-hole/AdminLTE#691]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Query log shows results

**Actual behaviour:**

Query log stuck on `Processing`

**Steps to reproduce:**

Open `Query Log`

**Troubleshooting undertaken, and/or other relevant information:**

Seems to throw an error in Chrome developer tools console

```
Uncaught TypeError: Cannot set property 'nTf' of undefined
    at kb (jquery.dataTables.min.js:27)
    at ga (jquery.dataTables.min.js:48)
    at HTMLTableElement.<anonymous> (jquery.dataTables.min.js:93)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at n.fn.init.m [as dataTable] (jquery.dataTables.min.js:82)
    at n.fn.init.h.fn.DataTable (jquery.dataTables.min.js:166)
    at HTMLDocument.<anonymous> (queries.js:128)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
kb @ jquery.dataTables.min.js:27
ga @ jquery.dataTables.min.js:48
(anonymous) @ jquery.dataTables.min.js:93
each @ jquery.min.js:2
each @ jquery.min.js:2
m @ jquery.dataTables.min.js:82
h.fn.DataTable @ jquery.dataTables.min.js:166
(anonymous) @ queries.js:128
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
I @ jquery.min.js:2
```

![image](https://user-images.githubusercontent.com/600045/36497508-6f66652c-1733-11e8-9627-d36472736497.png)

**Comment by DL6ER** [comment]
Does it still appear after a force refresh (`Ctrl + F5`)?
Look also at the `Network` tab, is the request answered in correct JSON format?

**Comment by hoshsadiq** [comment]
Damn! This is my bad. I should have known this. Thanks!
