### ISSUE TITLE
After an update DNS didn't restart.

### ISSUE THREAD

**Issue by pconnell99** [pi-hole/AdminLTE#702]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Pi-Hole to work after an update.`

**Actual behaviour:**

`DNS Server cannot be started.  Restarting it returns an error on a line in 01-pihole.conf.`

**Steps to reproduce:**

`Add line 'log-queries=extra' to conf.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`7144ukcu8a`

**Troubleshooting undertaken, and/or other relevant information:**

I did an update to the PI after web interface notified me.  I did the standard `pihole -up` but it partially errored.  Probably a few updates have passed me by.  Noticed blocking didn't work and query log was empty after update (still is).

Commented out line in conf file after `journalctl -xn` reported the line dnsmasq was having issues with.

Sorry, I don't remember what version I was on previously.

**Comment by PromoFaux** [comment]
https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159

**Comment by Mcat12** [comment]
https://discourse.pi-hole.net/t/why-cant-i-run-pi-hole-v3-3-on-raspbian-jessie-or-with-dnsmasq-v2-72/8052
