### ISSUE TITLE
Feature Request: Add Cloudflare free DNS 1.1.1.1 to Settings>DNS.

### ISSUE THREAD

**Issue by ramubhai** [pi-hole/AdminLTE#707]
Cloudflare just announced a new free public DNS service. It has quite low latency from all over the world. 

IP Address: 1.1.1.1, 1.0.0.1

Announcement link: https://blog.cloudflare.com/announcing-1111/

Detailed discussion on hacker news: https://news.ycombinator.com/item?id=16727869

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/pi-hole/pull/2073
