### ISSUE TITLE
Add Cloudfare DNS Server

### ISSUE THREAD

**Issue by jonasdroste** [pi-hole/AdminLTE#714]
Hi!

Cloudfare started their DNS server listening at 1.1.1.1 and 1.0.0.1.
Would be nice to add them.

https://github.com/pi-hole/AdminLTE/blob/e48aa295bd993a4a82bdabeb12a73e3123fc1559/scripts/pi-hole/php/savesettings.php#L119

Regards

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

> - [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

https://github.com/pi-hole/AdminLTE/issues/707
