### ISSUE TITLE
Add FreeDNS DNS Server

### ISSUE THREAD

**Issue by versavius** [pi-hole/AdminLTE#716]
Free DNS's DNS Server has No DNS redirects. No Logging so good for those using Pi-Hole for privacy concerns.

https://freedns.zone/en/

IPv4:

37.235.1.174
37.235.1.177

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
