### ISSUE TITLE
Block Lists - Groups & Time Settings

### ISSUE THREAD

**Issue by versavius** [pi-hole/AdminLTE#717]
For the Block Lists it would be useful to have a set of Default Groups such as:

Adverts
Gambling
Malware
Phishing
Porn
Ransomware
Trackers

Or at least let us create the categories.

The reason would be if we assigned multiple lists to groups we could turn them on/off all in one go.

In addition if we could set certain block lists by time, so say if you have a business environment and you want to block all social media sites/streaming sites outside of lunch (12.00 - 14.00) then you could, it would allow some environments to auto-turn on block lists during peak work times.

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/AdminLTE/blob/master/.github/ISSUE_TEMPLATE.md)

Paying particular attention to this section of the template:
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
