### ISSUE TITLE
Stats - Data Saved (Blocked)

### ISSUE THREAD

**Issue by versavius** [pi-hole/AdminLTE#718]
At present you just present stats on the number of queries allowed / blocked, have you thought about recording the data which has been blocked and add that in the dashboard?

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
