### ISSUE TITLE
Ignore DNS lookups for "localhost" in statistics and graphs

### ISSUE THREAD

**Issue by NyxCode** [pi-hole/AdminLTE#719]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [**x**] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [**x**] The issue I am reporting can be *replicated*.
- [**x**] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`3`

---
**Expected behaviour:**
The graphs and staticstics on the pi-hole webinterface are supposed to show the user how effective pi-hole and the used lists are

**Actual behaviour:**
When a server does **not only** runs pi-hole and a local proxy is used `(*e.g to have multiple services available at the same port but different domain*) the stats and graphs on the webinterface are basically useless because they show ever DNS-lookup for "localhost" (*as long as the OS does not use a DNS-cache*)

**Steps to reproduce:**
1. Install pi-hole
2. Send many DNS-requests for "localhost" to pi-hole, e.g by accessing a local webserver

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`5spakjdh28`

**Troubleshooting undertaken, and/or other relevant information:**
[image](https://imgur.com/a/V6KkL)

**Comment by DL6ER** [comment]
I think this is on the edge of being a feature request and not a real issue report, but since it is arguably on the edge, we can leave it here and open. We will discuss this internally. So far, I guess, we just haven't encountered such a scenario and first have to discuss what we want to do within the team. Stay tuned.

**Comment by DL6ER** [comment]
In https://github.com/pi-hole/FTL/pull/254 I propose a solution for this by adding a config flag for FTL that will tell the daemon to ignore all queries coming from `localhost`.

**Comment by DL6ER** [comment]
This has been implemented in the FTLDNS beta testing phase. You might want to try it out.

**Comment by Toakan** [comment]
@DL6ER I've just found another use case for this where it potentially loses tracking information.

DNS1 = Any Domain service, ie WinDNS / DHCP
DNS2 = PiHole.

If you set DNS1 to forward to DNS2, the stat graph on PiHole shows all requests coming from DNS1 IP rather than the originator.

**Comment by DL6ER** [comment]
I'm not sure what you mean as DNS1 will not be `localhost`

**Comment by jacobsalmela** [comment]
This config flag is now available as an option in v4.0.
