### ISSUE TITLE
Summary stats are incorrect?

### ISSUE THREAD

**Issue by 00firestar00** [pi-hole/AdminLTE#72]
##### Expected Behaviour:
Well, I see 1 of 2 things being wrong. Either the returned stats from the API are incorrect, or the title of the summary stats should be changed from "Ads Blocked Today" to "Ads Blocked To Date" 

##### Actual Behaviour:
Currently the PHP code parses the entire pihole.log file, and returns stats on all queries in there. Now, my log file isn't set reset/rotated nightly, meaning that the queries in there are from when I started up the server. (this in itself is a bad idea as you will soon get file sizes that are just unmanageable)

Also, I noticed the "Queries over time" graph seemed a bit weird for not resetting every day, but I also kinda like seeing the trend of my internet traffic based on time of day.

##### Suggestion:
One idea would be to rotate the logs nightly (which would be a change to the main repo), and then we wouldn't have to worry about parsing large files and could separate out all-time stats from daily stats.

**Comment by manuelgu** [comment]
> Now, my log file isn't set reset/rotated nightly

It should though. There is a cronjob running which flushes your log every night.
the [flush](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/piholeLogFlush.sh) happens [every night](https://github.com/pi-hole/pi-hole/blob/master/advanced/pihole.cron#L26)

**Comment by 00firestar00** [comment]
I thought i might have been overlooking something, though it looks like v2.6 or v2.6.1 didn't copy the crons over (if they are suppose to) . I will have to look into this later, though I would rather rotate the log instead of flushing it

**Comment by 00firestar00** [comment]
Ah crap, it's a late here, and should have checked the main repo first.  This is a duplicate of https://github.com/pi-hole/pi-hole/issues/434
I just need to rerun the install script.
