### ISSUE TITLE
Top Lists of clients shows IP addresses, but dashboard shows client names 

### ISSUE THREAD

**Issue by ksylvan** [pi-hole/AdminLTE#723]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Long Term Data -> Top Lists should show client names like the Dashboard view does.

**Actual behaviour:**

Dashboard view shows names for clients (set up in /etc/hosts) but the Top Clients list only shows IP addresses. 

**Steps to reproduce:**

1. Add client names to /etc/hosts
2. Browse the web for a while
3. Visit your dashboard.
4. Now look at Long Term Data -> Top Lists and examine the Top Clients list

**Troubleshooting undertaken, and/or other relevant information:**

None.

**Comment by Mcat12** [comment]
Have you tested this on the development version? It should be implemented there.

**Comment by ksylvan** [comment]
No, I have not. I'm running this on a physical Raspberry Pi at home and while at work, on my laptop running as a docker container using this image here: https://github.com/diginc/docker-pi-hole

**Comment by Mcat12** [comment]
This is actually expected. The long term data only contains IP addresses, not hostname information, for space reasons. Even though we know the IP address, we can't reliably get the hostname because the IP address of the device may have changed, and we would be showing incorrect data. So that is why they remain IP addresses instead of hostnames.
