### ISSUE TITLE
Pihole installing unneeded PHP version 

### ISSUE THREAD

**Issue by JPaulMora** [pi-hole/AdminLTE#725]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

 `pihole -up` should NOT install php5 when php7 is already installed

**Actual behaviour:**

`pihole -up` always reinstalls php5

**Steps to reproduce:**

install php7 like so in Raspbian jessie
from 
```
deb http://repozytorium.mati75.eu/raspbian jessie-backports main contrib non-free
#deb-src http://repozytorium.mati75.eu/raspbian jessie-backports main contrib non-free
```
after that, update pi-hole.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Not Applicable 

**Troubleshooting undertaken, and/or other relevant information:**

Post this lol

**Comment by PromoFaux** [comment]
Issue moved to [pi-hole/pi-hole #2117](https://github.com/pi-hole/pi-hole/issues/2117) via [**ZenHub**](https://www.zenhub.com/)
