### ISSUE TITLE
getAllQueries falls over when gravity.list contains large number of domains

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#73]
Continuation of [#465](https://github.com/pi-hole/pi-hole/issues/465) on the main pi-hole repo.

**Comment by PromoFaux** [comment]
@windyo
@CDeeRon
@7h3ju57 

I've only gone and done it. 

Can one of you test this for me please?

```
cd /var/www/html/admin
sudo git fetch
sudo git checkout BugFix73
```

to revert, `sudo git checkout master`

**Comment by CDeeRON** [comment]
I had to `git reset --hard` since I was playing around with data.php

Fixes work for me

**Comment by PromoFaux** [comment]
ah yes! Should have mentioned that.

But super, glad that works. We'll try and push it to release tonight, I think there are a couple of other minor bugs to sort out, too.

**Comment by CDeeRON** [comment]
I see below error in `/var/log/lighttpd/error.log`

`2016-04-15 16:21:19: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Notice:  Undefined variable: status in /var/www/html/admin/data.php on line 138`

`            if ( $status != ""){
              array_push($allQueries['data'], array(
                $time->format('Y-m-d\TH:i:s'),
                $type,
                $domain,
                $client,
                $status,
              ));
              $status = "";
            }`

**Comment by PromoFaux** [comment]
OK, should have that sorted... update and try again...

**Comment by CDeeRON** [comment]
Updated and tested with no errors, both the `admin/api.php?getAllQueries` and `/admin/queries.php`

**Comment by Windyo** [comment]
Was away from the computer, sorry. Confirmed working here too :+1:

**Comment by PromoFaux** [comment]
@CDeeRON @Windyo @7h3ju57 This is now released, so switch back to master branch on your local machines and update! Also another couple of bonus updates in there, too!

**Comment by Windyo** [comment]
Running update !

**Comment by CDeeRON** [comment]
Update looks good
