### ISSUE TITLE
Centos 7.5.1804 PHP error

### ISSUE THREAD

**Issue by rrobgill** [pi-hole/AdminLTE#746]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5
---
**Expected behaviour:**

Access to pi-hole admin page.

**Actual behaviour:**

500 error in browser.
/var/log/lighttpd/error.log:
(mod_fastcgi.c.434) FastCGI-stderr: PHP Fatal error: Can’t use function return value in write context in /var/www/html/pihole/index.php on line 105

**Steps to reproduce:**

Install pi-hole under these versions of Centos.
Attempt to open admin page.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
Reported in [discourse by sfraser](https://discourse.pi-hole.net/t/centos-7-5-1804-php-error/9456) sfraser's token wxfrw87gzf
Replicated by me  - my token : 0puvbj1805

**Troubleshooting undertaken, and/or other relevant information:**

As a **quick and dirty fix**, changing line 105 of /var/www/html/pihole/index.php
from
if (empty(glob("/etc/pihole/list.0.*.domains")))
to
if ((glob("/etc/pihole/list.0.*.domains")) == "")
allows the page to load.

I have not run extensive testing to see what other side-effects this could have, but the obvious one is that it may fall over in an ungraceful manner if the blocklists are not present, and it can't tell?

This is not a duplicate of #628 (the failure there occurred in a different location) but I suspect the two are related, as both involve calling empty(somefunction()) and failing in a similar manner.

Reported in [discourse by sfraser](https://discourse.pi-hole.net/t/centos-7-5-1804-php-error/9456)

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/issues/1955

I think this is the PHP 7 vs PHP 5 issue again.

**Comment by rrobgill** [comment]
Yes. That's the same issue. Didn't see that one when I went searching. Sorry.

**Comment by dschaper** [comment]
This is a better place to track it, didn't mean for this to close, just linking from the core.

**Comment by bcambl** [comment]
I have a PR open to address this with the installer here: https://github.com/pi-hole/pi-hole/pull/2161

You can try the following as a workaround until if/when my PR is approved and merged:

```
yum install -y https://rpms.remirepo.net/enterprise/${REMI_PKG}-$(rpm -E '%{rhel}').rpm
yum-config-manager --enable remi-php72
```

**Comment by rrobgill** [comment]
@bcambl I can confirm that upgrading php via remi's 7.0 repo also works

**Comment by rrobgill** [comment]
The stop-gap fix has been merged, which will keep it working (for now) until people install new repos in bcambl's fix.
