### ISSUE TITLE
Weird table spacing

### ISSUE THREAD

**Issue by kyle95wm** [pi-hole/AdminLTE#748]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`All tables on the Dashboard show normally without any weird spacing`

**Actual behaviour:**

`Ever since "Top Blocked Clients" was introduced, that table is oddly spaced.`

**Steps to reproduce:**

`Update to the latest FTLDNS beta`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`bfk4wzxf3p`

**Troubleshooting undertaken, and/or other relevant information:**

`Clear browser cache, as well as try on different browsers. Even went as far as uninstalling back to Master and then back to FTLDNS.`

<img width="2672" alt="screenshot 2018-05-13 02 17 18" src="https://user-images.githubusercontent.com/10158714/39964516-4911a2a0-5654-11e8-9aab-29cd07e0ef2b.png">

**Comment by PromoFaux** [comment]
I've seen this before, it's due to the amount of lines in each table. Note that the second table has only 9 rows. Looks like a formatting error. Thanks for reporting it, it's reminded me to look at it!

**Comment by jacobsalmela** [comment]
Fixed in v4.0.
