### ISSUE TITLE
Transparent colours are used for multiple clients

### ISSUE THREAD

**Issue by kyle95wm** [pi-hole/AdminLTE#760]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`All clients in the graph should have their own unique colour`

**Actual behaviour:**

`Some clients use the "transparent" colour, while others are using some of their own colours`

**Steps to reproduce:**

`Have a network of over 30 clients using the Pi-Hole`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`30cw46nad9`

**Troubleshooting undertaken, and/or other relevant information:**

`Flushing the logs`

**Comment by Mcat12** [comment]
Can you provide a screenshot?

**Comment by kyle95wm** [comment]
[here](http://prntscr.com/jpahkz) I hope you'll be able to see what I mean.

**Comment by Mcat12** [comment]
The clients do have their own colors, just when the theme colors run out they go to shades of black.

**Comment by Mcat12** [comment]
The new web interface will have randomly generated colors, which will make it seem less jarring.

**Comment by kyle95wm** [comment]
So wait, are we talking about the NEW interface announced earlier this year? Because I'm on the beta and I still have the older "styled" interface. If the NEWER interface is going to have this issue "fixed", then that's awesome.

**Comment by Mcat12** [comment]
Yes, the new web interface is not yet in production or the beta.

**Comment by kyle95wm** [comment]
Alright, thanks for the clarification. I guess I'll close this since there's technically nothing to fix, other than to wait for the new UI.
