### ISSUE TITLE
In FireFox (60.0.1) Query adlists never responds

### ISSUE THREAD

**Issue by lightswitch05** [pi-hole/AdminLTE#768]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:** 8

---
**Expected behaviour:**

Query adlists feature should respond with a list of matching domains - or even an empty list of no domains were found

**Actual behaviour:**

Request either never fires to begin with - or the response never gets captured. Browser just displays an empty box regardless - nothing is happening in the background.

**Steps to reproduce:**

In FireFox (60.0.1) try the query adlists feature with either exact or partial match. It doesn't matter if the domain is in a list or not.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

I don't believe this is needed and would rather keep the debugging information private at this time. If you disagree, I can update the ticket.

**Troubleshooting undertaken, and/or other relevant information:**

I looked at the JavaScript in question [queryads.js:eventsource](https://github.com/pi-hole/AdminLTE/blob/v3.3/scripts/pi-hole/js/queryads.js#L58-L106), but I am not familiar with `EventSource`. It looks correct from what I could find if it, perhaps its something specific to FireFox.

**Comment by rrobgill** [comment]
Might be best if you can upload the debug token so the developers can see what's up with your installation. There's not much for them to go by otherwise.

Query log is working for me on Firefox 60.0.1:
![2018-06-07_08 37 48](https://user-images.githubusercontent.com/35944068/41068808-912facce-6a2e-11e8-9685-297fd078b23b.jpg)

**Comment by lightswitch05** [comment]
It's working for me on Chome, so I don't think it has anything to do with my install. I have a Mac, if that's the difference.

I do have a bunch of extensions and privacy settings enabled. I'll play around with it some more and report back. Thank you for testing it with your firefox!

**Comment by Mcat12** [comment]
It is also working for me in FireFox 60.0.1

**Comment by lightswitch05** [comment]
@rrobgill I'm sorry, I just now paid closer attention to your screenshot - query log works fine - its `query adlists` that does not work. http://127.0.0.1/admin/queryads.php

I disabled a bunch of my extensions and still haven't been able to get it to work. Ironically enough it a bunch of the same extensions you have installed.

@Mcat12 did you try  `query adlists` or just the regular query log?

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/598803/41072657-b7cb3b7c-69ee-11e8-9ded-dcf620185351.png">

**Comment by Mcat12** [comment]
The Query Adlists functionality is working for me. If you open up the dev tools (F12) do you see any errors in the console?

**Comment by lightswitch05** [comment]
@Mcat12 no errors. I even stepped through the javascript and could not find any issues. The request is never fired (checked with wireshark).

I believe I found the [answer on StackOverflow](https://stackoverflow.com/a/13135995/912563). I have Sophos Endpoint Security installed on this computer, I think it is killing the request silently in the background. I don't have permissions to disable it, so no way to check for sure, but it matches closely with StackOverflow.

I'm fine with you closing this ticket if you like

**Comment by lightswitch05** [comment]
I've finally been able to reproduce this on another machine without Sophos. On Firefox, I always set privacy settings recommended here: https://www.privacytools.io/#about_config 

The configuration option that breaks this is `network.http.referer.XOriginPolicy` set to `1`.

* Only send Referer header when the full hostnames match. (Note: if you notice significant breakage, you might try 1 combined with an XOriginTrimmingPolicy tweak below.) Source
    * 0 = Send Referer in all cases
    * 1 = Send Referer to same eTLD sites
    * 2 = Send Referer only when the full hostnames match

Interestingly enough, the query adlists feature works when this configuration is either `0` or `2`, it only breaks if set to `1` - which is supposed to be the least intrusive option

Can this bug be re-opened?

**Comment by lightswitch05** [comment]
Now that I know the config options, I opened up Wireshark see the differences in the requests based on the config. With `network.http.referer.XOriginPolicy` set to either `0` or `2` - the HTTP request is **exactly** the same. With the config set to `1`, the browser never fires a request. I now think this is a bug in Firefox unless someone here knows a reason why the JavaScript side wouldn't make a request due to this option

**Comment by Mcat12** [comment]
The JS code sends the request to the same hostname as it runs under, and I can't see anything in the code that should break because of that option.

**Comment by lightswitch05** [comment]
I think is a Firefox bug with `EventSource` and `XOriginPolicy`
