### ISSUE TITLE
pi-hole version and web interface version on a mobile device

### ISSUE THREAD

**Issue by Bmooij** [pi-hole/AdminLTE#770]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Display the current pi-hole version and web interface version on a mobile device`

**Actual behaviour:**

`On a mobile device, the current pi-hole and web interface version are not visible.
Also on a mobile device there is no hint that a new version is available.`

**Steps to reproduce:**

`Visit the admin page on a mobile device.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`no token`

**Troubleshooting undertaken, and/or other relevant information:**

`None.`

**Comment by PromoFaux** [comment]
Hi there, Thanks for the report, however I would probably classify this more as a feature request than an issue. At the bottom of the issue template (the bit it asks you to delete) is a link to our discourse forums for feature requests. Much easier to track there!

https://discourse.pi-hole.net/c/feature-requests

Cheers!
