### ISSUE TITLE
Suggestion - "Pi-hole" header logo on the top of leftnav should take you to dashboard

### ISSUE THREAD

**Issue by zmsy** [pi-hole/AdminLTE#773]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1 - Casual user of pi-hole at home.

---
**Expected behaviour:**

Common UX for websites is for the icon to take you home or to the frontpage. Expected that clicking the header icon would take you there.

**Actual behaviour:**

Clicking the header icon takes you to pi-hole.net.

**Steps to reproduce:**

Click on the header icon.

**Troubleshooting undertaken, and/or other relevant information:**

It would make sense if the pi-hole.net was an entry in leftnav with its own icon.

**Comment by Mcat12** [comment]
This is actually implemented in the upcoming web interface: https://github.com/pi-hole/web

But, it would be a good first PR, if you want to do it. Otherwise let us know and we can make a PR for it.

**Comment by Recursivepaiste** [comment]
I'm happy to pick this issue (as small as it is) up and get this issue closed if it's still wanted.

**Comment by Mcat12** [comment]
Thanks @Recursivepaiste

**Comment by XhmikosR** [comment]
This does not feel normal to me either :/ I expect clicking on the logo to take me to the dashboard but instead it takes one to the pi-hole.net page. Should be a pretty trivial change. I could provide a patch if everyone agrees.

**Comment by 8633brown** [comment]
#1128 resolves this
