### ISSUE TITLE
Clients graph tooltips are not visible

### ISSUE THREAD

**Issue by timlkelly** [pi-hole/AdminLTE#775]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

I can see the entire tool tip

**Actual behaviour:**

The tool tip is cutoff / not visibile. see attached gif.
![2018-06-22 17 31 43](https://user-images.githubusercontent.com/8271737/41803134-a3131178-764b-11e8-92e4-f3e6a242b489.gif)

**Steps to reproduce:**

Hover over client graph. I'm not sure if this is related to screen dimensions, I have the browser
at full screen on a 1080 monitor.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

None yet, I'll see if I can take some time with this but wanted to report it first.

**Comment by rrobgill** [comment]
This is a known bug (#603) and has been fixed in the next release of Pi-hole. #700

**Comment by timlkelly** [comment]
Sorry for the repost then, I didn't see it when i was searching.

**Comment by rrobgill** [comment]
I think the other one is marked as closed so it won't show by default. Thanks for your report.
