### ISSUE TITLE
Add support for multiple Conditional Forwarding routers

### ISSUE THREAD

**Issue by dhoppeIT** [pi-hole/AdminLTE#784]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`I would like to configure more than one router for Conditional Forwarding at the DNS settings, because I use more than one network in my environment.`

**Actual behaviour:**

`It is only possible to configure one router for Conditional Forwarding at the DNS settings.`

**Steps to reproduce:**

`Just take a look at the web interface.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`This would not add any value to this feature request.`

**Troubleshooting undertaken, and/or other relevant information:**

`Nothing, because I am not familiar with the code. `

**Comment by rrobgill** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests).

Thank you for your understanding.
