### ISSUE TITLE
Query adlist should list full path of adlist

### ISSUE THREAD

**Issue by seb-1204** [pi-hole/AdminLTE#789]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

When querying for a blocked domain each adlist should be clearly identifiable with their full source path that is shown in the _Block Lists_ page. If a domain host two adlist for different purposes I'd like to be able to see which one is listed in the result.

**Actual behaviour:**

Block Lists / Adlist are listed by the domain and not with the full path. In some cases even with their redirected domain.
e.g. Block Lists entries from domain 
`https://raw.githubusercontent.com/.. ` 
will be listed under 
`list.0.raw.githubusercontent.com`.

This makes the source Adlist hard to identify.

In addition if the domain is hosting two block lists, e.g.
- `https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt`
- `https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt`

The query listing will only list them under an entry `list.0.raw.githubusercontent.com` thereby making it unclear on which block list the searched for entry is.

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`
Add these two Adlists to Pi-hole

- `https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt`
- `https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt`

Refresh Adlists and query for `crashlytics.com`.

![pihole adlist 1](https://user-images.githubusercontent.com/307449/42987446-687b79ea-8c0a-11e8-93e6-a433e0cfa28e.png)

![pihole adlist 2](https://user-images.githubusercontent.com/307449/42987421-51a85bca-8c0a-11e8-87b2-ca52ce3d9d62.png)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

nil

**Comment by Mcat12** [comment]
This was fixed by #676 (currently available in the FTLDNS beta).
