### ISSUE TITLE
Space between hostname and IP address in Top Clients

### ISSUE THREAD

**Issue by jradwan** [pi-hole/AdminLTE#79]
Thanks for the revised Top Clients widget! One simple touch-up request: can you put a space between the hostname and the IP address? There is one on the localhost line, but on the other lines the space is missing.

![image](https://cloud.githubusercontent.com/assets/11047158/14592062/aba3a0b8-04e8-11e6-834d-60a972974e5a.png)

**Comment by Mcat12** [comment]
Interesting... Mine has a space between every one. Can you post your hosts file?

**Comment by DonLexos** [comment]
Strange, especially since there is a space for the localhost one. I got spaces on my installation for all hosts, this could be something in your hostfile I think..

**Comment by jradwan** [comment]
Ok, it was something in my hosts file. I originally had it formatted like this:

```
192.168.1.61    nucleus    nucleus.mydomain.net   # comment
192.168.1.105   eunuce     enuce.mydomain.net     # comment
```

I took out the FQDN and comments to make it look like this:

```
192.168.1.61    nucleus
192.168.1.105   eunuce
```

And now the spaces are there.

![image](https://cloud.githubusercontent.com/assets/11047158/14612223/02b57996-0564-11e6-900f-8006510e9106.png)

**Comment by jradwan** [comment]
Just FYI, it looks like the space between hostname and IP address is missing when you have a tab at the end of the line in the hostname file. If you end the line with a space, it's fine. Just seems to be the trailing tab that can cause the formatting issue.
