### ISSUE TITLE
missin whitespace in Adlist results listing

### ISSUE THREAD

**Issue by seb-1204** [pi-hole/AdminLTE#790]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

When searching for domains in _Query adlist_ the results should have a `space` between the returned domain and the word _domains_.

It could also be that the _domains_ is intended to signal something else to the used, in which case I'd say it is not clear to the average user.

**Actual behaviour:**

Use the search in _Query adlist_ and look at the results. Between the returned domain and the word _domains_ there is a **full stop** {period for US} instead of a `space`.

![pihole adlist space](https://user-images.githubusercontent.com/307449/42988059-51ecaf9e-8c0c-11e8-90bc-4f9c2b3345c9.png)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

nil

**Comment by Mcat12** [comment]
The file that the script searches in ends with `.domains`, so this is intended. This behavior is changed anyways in the next release (see #676).
