### ISSUE TITLE
Inconsistent use of Adlist and Blocklist in UI

### ISSUE THREAD

**Issue by seb-1204** [pi-hole/AdminLTE#791]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

Descriptions and names should be used consistently throughout the UI. This should also include reports or queries generated outside of UI elements.

**Actual behaviour:**

Throughout the admin interface the words `Adlist` and `Blocklist` are used refering to the same features. 

**Steps to reproduce:**

Refer to pi-hole admin interface and attached screenshots with mark-ups.

Some thoughts: 
- Adlist VS Blocklist. I consider Adlist a subset of Blocklist. Since pi-hole caters for all types of list I'm in favour of removing the wording of Adlist in the UI and replace it by blocklist. It could be argued that many newbies come to pi-hole to block ads and therefore a explanation regarding the list might be appropriate. 
- Blocklist  and Blacklist are quire similar and could be easily confused. Have different wordings been discussed? 

![pihole adlist lists1](https://user-images.githubusercontent.com/307449/42989667-98f61664-8c11-11e8-8096-8becf099b10e.png)

![pihole adlist lists2](https://user-images.githubusercontent.com/307449/42989676-9db618a2-8c11-11e8-9341-fed3170a3f52.png)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A 

**Troubleshooting undertaken, and/or other relevant information:**

nil

**Comment by Mcat12** [comment]
Thanks, this should be simple to change.

**Comment by Mcat12** [comment]
Blacklist vs blocklist might be confusing, and it has not been discussed much. I think it's not that much of an issue, especially since they are very related (one is just a more manual version of the other). This could be debated though.

I'm putting together a PR for changing some wording to use blocklist consistently.

**Comment by Mcat12** [comment]
The Query adlists page title should still use "Lists" instead of "Blocklists" because it looks for the domain in more places than just blocklists, including the whitelist and blacklist.

**Comment by seb-1204** [comment]
I thank you guys for pi-hole. I also feel a little proud I could contribute.
