### ISSUE TITLE
PHP error (release 4.0)

### ISSUE THREAD

**Issue by kyle95wm** [pi-hole/AdminLTE#796]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`No errors on settings page`

**Actual behaviour:**

`I see the following error: There was a problem applying your settings.
Debugging information:
PHP error (2): syntax error, unexpected TC_LABEL, expecting '=' in /etc/pihole/pihole-FTL.conf on line 33 in /var/www/html/admin/settings.php:15`

**Steps to reproduce:**

`Try to save settings`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`k13t4xf70k`

**Troubleshooting undertaken, and/or other relevant information:**

`Tried to restart pihole as well as hard-refresh the browser to clear the cache`

**Comment by kyle95wm** [comment]
After further investigation, it seems to be a problem with the template file. Clearing out the data and putting my options into it fixes the error.

**Comment by Mcat12** [comment]
Thanks for opening the issue! We also just discovered this, and someone is putting together a fix now.
