### ISSUE TITLE
After upgrade from 3.x to 4.0, Blacklist webpage doesn't show blacklist, though it's there

### ISSUE THREAD

**Issue by dchang0** [pi-hole/AdminLTE#809]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`On the Blacklist webpage in the Web UI, I expect to see a list of the Exact blacklist entries I know are in effect because they are actively being blocked.`

**Actual behaviour:**

`The Blacklist webpage only shows the page title "Blacklist", the input text field "Add a domain", and the section titles "Exact" and "RegEx & Wildcard blocking"`

**Steps to reproduce:**

`Look at the Blacklist web page.  No amount of refreshing the page, flushing logs, restarting Pi-Hole, or restarting the OS fixes this--I think it might be due to my upgrade from 3.x to 4.0, which appeared to go well. I used pihole -up to upgrade.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`xzktqhi50s`

**Troubleshooting undertaken, and/or other relevant information:**

`Flushed logs, restarted Pi-Hole, restarted OS. I checked the lighttd logs and did not see any errors. My next step will be to uninstall Pi-Hole completely and install a fresh copy of Pi-Hole 4.0`

**Comment by DL6ER** [comment]
Force-refresh your browser using `Ctrl + F5` on the lists page.

**Comment by dchang0** [comment]
Nice! Took two force-refreshes to make the blacklist show up again. Thanks for the help!
