### ISSUE TITLE
Manually / Force-Update Web-UI to 4.0

### ISSUE THREAD

**Issue by whitespring** [pi-hole/AdminLTE#818]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behaviour:**

The Updater pihole -up should update all components.

**Actual behaviour:**

I edited some of the web UI html to get "All" entries to show by default in the "Queries" section. I am assuming that due to the change, the updater breaks. 

**Steps to reproduce:**

mess with the queries.php files I guess. 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

xnky4se95j

**Troubleshooting undertaken, and/or other relevant information:**

I tried to copy the original queries.php code back, that seems to not make a difference.

**Comment by PromoFaux** [comment]
Hmmm, I thought the updater was supposed to stash any locally made changes..

Might be easier to reset all changes and then manually pull the changes from the remote repo

```
cd /var/www/html/admin
sudo git reset --hard
sudo git pull
```

**Comment by dschaper** [comment]
It does stash, but if there is no user already created then it will fail as it asks for the global git user.name and user.email.

**Comment by PromoFaux** [comment]
@whitespring did that solve your issue?

**Comment by whitespring** [comment]
Yes, thank you! 
null
