### ISSUE TITLE
Error upgrading 

### ISSUE THREAD

**Issue by soydepr** [pi-hole/AdminLTE#819]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`{i Expected FTl to update }`

**Actual behaviour:**

`error upgrading ftl}`

**Steps to reproduce:**
pihole -up

`elgh9fxnqu`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

Pihole -up
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              update available

  [i] FTL out of date

  [i] FTL Checks...
  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  Error: URL not found how can I finish upgrade

**Comment by rrobgill** [comment]
Thanks for your report. 

Can you please fill out the template (it's been placed back in to your post) to help determine where the problem originates?

**Comment by soydepr** [comment]
See if that helps

**Comment by rrobgill** [comment]
Thanks for that. The debug token you gave shows it's having trouble identifying your hardware.

Can you please confirm which model of raspberry pi you're running on?

**Comment by soydepr** [comment]
Strange was working before fine.  This was not a clean install but upgrade which apparently got interrupted 

Using a raspberry pi 3 I think but not sure

**Comment by rrobgill** [comment]
Can you please tell me the responses of the following commands in a terminal window:

```uname -m```

and also

```lscpu | head```

**Comment by soydepr** [comment]
soydepr@coqui:~$ lscpu|head
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model:                 4
Model name:            ARMv7 Processor rev 4 (v7l)
CPU max MHz:           1200.0000
soydepr@coqui:~$ uname -m
armv7l
soydepr@coqui:~$

**Comment by soydepr** [comment]
Had already tried that 

[✓] Checking for php7.0-sqlite3
Can't call method "set" on an undefined value at /usr/share/perl5/Debconf/FrontEnd.pm line 126, <GEN0> line 5.
Use of uninitialized value $ret in scalar chomp at /usr/share/perl5/Debconf/Client/ConfModule.pm line 132, <STDIN> line 4.
Use of uninitialized value $ret in split at /usr/share/perl5/Debconf/Client/ConfModule.pm line 133, <STDIN> line 4.
Use of uninitialized value $ret[0] in string eq at /usr/share/perl5/Debconf/Client/ConfModule.pm line 134, <STDIN> line 4.
Use of uninitialized value $ret[0] in string eq at /usr/bin/debconf-apt-progress line 173, <STDIN> line 4.
soydepr@coqui:~$

**Comment by rrobgill** [comment]
If you haven't already, I would suggest ensuring your system is up to date before proceeding further:

```sudo apt update```
```sudo apt upgrade```

Then if that is successful, try to reinstall from scratch:

```sudo bash -x /etc/.pihole/automated\ install/basic-install.sh --unattended```

**Comment by soydepr** [comment]
That resulted in 

+ debconf-apt-progress -- apt-get --yes --no-install-recommends install dns-root-data resolvconf
Can't call method "set" on an undefined value at /usr/share/perl5/Debconf/FrontEnd.pm line 126, <GEN0> line 25.
Use of uninitialized value $ret in scalar chomp at /usr/share/perl5/Debconf/Client/ConfModule.pm line 132, <STDIN> line 24.
Use of uninitialized value $ret in split at /usr/share/perl5/Debconf/Client/ConfModule.pm line 133, <STDIN> line 24.
Use of uninitialized value $ret[0] in string eq at /usr/share/perl5/Debconf/Client/ConfModule.pm line 134, <STDIN> line 24.
Use of uninitialized value $ret[0] in string eq at /usr/bin/debconf-apt-progress line 173, <STDIN> line 24.soydepr@coqui:~$


Perhaps I should uninstall first ?

At least pihole is latest sis web and ftl fu@#$% up
