### ISSUE TITLE
Persistent XSS in web interface

### ISSUE THREAD

**Issue by roddux** [pi-hole/AdminLTE#82]
##### Expected Behaviour:
Sanitation of host names displayed by Pi-Hole

##### Actual Behaviour:
Domains queried against a server running Pi-Hole will be displayed in the web admin console without sanitation.

##### Steps to reproduce this issue:
Run the following command in a shell:
`dig '<img/src="x"/onerror=alert(document.cookie)>' @PiHoleServer`

If required, run the command repeatedly until the result appears in the Top-10 list.

Note the alert box that appears.

**Comment by PromoFaux** [comment]
Ah! Nice catch!

I was struggling to understand what was happening until I followed your steps. Does the PR above fix it?

**Comment by roddux** [comment]
I haven't tested it as I'm on a work computer, but I'm 100% sure it will.

Just created another request to the devel branch, my mistake.

**Comment by PromoFaux** [comment]
Just tried it out, stops the api from running completely. Interestingly, nothing in the lighttpd error log...

**Comment by PromoFaux** [comment]
Oh no, wait. It's running, but `index.php` is just not parsing the results. Example output:

```
{&quot;domains_being_blocked&quot;:102661,&quot;dns_queries_today&quot;:89,&quot;ads_blocked_today&quot;:30,&quot;ads_percentage_today&quot;:33.707865168539,&quot;top_sources&quot;:{&quot;192.168.216.235&quot;:89}}
```

**Comment by roddux** [comment]
I've updated the fix-- It didn't work before! I've just tested my latest version of the fix, which now does work.

Example: http://178.62.45.216/admin/

**Comment by PromoFaux** [comment]
Just tried that, works fine!
