### ISSUE TITLE
Getting long-term data for a date range with no data produces cryptic error

### ISSUE THREAD

**Issue by zhimsel** [pi-hole/AdminLTE#836]
**In raising this issue, I confirm the following:**:

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2 (not really a front-end dev)

---

For a pihole installation that has only been running for 3 days, try to load long-term data for "the past 7 days"

**Expected behaviour:**

Data is returned only for the date range where data exists (i.e. for the last 3 days, even if 7 days were selected). Maybe an optional warning or [more descriptive] error.

**Actual behaviour:**

A pop-up "Unknown error while loading the data"

**Steps to reproduce:**

- Either create a new installation of pihole or clear the `pihole-FTL.db` database (by deleting or using SQLite3).
- Let it collect some data (for say 1 hour).
- Go to long-term data and search for only the last hour: success
- Search for any time period longer than 1 hour (say, 1 day): error produced

**Debug token:**

`hoq4mwvryt`

**Troubleshooting undertaken, and/or other relevant information:**

It took some digging to figure out what was going on. I checked all the file permissions, etc. I only realized what the issue actually was when I was able to get long-term data for a data range within the time my pihole installation was actually running (approximately the last 2-3 days). If I selected a time range that included dates with no data (say "the last 7 days"), the error would be produced.

**Comment by DL6ER** [comment]
Okay, I tried the following:

- Stopped `pihole-FTL`
- Moved the database somewhere else
- Started `pihole-FTL`
- Let it collect about 5minutes of data
- Requested a full day -> Worked
- Requested a month -> Worked
- Requested data in October 1999 -> Worked

Still trying to see how I can reproduce this...

**Comment by DL6ER** [comment]
Example: First entry in the DB `2018-08-28 12:23:06`, last entry is `2018-08-28 12:29:41`

I can query the entire day without any issue:
![screenshot at 2018-08-28 12-33-52](https://user-images.githubusercontent.com/16748619/44717890-a1cee880-aabe-11e8-81de-8c7f5ed02b30.png)


Identical result for 12:00 - 13:00:
![screenshot at 2018-08-28 12-33-18](https://user-images.githubusercontent.com/16748619/44717867-954a9000-aabe-11e8-974f-143781c3060c.png)


Yesterday gives no data:
![screenshot at 2018-08-28 12-32-25](https://user-images.githubusercontent.com/16748619/44717829-6d5b2c80-aabe-11e8-8b7d-10d8a922f2de.png)

**Comment by zhimsel** [comment]
Huh. That's strange. I just tried to replicate again myself, and starting with a blank DB, it works fine. Only when I put my DB back in do I get that error. As much as I'd rather not lose my 4-day history (heh), I could just wipe it and call it a day.

Still interested to know what the problem itself is. Maybe the DB is corrupted somehow?

**Comment by zhimsel** [comment]
Comparing to the [documentation](https://docs.pi-hole.net/ftldns/database/), the DB tables look correct...
```
root@pihole:/etc/pihole# sqlite3 pihole-FTL.db~
sqlite> .tables
counters  ftl       queries
sqlite> .schema queries
CREATE TABLE queries ( id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp INTEGER NOT NULL, type INTEGER NOT NULL, status INTEGER NOT NULL, domain TEXT NOT NULL, client TEXT NOT NULL, forward TEXT );
CREATE INDEX idx_queries_timestamps ON queries (timestamp);
sqlite> .schema counters
CREATE TABLE counters ( id INTEGER PRIMARY KEY NOT NULL, value INTEGER NOT NULL );
```

I'd be happy to provide sanitized dumps of the table contents if that helps.

**Comment by zhimsel** [comment]
For what it's worth, this is the error I get: 
![screen shot 2018-08-28 at 12 59 09](https://user-images.githubusercontent.com/5325723/44744361-3850d900-aac2-11e8-84f1-b5fdaeb7655e.png)

Note: it takes a couple seconds before the error pops up. Compare this to an instant (but empty) response from the clean DB.

**Comment by zhimsel** [comment]
Actually, here's the actual DB that I'm getting the error from: https://s3.amazonaws.com/zhimsel-public/pihole-FTL.db

I've sanitized it by replacing all the values for the `domain` and `client` columns with `redacted`, but made no other changes.

**Comment by DL6ER** [comment]
Thanks for the link, I will see if I can find some time to download this database and use it for testing. I'll respond here when I some news for you. I will mark this as a potential bug as we're not yet sure what is happening.

**Comment by DL6ER** [comment]
Well ... even with your file everything seems to work perfectly fine :eyes: 

Today:
![screenshot at 2018-08-28 21-30-26](https://user-images.githubusercontent.com/16748619/44746052-a7055500-ab09-11e8-95da-cc4c83ebad61.png)

Yesterday:
![screenshot at 2018-08-28 21-30-13](https://user-images.githubusercontent.com/16748619/44746060-ab317280-ab09-11e8-9e5a-dd847b13dcd9.png)

Last 7 days:
![screenshot at 2018-08-28 21-29-39](https://user-images.githubusercontent.com/16748619/44746075-b08ebd00-ab09-11e8-83a8-71778c47ccd0.png)

This month:
![screenshot at 2018-08-28 21-29-58](https://user-images.githubusercontent.com/16748619/44746090-b4224400-ab09-11e8-8a05-110be6195b23.png)

**Comment by DL6ER** [comment]
Even from the "beginning of time", seems to work
![screenshot at 2018-08-28 21-33-54](https://user-images.githubusercontent.com/16748619/44746254-2004ac80-ab0a-11e8-98ee-92850777bd32.png)

**Comment by DL6ER** [comment]
I see your screen shot going from earlier than 1970, that may not be wise.

**Comment by zhimsel** [comment]
That's weird... What version of FTL-admin are you on? I'm on v4.0

> I see your screen shot going from earlier than 1970, that may not be wise.

I just clicked on the "beginning of time" default period.

**Comment by zhimsel** [comment]
Also, it's weird that you're getting 72k total queries. There should only be ~30k

**Comment by zhimsel** [comment]
HUH. Even weirder, I'm getting that 72k figure as well, if I specify (roughly) from the time the logs start to ~48 minutes ago. However, I'm only seeing ~33k on the dashboard (which should be correct).

**Comment by zhimsel** [comment]
Wait, so looking at the raw DB, there are 72947 rows, which means there _are_ ~72k queries. However, my dashboard is only showing ~33k queries.

**Comment by DL6ER** [comment]
> Is the dashboard only calculating the last 24 hours?

Yes. We continuously correct all statistics accordingly so that all counters span the most recent 24 hours. On top, on (re)start of `pihole-FTL`, we import only the most recent 24 hours.

**Comment by Mcat12** [comment]
It may be that your device does not have enough RAM or processing power to return the queries, in which case it fails. This possible failure is noted in the yellow warning box that appears when it is loading the queries.

**Comment by zhimsel** [comment]
No, I don't think that's the problem. There's plenty of RAM and CPU left during the query. The CPU load never goes above 0.00 for the 1-min average, and RAM doesn't really increase any significant amount. I watched `htop` during one of the attempted data loads.

**Comment by DL6ER** [comment]
@zhimsel I'm a bit confused. Can you still reproduce this?

If so, are there any hints in `/var/log/lighttpd/error.log` for why the query failed? It may be that there are also still some old errors in this file or one of the other files in this folder that may be helpful.

**Comment by zhimsel** [comment]
@DL6ER so this _technically_ isn't happening for me any more since I deleted the DB and let it be re-created from scratch. The new DB works as expected.

However, I temporarily restored the "dirty" DB and ran some tests...

I confirmed the original error is still encountered. Watching `htop`, I saw a brief CPU spike for one of the `php-cgi` forks (100% on a single core for less than 2 seconds). There were no errors in the lighttpd `error.log`. There were also no [apparently] relevant log entries in `pihole.log` or `pihole-FTL.log`.

----

### NEW INFO!

While doing long-term searches, I did notice some things that narrow down the behavior a little bit. Here are some new facts:
- This database contains data for 8/25-8/28
- Selecting a date range that doesn't have _any data_ works as expected (it just doesn't return anything). For example: selecting "Last Month" or "Yesterday" (i.e. "8/29").
- Selecting a date range that starts _after the data starts_ (e.g. "8/26"), but ends in a place where there is no data (e.g. "8/29") works as expected (it returns queries only for the data it has, with no error).
- Selecting a date range that starts _before the data starts_ (e.g. "8/20"), but ends _after the data starts_ (e.g. "8/30") produces the error in question.

So it seems that this error only occurs if the selected date range _begins_ with no data...

**Comment by DL6ER** [comment]
What was the domain in front of `�` ? I'd like to know if the character ended up there intentionally or by mistake.

`pihole-FTL` is intentionally constructed such that it can handle arbitrary characters without questioning if they make sense (to support Umlauts, Arabic, Chinese, etc. characters we have no idea about!). I copy&pasted your `�` and it seemed to have worked:
```
$ dig �                                                                        

; <<>> DiG 9.9.5-9+deb8u15-Raspbian <<>> �
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54004
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;\239\191\189.                  IN      A

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Aug 30 21:28:17 CEST 2018
;; MSG SIZE  rcvd: 21
```
However, I wasn't able to get an error. Instead, the dashboard reported the strange domain correctly:
![screenshot at 2018-08-30 21-30-46](https://user-images.githubusercontent.com/16748619/44874608-fed3c580-ac9b-11e8-903a-5c2277937715.png)

Thinking again about it, it may actually come down to your particular combination of operating system + browser, i.e., your Pi-hole sends the correct data, but the client isn't able to handle the data stream (probably expecting ASCII). I'm using Linux (Debian) with en_US locale + Firefox Quantum 61. How does your configuration look like?

**Comment by DL6ER** [comment]
Yeah, please send me the one-line database if its not too much effort for you. My host system is identical to yours. An interesting question is still what kind of browser you're using as all hints currently point towards a client-side (i.e., Javascript) issue.

**Comment by badabing2005** [comment]
I have the same issue, what is the recommended way to fix this?

Thanks

**Comment by zhimsel** [comment]
@DL6ER Sorry for the delay. Here's the DB with just that row. Note: I made this by running the following queries (in SQLite3):
```
delete from queries where id != 259;
vacuum;
```
[pihole-FTL-dirty.db.zip](https://github.com/pi-hole/AdminLTE/files/2349774/pihole-FTL-dirty.db.zip)

**Comment by zhimsel** [comment]
@badabing2005 can you confirm that the `.db` file was actually removed while `pihole-FTL` was stopped, and that it was recreated when it was started again?

If you're starting with a fresh DB, this isn't _shouldn't_ present itself unless your DB is consistently getting those "unknown" characters. I'd inspect the DB with `sqlite3` and see if there are any un-printable characters.

**Comment by badabing2005** [comment]
**Update**

`http://10.1.1.60/admin/api_db.php?getAllQueries=empty&_=1536414869351`
Is getting HTTP 500

Before that there are couple of font loading issues:
![image](https://user-images.githubusercontent.com/22603312/45254887-df006980-b34d-11e8-8bbf-99e67d7daea9.png)

**Comment by Mcat12** [comment]
@badabing2005 Make a new issue (with a debug token), since yours seems to have different causes and symptoms.

@zhimsel I can confirm the error on the long term stats page using your database:
```
An unknown error occurred while loading the data.
Error connecting to database
```

That corrupted domain is probably incompatible with PHP's SQLite database driver. Since you found that removing this corrupted query fixed the issue, this issue will be closed (feel free to continue the discussion though).
