### ISSUE TITLE
Suggestions: please add more custom dns blanks.

### ISSUE THREAD

**Issue by lifansama** [pi-hole/AdminLTE#837]
I am a user from China. All the “Upstream DNS Servers” the pi-hole provided are very slow  in China.
So, could you make the web allow me to add more custom dns？

**Comment by DL6ER** [comment]
[You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.

When you open a feature request over there, please specify why you need more than two (or four incl. IPv6) custom servers.
