### ISSUE TITLE
Blocked percentage above 100% for weeks (v4.0)

### ISSUE THREAD

**Issue by walter-exit** [pi-hole/AdminLTE#851]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [?] The issue I am reporting can be *replicated*.
- [?] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
8

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
Not going above 100% blocked

`{A detailed description of what you expect to see}`

**Actual behaviour:**
Percentage always being above 100%:
https://paste.pics/3U6VY

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**
Run piHole 4.0+
`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`
Opening a ticket here :)

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by walter-exit** [comment]
That is superb news!

PS 1: Do you happen to know when the next update is going to be released to the public?

PS 2: How is development going in general? If I'm not mistaken, the next big change will be in the webinterface (technology rewrite from the ground up so to speak?). Is there anything of that scale in the works for Core or FTL too? Is there something like a "Trello board" with things coming up? Or needing to be done?

I'm still waiting for the perfect time to jump into this as a volunteer. Since Web is right in the middle of a major rewrite, It seemed wiser to jump on-board afterwards.

**Comment by Mcat12** [comment]
1. We do not have an ETA unfortunately.
2. Development is going well, and there will actually be some news on this released very soon :wink:. Web has a project board here for the MVP, and I will be working more on filling out more issues soon: https://github.com/pi-hole/web/projects/1.
