### ISSUE TITLE
Adding ADMIN_INTERFACE_DIR to setupVars.conf

### ISSUE THREAD

**Issue by Mineroboter** [pi-hole/AdminLTE#873]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

- Successfully changing the variable ADMIN_INTERFACE_DIR in setupVars.conf in /etc/pihole from "/var/www/html/admin" to e.g. "/var/www/pihole"; 
- No manual change to the source code would be needed.
- pihole -up throws no error.

**Actual behaviour:**

This feature isn't possible (I think). Only manually changing ADMIN_INTERFACE_DIR in e.g. /opt/pihole/update.sh to a different value.

Setting ADMIN_INTERFACE_DIR in setupVars.conf throws the error: "/etc/pihole/setupVars.conf: Zeile 12: ADMIN_INTERFACE_DIR: Schreibgeschützte Variable." when executing pihole -up

**Steps to reproduce:**

Set ADMIN_INTERFACE_DIR in setupVars.conf to e.g. "/var/www/pihole/" and execute pihole -up.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

o6dwo4tpbw

**Troubleshooting undertaken, and/or other relevant information:**

Because this isn't really a new feature and also didn't really fit into the scope of discourse.pi-hole.net/c/feature-requests , I'm posting it here.
If I'm mistaken and this is already possible, feel free to correct me, but I haven't found any related posts.

**Comment by Mcat12** [comment]
`ADMIN_INTERFACE_DIR` is not a valid setupVars setting, so there is no way that it can handle this.

**Comment by Mcat12** [comment]
You can make a feature request for having a configurable web interface directory on the Discourse, but when the API is released the web interface will be embedded and this setting would not be needed.
