### ISSUE TITLE
 v4.1.1 Recent Queries not work: ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by polygontwist** [pi-hole/AdminLTE#883]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{7}`

---
**Expected behaviour:**

`{show query log}`

**Actual behaviour:**

`{noting; Console wrote: ReferenceError: moment is not defined queries.js:295:101 }`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{qkl3mg6itn}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Login, clikc "Query Log"}`

**Comment by polygontwist** [comment]
i use Windows10, Firefox 64.0; Chrome 71.0.3578.98
yes, moment.min.js exist. when loading, an empty file is returned. on the pi the file is present - with content.

if I

```
 { "width" : "15%", "render": function (data, type, full, meta) { 
				if(type === "display"){
					if(!(typeof moment ==="undefined"))
						return moment.unix(data).format("Y-MM-DD [<br class='hidden-lg'>]HH:mm:ss z");
				}
				else
				{return data;} 
			}},
```

append to line 295 (if(!(typeof moment ==="undefined"))) in queries.js will display a list.

>  ls -l moment.min.js
-rwxrwxrwx 1 root root 61317 Nov 17 17:11 moment.min.js

**Comment by polygontwist** [comment]
I duplicated the file, renamed the original "_moment.min.js" and the duplicate "moment.min.js". now is running. I've undone the changes in queries.js.

but in longterm-data:
![grafik](https://user-images.githubusercontent.com/3751286/50539238-30db3280-0b7d-11e9-8d9e-c95e5cecb113.png)

**Comment by polygontwist** [comment]
_moment.min.js = original
moment.min.js = copy
```
pi@pi0:/var/www/html/admin/scripts/vendor $ stat _moment.min.js
  Datei: _moment.min.js
  Größe: 61317          Blöcke: 120        EA Block: 4096   reguläre Datei
Gerät: b307h/45831d     Inode: 417760      Verknüpfungen: 1
Zugriff: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Zugriff    : 2018-11-17 17:11:22.463629648 +0100
Modifiziert: 2018-11-17 17:11:22.463629648 +0100
Geändert   : 2018-12-29 15:24:51.680085144 +0100
 Geburt    : -
pi@pi0:/var/www/html/admin/scripts/vendor $ stat moment.min.js
  Datei: moment.min.js
  Größe: 61317          Blöcke: 120        EA Block: 4096   reguläre Datei
Gerät: b307h/45831d     Inode: 417760      Verknüpfungen: 1
Zugriff: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Zugriff    : 2018-11-17 17:11:22.463629648 +0100
Modifiziert: 2018-11-17 17:11:22.463629648 +0100
Geändert   : 2018-12-29 15:29:04.588039305 +0100
 Geburt    : -

```

**Comment by DL6ER** [comment]
How about
```
git diff
```
and
```
diff moment.min.js _moment.min.js
```
in this directory?

**Comment by polygontwist** [comment]
git diff: all files (i cange it for samba). the content is identical
```
old mode 100644
new mode 100755
```
those were my changes
```
--- a/scripts/pi-hole/js/queries.js
+++ b/scripts/pi-hole/js/queries.js
@@ -292,7 +292,13 @@ $(document).ready(function() {
         "processing": true,
         "order" : [[0, "desc"]],
         "columns": [
-            { "width" : "15%", "render": function (data, type, full, meta) { if(type === "display"){return moment.unix(data).format("Y-MM-DD [<br class='hidden-lg'>]HH:mm:ss z");}else{return data;} }},
+            { "width" : "15%", "render": function (data, type, full, meta) {
+                               if(type === "display"){
+                                       return moment.unix(data).format("Y-MM-DD [<br class='hidden-lg'>]HH:mm:ss z");
+                               }
+                               else
+                               {return data;}
+                       }},
             { "width" : "4%" },
             { "width" : "36%", "render": $.fn.dataTable.render.text() },
             { "width" : "8%", "render": $.fn.dataTable.render.text() },

```

> diff moment.min.js _moment.min.js
nothing

If the files are the same, then I can not see any difference.
When I swap the files, the file is delivered empty again.

**Comment by polygontwist** [comment]
> sudo git reset --hard
I renamed the original file again. Everything works now with the command.

> Then there might be an issue with the file table and the other file somehow cannot be found by lighttpd.
yes, I guess that too. thanks for the tips and the time.
