### ISSUE TITLE
Failed Host Check <hostname>.local

### ISSUE THREAD

**Issue by m-vellinga** [pi-hole/AdminLTE#885]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`3`

---
**Expected behaviour:**

When navigating to http://hostname.local in your local network to be able to load both the admin interface and the normal root index.php. The default hostname of a fresh Raspbian install is raspberrypi. Navigating to raspberrypi.local/admin should load the admin interface.

**Actual behaviour:**

When navigating to http://raspberrypi.local/admin the following error is shown: 

`Failed Host Check: raspberrypi.local vs 192.168.1.100, , _, pi.hole, localhost`

**Steps to reproduce:**
Find the <hostname>.local of your pi

`$ avahi-resolve-address <IP OF PI>`
`<IP OF PI>	raspberrypi.local`

In your browser go to and see the error:
`http://raspberrypi.local/admin`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`8cirzg17aw`

**Troubleshooting undertaken, and/or other relevant information:**

* This also breaks the landing page in the pihole repo for the root of the domain. It tries to resolve to pi.hole for all static assets when navigating to http://raspberrypi.local but it does not show an Failed host check error because it defaults to pi.hole if it's not in the authorized host list (if I'm not mistaken)
* I use nginx instead of lighttpd but that does not seem to make a difference
* The code resulting in the error can be found at (master branch): scripts/pi-hole/php/auth.php#L31

**Comment by Mcat12** [comment]
The web interface is only loadable from those origins to make sure that ads don't try to load the web interface or interact with the API (only applicable in IP based block modes). You can add a virtual host to be able to visit the web interface from another origin. That code is right below the code you mentioned:
https://github.com/pi-hole/AdminLTE/blob/de7aa5a3fafb7d82b50d9972a1451a848c89037a/scripts/pi-hole/php/auth.php#L39-L42

However, this is not a bug, so the issue will be closed.
