### ISSUE TITLE
Wrong text/suggestion in Advanced DNS settings

### ISSUE THREAD

**Issue by HellStorm666** [pi-hole/AdminLTE#893]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`{Pi-hole should use conditional forwarding from the DHCP server.}`

**Actual behaviour:**

`{There is asked to fill in the address of the router, what isn't the same}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

The text under Advanced DNS settings, Conditional Forwarding should ask to fill in the address and local domain of the DHCP server.
This could be the Router, but in a lot of cases this isn't the router.

The text now is:
```
Conditional Forwarding
If not configured as your DHCP server, Pi-hole won't able to determine the names of devices on your local network. As a result, tables such as Top Clients will only show IP addresses.

One solution for this is to configure Pi-hole to forward these requests to your home router, but only for devices on your home network. To configure this we will need to know the IP address of your router and the name of your local network.

Note: The local domain name must match the domain name specified in your router, likely found within the DHCP settings.
```

And should be:
```
Conditional Forwarding
If not configured as your DHCP server, Pi-hole won't able to determine the names of devices on your local network. As a result, tables such as Top Clients will only show IP addresses.

One solution for this is to configure Pi-hole to forward these requests to your DHCP server (most likely your router), but only for devices on your home network. To configure this we will need to know the IP address of your DHCP server and the name of your local network.

Note: The local domain name must match the domain name specified in your DHCP server, likely found within the DHCP settings.
```

**Comment by DL6ER** [comment]
>  This could be the Router, but in a lot of cases this isn't the router.

I disagree. The vast majority of users install it in their home networks which have the most simple topology you can imagine (devices connected to a router). Nevertheless, your suggested change is good.
