### ISSUE TITLE
[Question] Backup

### ISSUE THREAD

**Issue by zero77** [pi-hole/AdminLTE#905]
Is there any documentation on how to backup all settings and configurations, ready for a reinstall.
Also, i dont need to back up logs.
Thanks

**Comment by Mcat12** [comment]
Use the "Teleporter" functionality in the web interface settings.

**Comment by zero77** [comment]
@Mcat12 
Thanks, is this possible via terminal and does it include rules and all settings.

**Comment by zero77** [comment]
@Mcat12 
Thank you.
