### ISSUE TITLE
Domain lists sometimes don't fit

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/AdminLTE#91]
##### Expected Behaviour:

Domain names should fit/be truncated to fit the section
##### Actual Behaviour:

![img](https://cloud.githubusercontent.com/assets/4417660/15441141/27746952-1ea7-11e6-9517-1bccd9499483.png)
The client section would probably also have this issue.
##### Steps to reproduce this issue:

Query a domain with a long name or give a client a long name.
##

**Comment by brantje** [comment]
You can use css text ellipsis for this:
```
.truncate {
  width: 250px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
Add the full domain / client name under a title attribute.

**Comment by tsenovIvan** [comment]
Hello,

I also saw the bug on one of my tablets.

Can I suggest the same changes as thone here: https://github.com/pi-hole/AdminLTE/pull/113/commits/f4b52452e6a1d903d18ffe5e3043f4d892160475 ?
It will make the tables scroll horizontally if they don't fit.

I already tried it and it works OK.

If you also like this approach, I can make a pull request?

KR
Ivan

**Comment by PromoFaux** [comment]
Hi @tsenovIvan , by all means make a pull request at any time you feel you have something to add :)

That sounds like a great idea. cheers!

**Comment by Mcat12** [comment]
Fixed a long time ago.
