### ISSUE TITLE
Typo, missing "be"

### ISSUE THREAD

**Issue by emelendez89** [pi-hole/AdminLTE#910]
> Pi-hole won't able to determine the names of devices

Should say:
> Pi-hole won't **be** able to determine the names of devices

In:
https://github.com/pi-hole/AdminLTE/blob/347994db169eb486954cbcff6f62955c77c1db4a/settings.php#L859

**Comment by Mcat12** [comment]
Feel free to open a PR, or we can if you don't.

**Comment by emelendez89** [comment]
I don't know how to create a new branch from a Github Issue, or shoud I create my own fork and PR from there?

**Comment by Mcat12** [comment]
Yes, but make sure you check out the contributor's guide (especially the note about working off the devel branch, and submitting PRs to the devel branch): https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md

**Comment by Mcat12** [comment]
Closed by #913
