### ISSUE TITLE
Web interface feature:  Dashboard "Top Clients (Blocked Only)" FILTERS only blocked domains.

### ISSUE THREAD

**Issue by jaxjexjox** [pi-hole/AdminLTE#912]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [Y] The issue I am reporting can be *replicated*.
- [Unknown] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Filtered results, based on the description of the dashboard entry

**Actual behaviour:**

Standard results which can be obtained elsewhere.

**Steps to reproduce:**

Click on any bottom left dashboard entry, in the "Top Clients (Blocked Only)" list

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

N/A

Subject should be self explanatory.

The UI is not following logic

If I click hostname "NAUGHTY-COMPUTER" (Top Blocked) in the bottom right.
I expect to see "NAUGHTY-COMPUTERS" blocked list, not list of all hits.

I don't think we should be seeing allowed, ONLY blocked in the subsequent view after clicking this.

Then I know it's constantly hitting "reallybaddomain.com" for example, instead of having to scroll down the list, looking for RED entries.

I could've SWORN I logged this several months ago.

**Comment by Mcat12** [comment]
I've re-added the issue template to your post. Please fill it out.
There is no need to get riled up over a small bug.

**Comment by jaxjexjox** [comment]
I am not even remotely riled up in the slightest, please do not interpret emphasising words with capitals as angry.    If I stop dropping ! all over the place, then we'll have to worry.

**Comment by PromoFaux** [comment]
Hi there, 

You appear to have opened an issue for a feature request.

As per issue template instructions, All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests).

Thank you for your time.

**Comment by DL6ER** [comment]
It's currently not possible to do this without investing much effort as neither the PHP API nor FTL support filtering by the blocking state.

The lifetime of the current web interface is coming to an end and currently all work is going into its successor. See https://github.com/pi-hole/web. We only fix bugs but do not add any new features to the current web interface as everything we code would need to be coded twice, otherwise.

**Comment by jaxjexjox** [comment]
Let me clarify, the entire WebUI is being overhauled / replaced?   Will it still fit in the same memory footprint? (256 / 512MB odd little Chinese units like Orange Pi)

I'm happy to wait and re-log this suggestion in the tracker for the new one, when it arrives, if it lacks this feature.

Thanks for your reply, appreciate.

**Comment by Mcat12** [comment]
The web interface is being rewritten in React with a backend in Rust. Only the backend runs on the Pi-hole device, the frontend runs on the client. The hardware requirements will be the same or (likely much) less.

**Comment by jaxjexjox** [comment]
Apologies but I'm curious when this new UI is coming along?  Any time soon?

**Comment by Mcat12** [comment]
I can't give an ETA sadly. This PR is the best place to see the integration progress: pi-hole/pi-hole#2692

**Comment by jaxjexjox** [comment]
Thanks for that, I'll keep an eye on it.
