### ISSUE TITLE
Update to 4.2.1 failing

### ISSUE THREAD

**Issue by gordonjct** [pi-hole/AdminLTE#914]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2
---
**Expected behaviour:**

Upgrade work with error

**Actual behaviour:**

Running pihole -up sees this error:

error: inflate: data stream error (invalid code lengths set)
error: failed to read object 053d28980fd107d189a7893a97c5fa0a2ecefa6e at offset 48344 from .git/objects/pack/pack-eaf2dd2c8240e74617c25c532fc19cfe15d1d955.pack
fatal: packed object 053d28980fd107d189a7893a97c5fa0a2ecefa6e (stored in .git/objects/pack/pack-eaf2dd2c8240e74617c25c532fc19cfe15d1d955.pack) is corrupt
fatal: The remote end hung up unexpectedly

Process continues

**Steps to reproduce:**

Run update again

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

u8w6yicolh

**Troubleshooting undertaken, and/or other relevant information:**

Waited a few days anticipating an update may be available

Note on web interface see:
Pi-hole Version v4.2.1 Web Interface Version v4.1.1 (Update available!) FTL Version v4.2.1

Am running Pi-Hole on a Raspberry Pi 3B, on a 32Gb Micro SDRAM Class 10 with Raspbian Lite installed. OS is up to date. System is running headless and on Ethernet.

**Comment by Mcat12** [comment]
It looks like your web git repo is corrupt. Try running these commands:
```
cd /var/www/html/
sudo rm -rf admin
sudo git clone https://github.com/pi-hole/AdminLTE.git admin
```

**Comment by gordonjct** [comment]
Thank you that got rid of the error am still seeing on the Dashboard page that the Web interface has an update. However a pihole -up does not update this?

**Comment by gordonjct** [comment]
After a reboot all up to date. Did use a variation on your update above. Stopped Pi-Hole, moved admin folder, then did clone and re-started.

**Comment by Mcat12** [comment]
`pihole -up` does not know how to deal with corrupted git repos. Glad to see that the issue is fixed!
