### ISSUE TITLE
Static DHCP hostname should be checked for validity

### ISSUE THREAD

**Issue by jnko** [pi-hole/AdminLTE#919]
When entering a hostname in pihole-web Settings->DHCP->"Static DHCP Leases" the name should be checked for validity.

Currently it is possibe to enter a dot within the hostname, for example "Nokia7.1" which will result in a not resolvable dns entry.

[a-zA-Z0-9-]

**Comment by DL6ER** [comment]
Why should `Nokia7.1` not work? It is the subdomain `Nokia7` under the top-level-domain `1`.

Example:
``
pi@munichpi ~ $ grep "Nokia" /etc/hosts
127.0.0.10      Nokia7.1

pi@munichpi ~ $ dig Nokia7.1 +short
127.0.0.10
```

**Comment by yubiuser** [comment]
We do check hostnames for validity

https://github.com/pi-hole/AdminLTE/blob/f85da922fd178c3b94521a691c71b7b43cb3cb57/scripts/pi-hole/php/savesettings.php#L132-L147

https://github.com/pi-hole/AdminLTE/blob/f85da922fd178c3b94521a691c71b7b43cb3cb57/scripts/pi-hole/php/func.php#L12-L32
