### ISSUE TITLE
[Feature Request] Use Apache If Lighttpd Is Not Installed

### ISSUE THREAD

**Issue by zero77** [pi-hole/AdminLTE#920]
If Lighttpd is not installed but Apache is installed then, can you automatically use Apache as the default.
I am currently using pi-hole in ubuntu 18.04 with the newest Apache and it works without any problems.
Thanks

**Comment by Mcat12** [comment]
As noted in the [issue template](https://github.com/pi-hole/AdminLTE/blob/master/.github/ISSUE_TEMPLATE.md):
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
