### ISSUE TITLE
Dashboard is showing loading icons

### ISSUE THREAD

**Issue by RichardGladman** [pi-hole/AdminLTE#922]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
0
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

Opening the PiHole Admin console should show gtaphs and activity stats

**Actual behaviour:**

Graphs show loading icons and stats show ---

**Steps to reproduce:**

Open the dashboard page

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

g3ai0zvx5y

**Troubleshooting undertaken, and/or other relevant information:**

Pihole itself seems to be correctly working, I can access the Internet and the query log shows that sites are being blocked.

Pi-hole Version v4.2.2 Web Interface Version v4.2 FTL Version v4.2.3

So far I have:

- Updated PiHole
- Updated Raspian
- Rebooted
- Cleared browser cache and cookies
- Ran pihole -r
- Restarted browser (Falkon: Application version 3.0.1, QtWebEngine version 5.12.1**)**
- Looked at line 308 of /var/www/html/admin/api_FTL.php but it doesn't have the suggested code to change
- Added log-queries=extra to /etc/dnsmasq.d/01-pihole.conf
- Checked that permissions on log files are 0644
- Run pihole updatechecker remote

**Comment by Mcat12** [comment]
See discussion on Reddit:
https://www.reddit.com/r/pihole/comments/awup9a/pi_hole_dashboard_is_showing_loading_icons/

**Comment by bsyk** [comment]
I have had the same issue recently. Debugging, my issue is because there are 2500 unique client IPs (mostly IPv6) trying to get drawn in the `Clients (over time)` chart, which is taking so long to render that the update cycle kicks in and it never finishes.  It also uses 100% cpu.

I have a patch that restricts to the top 20 clients which then works happily.

**Comment by DL6ER** [comment]
@bsyk Do you want to share your patch with the project? If you submit a PR, your authorship will be recorded.

**Comment by bsyk** [comment]
There's a patch to the current UI in the linked PR #930.
It was suggested to rewrite and work into the new API project, that I haven't yet done.

**Comment by yubiuser** [comment]
Solution is to increase PHP`s memory as described here: https://docs.pi-hole.net/main/faq/#while-loading-data-from-the-long-term-database-you-encountered-an-error
