### ISSUE TITLE
"Interface listening behavior" setting not preserved between restarts.

### ISSUE THREAD

**Issue by ThisIsSet-L** [pi-hole/AdminLTE#929]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`After restarting the server, settings in "Interface listening behavior" (Settings > DNS) would be preserved ("Listen on all interfaces, permit all origins")`

**Actual behaviour:**

`"Interface listening behavior" reverts to "Listen on all interfaces". Web interface shows desired option selected, but desired behavior is only exhibited once another option is selected, saved, and the desired option is then selected and saved. `

**Steps to reproduce:**

`Restart the Pi-hole service`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`Refused for security reasons`

**Troubleshooting undertaken, and/or other relevant information:**

`Workaround found in "Actual Behavior" section.`

**Comment by Mcat12** [comment]
> Refused for security reasons

It would be very helpful if we could access the information necessary to debug this issue. Without it, my only lead is that maybe your storage medium (SD card?) is going read-only. This is relatively common, and causes the card to fail to persist data across a reboot.

**Comment by wertyy102** [comment]
We have pihole running on a VPS in the cloud, with raid storage and confirmed non-failing, and still hit this issue.  if you give me some time until I get home from work, i can pull logs, if there is anything you want me to pull for you.

**Comment by Mcat12** [comment]
These outputs would be helpful, taken both before and after restarting (if you don't want to make a debug token):
```
cat /var/log/lighttpd/error.log
cat /etc/pihole/setupVars.conf # Remove any sensitive information
journalctl -u lighttpd
```

**Comment by wertyy102** [comment]
Alright here we go.  
Sorry about the delay, life got in the way.

[journalctl.txt](https://github.com/pi-hole/AdminLTE/files/3071530/journalctl.txt)

[error.log](https://github.com/pi-hole/AdminLTE/files/3071531/error.log)


[setupVars.conf.txt](https://github.com/pi-hole/AdminLTE/files/3071533/setupVars.conf.txt)

**Comment by Mcat12** [comment]
You have an empty DNS server saved in setupVars:
```
PIHOLE_DNS_7=
```

Remove this line manually, reload the settings page, and click save.

**Comment by ThisIsSet-L** [comment]
Sorry about lack of logs. I was just a tech on this particular install for @wertyy102 and I didn't have permission to share such stuff.

**Comment by wertyy102** [comment]
@Mcat12 oh lol, that's from sanitizing before posting.  My bad

**Comment by Mcat12** [comment]
I was away for traveling, sorry for the late response. I am unable to reproduce this. Check the output of this command before changing the setting, after changing the setting, and after rebooting (when you say the setting has changed):
```
cat /etc/pihole/setupVars.conf | grep DNSMASQ_LISTENING
```

**Comment by wertyy102** [comment]
Alright, I'll make a maintenance window and test tonight.  

And, It's all good @Mcat12, taking time for yourself is always important.  You guys do great work and deserve breaks :)

**Comment by DL6ER** [comment]
@wertyy102 Do you have any new insight for us or can this ticket be closed?

**Comment by wertyy102** [comment]
I totally forgot about this...

I'm on a camping trip this weekend, slated to be back in three days.  I'll
take a look then to see if the issue still persists.

**Comment by yubiuser** [comment]
Hope they didn't got lost during camping.

**Comment by musikele** [comment]
@yubiuser Hi there, i am having this same issue. Pihole is deployed as docker container on Synology. Everything works fine, every setting is saved, except this one. Can we reopen this ticket?

**Comment by shell** [comment]
I have the same problem. Every time Synology DSM updates, it breaks internet at my home network. DNS server stops responding because this setting is being reset to default

**Comment by shell** [comment]
@musikele I just checked my container ENV variable DNSMASQ_LISTENING, and it explicitly said "local" instead of "all". Probably because I followed it in a guide

**Comment by musikele** [comment]
@shell you're right, that was my problem too. I added that variable in how i start docker and it worked
