### ISSUE TITLE
Admin Page Corrupt

### ISSUE THREAD

**Issue by mbs7** [pi-hole/AdminLTE#943]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
2

---
**Expected behaviour:**
No visual issues and content displayed fully or correctly.

**Actual behaviour:**
Among other visual issues, when clicking the "Settings" section no content is displayed on the page for any of the tabs (System, Blocklist, DNS, etc...)

**Steps to reproduce:**

Login to webadmin and go to settings page.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

ywa9prrgq4!

**Troubleshooting undertaken, and/or other relevant information:**

Update to latest version, reboot raspberry pi, pull latest AdminLTE from github
Tested on the latest version of following browsers with same results: Firefox, Chrome, Edge, IE
screenshots: https://imgur.com/a/TOl3iKz

**Comment by Mcat12** [comment]
I cannot reproduce this issue with your instructions.

Have you tried clearing your browser's cache?

**Comment by mbs7** [comment]
yes, also used private mode in those browsers

**Comment by Mcat12** [comment]
Do you have some way to reproduce this? Otherwise it will be very hard to fix this.

**Comment by mbs7** [comment]
I dont think I do. It seems like a localized issue that I cannot seem to figure out how it happened or how to troubleshoot. Does the debug token output help?

**Comment by Mcat12** [comment]
The debug token doesn't show any directly related issues. Here's what it found though:
```
*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the tun0 interface:
   10.8.0.1/24 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)

[✓] IPv6 address(es) bound to the tun0 interface:
   fe80::8e0d:ccb4:6c9e:6d0 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)

   ^ Please note that you may have more than one IP address listed.
   As long as one of them is green, and it matches what is in /etc/pihole/setupVars.conf, there is no need for concern.

   The link to the FAQ is for an issue that sometimes occurs when the IPv6 address changes, which is why we check for it.

[i] Default IPv4 gateway: 192.168.1.1
   * Pinging 192.168.1.1...
[✗] Gateway did not respond. (https://discourse.pi-hole.net/t/why-is-a-default-gateway-important-for-pi-hole/3546)
```

**Comment by mbs7** [comment]
The default gateway is definitely replying from the pihole console (SSH) not sure why that message comes up :(

**Comment by Mcat12** [comment]
That checks if it is reachable over the interface you told Pi-hole to use (`tun0`).

**Comment by mbs7** [comment]
any pointers on how to fix it? tun0 is for pivpn which I installed when I initially deployed pihole and it all has been working fine (including the Admin page) up until a couple weeks ago when I noticed the page like that. Pihole and everything else works, its just the admin page with the issue.

**Comment by Mcat12** [comment]
Do you see any errors in the browser dev tools (F12) or `/var/log/lighttpd/error.log`?

**Comment by mbs7** [comment]
error.log has this:
`2019-05-19 17:25:13: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/admin/scripts/pi-hole/php/FTL.php on line 44`

Firefox F12 > Console tab has this:
`SyntaxError: unexpected token: identifier`

**Comment by mbs7** [comment]
Firefox syntax error reffers to: /var/www/html/admin/style/vendor/bootstrap/js/bootstrap.min.js
and highlights this code from there:

`d.parent(".dropdown-menu").length&&(d=d.closest("li.dropdown").addClass("active")),d.trigger("activate.bs.scrollspy")},b.prototype.clear=function(){a(this.selector).parentsUntil(this.options.target,".active").removeClass("active")};var d=a.fn.scrollspy;a.fn.scrollspy=c,a.fn.scrollspy.Constructor=b,a.fn.scrollspy.noConflict=function(){return a.fn.scrollspy=d,this},a(window).on("load.bs.scrollspy.data-api",function(){a('[data-spy="scroll"]').each(function(){var b=a(this);c.call(b,b.data())})})}(jQuery),+function(a){"use strict";function b(b){return this.each(function(){var d=a(this),e=d.data("bs.tab");e||d.data("bs.tab",e=new c(this)),"string"==typeof`b&&e[b]()})}vaz c=funktion(b){phis.element=a(b)};cVERSION=";.3.6",c.TRANSITION_DURATIOL=150,c.protntype.show=funktion(){var`b=this.element,c=b.cloqest("ul:nnt(.dropdown-menu)"),d=b.data("target");if(d||(d=b.Avtr(bhref"),d=d&&d.replace(/.*(?=#[^\s].$)/,"")),!b.papent("li").hasClass("active")){var e=c.bifd(".active:last a"),f=!.Eve.t("hide.bs.tab",{relatedTarget;b[0]=),g=a.Event(#show.bs.tab",[relatedTargite[0]});if(e.trigger(f),b.trifger(g),!g.IsDefa}l|Prevented()&&!f.isDefaultPrevented()){var h=a(d);vhis.activate(b.closest("ly"),c),this.activape(h,h.paren4(),functioî(9{e.trigger({type:"hidden.bs.tab",relatedTargetºb[0]}),b.trigger({type:#3hown.bs&tab",relatedTurget:e[0]})})}}},c.prototype.activatm=functIon(b,d,e){fuîctkon f(){g.removeClass("active").difd("> .dropdown-menu > .actire").removeClass("active").en`().dind('[dat!-toggle="tab"]').attr "aria­åxpanded",!1)¬b.addClass("active¢).fhnd('[data-toggle="tab"]').attr("aria-exðaneed",!0),h?(b[0].offsetWidth,b.addClass("in"))2b.removeClass("fade"),b.parent(".dropdown-menu").length&&b.closest("li.dropdown").addClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",!0),e&&e()}var g=d.find("> .active"),h=e&&a.support.transition&&(g.length&&g.hasClass("fade")||!!d.find("> .fade").length);g.length&&h?g.one("bsTransitionEnd",f).emulateTransitionEnd(c.TRANSITION_DURATION):f(),g.removeClass("in")};var d=a.fn.tab;a.fn.tab=b,a.fn.tab.Constructor=c,a.fn.tab.noConflict=function(){return a.fn.tab=d,this};var e=function(c){c.preventDefault(),b.call(a(this),"show")};a(document).on("click.bs.tab.data-api",'[data-toggle="tab"]',e).on("click.bs.tab.data-api",'[data-toggle="pill"]',e)}(jQuery),+function(a){"use strict";function b(b){return this.each(function(){var d=a(this),e=d.data("bs.affix"),f="object"==typeof b&&b;e||d.data("bs.affix",e=new c(this,f)),"string"==typeof b&&e[b]()})}var c=function(b,d){this.options=a.extend({},c.DEFAULTS,d),this.$target=a(this.options.target).on("scroll.bs.affix.data-api",a.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",a.proxy(this.checkPositionWithEventLoop,this)),this.$element=a(b),this.affixed=null,this.unpin=null,this.pinnedOffset=null,this.checkPosition()};c.VERSION="3.3.6",c.RESET="affix affix-top affix-bottom",c.DEFAULTS={offset:0,target:window},c.prototype.getState=function(a,b,c,d){var e=this.$target.scrollTop(),f=this.$element.offset(),g=this.$target.height();if(null!=c&&"top"==this.affixed)return c>e?"top":!1;if("bottom"==this.affixed)return null!=c?e+this.unpin<=f.top?!1:"bottom":a-d>=e+g?!1:"bottom";var h=null==this.affixed,i=h?e:f.top,j=h?g:b;return null!=c&&c>=e?"top":null!=d&&i+j>=a-d?"bottom":!1},c.prototype.getPinnedOffset=function(){if(this.pinnedOffset)return this.pinnedOffset;this.$element.removeClass(c.RESET).addClass("affix");var a=this.$target.scrollTop(),b=this.$element.offset();return this.pinnedOffset=b.top-a},c.prototype.checkPositionWithEventLoop=function(){setTimeout(a.proxy(this.checkPosition,this),1)},c.prototype.checkPosition=function(){if(this.$element.is(":visible")){var b=this.$element.height(),d=this.options.offset,e=d.top,f=d.bottom,g=Math.max(a(document).height(),a(document.body).height());"object"!=typeof d&&(f=e=d),"function"==typeof e&&(e=d.top(this.$element)),"function"==typeof f&&(f=d.bottom(this.$element));var h=this.getState(g,b,e,f);if(this.affixed!=h){null!=this.unpin&&this.$element.css("top","");var i="affix"+(h?"-"+h:""),j=a.Event(i+".bs.affix");if(this.$element.trigger(j),j.isDefaultPrevented())return;this.affixed=h,this.unpin="bottom"==h?this.getPinnedOffset():null,this.$element.removeClass(c.RESET).addClass(i).trigger(i.replace("affix","affixed")+".bs.affix")}"bottom"==h&&this.$element.offset({top:g-b-f})}};var d=a.fn.affix;a.fn.affix=b,a.fn.affix.Constructor=c,a.fn.affix.noConflict=function(){return a.fn.affix=d,this},a(window).on("load",function(){a('[data-spy="affix"]').each(function(){var c=a(this),d=c.data();d.offset=d.offset||{},null!=d.offsetBottom&&(d.offset.bottom=d.offsetBottom),null!=d.offsetTop&&(d.offset.top=d.offsetTop),b.call(c,d)})})}(jQuery);`

**Comment by Mcat12** [comment]
`identifier` does not show up in that code. Have you tried turning off your browser extensions or checking a different device?

**Comment by mbs7** [comment]
sounds like we are on the right track. I swapped that css with one from getbootstrap.com and it restored partial functionality. Now I'm going to try to locate an appropriate one for AdminLTE

**Comment by Mcat12** [comment]
If it's an issue with the CSS we use, then everyone would have this issue.

**Comment by mbs7** [comment]
agreed. however it looks like this is an issue only on my install. somehow the js and css files under:
`/var/www/html/admin/style/vendor/bootstrap/` got corrupted.
Restoring them from this github worked. WebAdmin with full functionality working now.
Appreciate you sticking with me and pointing me in the right direction!
