### ISSUE TITLE
Sidebar toggle icon not showing

### ISSUE THREAD

**Issue by alexjustesen** [pi-hole/AdminLTE#944]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behaviour:**

The :before pseudo-element on `.main-header .sidebar-toggle` css class is missing the font-weight and font-family attributes to correctly show a "Font Awesome 5 Free" bars icon (fa-bars).

**Actual behaviour:**

There is a square character in the sidebar-toggle button where the missing bars icon should be.

**Steps to reproduce:**

Log into the PiHole dashboard (version 4.3), there will be a square icon in the sidebar-toggle button where the missing bars icon is.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

n/a

**Troubleshooting undertaken, and/or other relevant information:**

To fix the issue add `font-weight: 900;` and 'font-family: "Font Awesome\ 5 Free";' to the css class of `.main-header .sidebar-toggle:before`.

**Comment by Mcat12** [comment]
I cannot reproduce this issue. Have you tried clearing your browser's cache? You may have old CSS files cached. If you can still reproduce it after that, share a screenshot of what you see.

**Comment by Th3M3** [comment]
The rule proposed by @alexjustesen is already in [**pi-hole.css** in line 184](https://github.com/pi-hole/AdminLTE/blob/master/style/pi-hole.css#L184).

But I see an issue with the hight when hovering the button (on PC and mobile):
![Unbenannt](https://user-images.githubusercontent.com/28313514/58374169-f57d3e00-7f39-11e9-8c60-448497ce07eb.jpg)

This could be fixed by adding `.navbar .sidebar-toggle` selector to rule in [line 86](https://github.com/pi-hole/AdminLTE/blob/master/style/pi-hole.css#L86).

**Comment by Mcat12** [comment]
@Th3M3 could you open an new issue (or PR) for this?

**Comment by alexjustesen** [comment]
Confirmed, it was a cache issue. Sorry about that.
