### ISSUE TITLE
Sidebar toggle icon wrong hight

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/AdminLTE#945]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

7

---
**Expected behaviour:**

When hovering the sidebar toggle icon, the button should have the same hight as the headerbar.

**Actual behaviour:**

The button is little too high (on PC and mobile):
![Unbenannt](https://user-images.githubusercontent.com/28313514/58374169-f57d3e00-7f39-11e9-8c60-448497ce07eb.jpg)

**Steps to reproduce:**

Open pi.hole and hover the sidebar toggle button

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`-`

**Troubleshooting undertaken, and/or other relevant information:**

This could be fixed by adding `.navbar .sidebar-toggle` selector to pi-hole.css rule in [line 86](https://github.com/pi-hole/AdminLTE/blob/master/style/pi-hole.css#L86).

**Comment by Mcat12** [comment]
I cannot reproduce this, and for me the toggle is to the right on the lighter part of the header.
![image](https://user-images.githubusercontent.com/4417660/58375563-bd123b80-7f0a-11e9-9cc8-2690ec90af04.png)
![image](https://user-images.githubusercontent.com/4417660/58375568-cf8c7500-7f0a-11e9-9653-b53ab3cbbe9d.png)

You might need to clear your browser cache to get the new styles.

**Comment by Th3M3** [comment]
This is a fresh installation on pi-hole. Browsers cache is cleared.
Issue is still present, even in different browsers and on the mobile phone.
Maybe it only occurs on high density screens. 
If I change the page's zoom to values between 80 - 90% or 110-125%, then the height is correct.

I am not sure why the elements height is calculated to 20.667px. 
Maybe the new Font Awesome version needs another `line-height` value.
![Unbenannt](https://user-images.githubusercontent.com/28313514/58380033-272eed00-7fac-11e9-852b-5da6ccd7b4fb.jpg)

**Comment by Mcat12** [comment]
Ok, I see now. It is on hover of the button that you have the issue. Adding that height CSS fixes the issue. I'll make a PR.
