### ISSUE TITLE
api.php throws server error 500

### ISSUE THREAD

**Issue by Peronia** [pi-hole/AdminLTE#949]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

i dont understand this question...

---
**Expected behaviour:**

Graphs rendered correctly at dashboard, can enter an entry into white- and blacklist sites

**Actual behaviour:**

Empty error message on black- and whitelist, no graphs, both api.php get a 500 error

**Steps to reproduce:**

Visit the sites in adminpanel

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

upload failed, here are the debuglog:
[log.txt](https://github.com/pi-hole/pi-hole/files/3236774/log.txt)

**Troubleshooting undertaken, and/or other relevant information:**

increase the memory_limit @ php to 256 and restart the lighthttp service
![admin_500](https://user-images.githubusercontent.com/25049991/58630025-6af06200-82de-11e9-90a7-8e1d718e8459.JPG)

**Comment by DL6ER** [comment]
Please install `php7.0-json` using
```
sudo apt install php7.0-json
```

**Comment by Peronia** [comment]
Hi,

im using this command. It is already installed:
`pi@raspberrypi:~ $ sudo apt install php7.0-json
Reading package lists... Done
Building dependency tree
Reading state information... Done
php7.0-json is already the newest version (7.0.33-0+deb9u3).
php7.0-json set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by Mcat12** [comment]
Check the answers from this topic: https://discourse.pi-hole.net/t/sqlite3-and-json-encode-fault/18325

**Comment by Peronia** [comment]
Thanks, this solved my issue!
