### ISSUE TITLE
custom colors or color-blind friendly query log

### ISSUE THREAD

**Issue by jiayulu** [pi-hole/AdminLTE#950]
the query log page:

http://mypihole/admin/queries.php

is very hard for color blind eyes to read. I often go to that page to manually blacklist or whitelist sites. In order to easily tell forwarded sites from blocked sites, I changed forwarded entries to blue.

It would be nice if there's a built-in colorscheme for color bind people, or a way to customize colors through the web interface.

**Comment by DL6ER** [comment]
@Mcat12 How easy would it be to realize this with the new web interface?

**Comment by Mcat12** [comment]
It would be about as easy as adding support for a dark mode, so not too easy. There is an issue for tracking color accessibility for the new web interface: https://github.com/pi-hole/web/issues/120

**Comment by DL6ER** [comment]
This is already tracked by pi-hole/web#120 and not an issue, but rather a feature request. Closing this ticket as it a duplicate.

**Comment by rdwebdesign** [comment]
@jiayulu 

I'm not sure if you still use Pi-hole, but I'm testing 2 new themes (one light, one dark) with better contrast and colors intended to distinguish between allowed and blocked items in cases like this one.

I like to hear your opinion about the themes.

If you are interested in testing the themes, you can execute:
```console
pihole checkout web high_contrast
```
Then, open the web interface and select the new themes.

When you finish the test (or case you decide the themes are too bad to use them), you need to revert the changes using:
```console
pihole checkout web master
```
