### ISSUE TITLE
show remark on taillog.php if logging is disabled

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/AdminLTE#959]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behaviour:**

If query logging has been disabled (`sudo pihole logging off`), it would be grat to get an information box about this on taillog.php site.

**Actual behaviour:**

If I open _Tail pihole.log_ site, the log stays clear because query logging has been disabled before. 

**Steps to reproduce:**

- disable query logging with `sudo pihole logging off`
- navigate to _Tail pihole.log_ and notice that there is no information why no data is tailing in log.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`-`

**Troubleshooting undertaken, and/or other relevant information:**

`-`

**Comment by Mcat12** [comment]
Please make feature requests on [Discourse](https://discourse.pi-hole.net/c/feature-requests), as was noted in the template.
