### ISSUE TITLE
Is it safe to make changes to the index.php file?

### ISSUE THREAD

**Issue by virtyaluk** [pi-hole/AdminLTE#961]
Hey everybody!

Just wondering whether it is possible to make purely cosmetic changes to the index file. I have PiHole running on my VDS and every time I open its homepage I see default PiHole page with some random buttons etc. I'd like to hide these buttons and stuff and refreshen page's style. Is it safe?

Thank you.

**Comment by PromoFaux** [comment]
Totally safe to do so, but the usual "Your warranty is now void" applies when it comes to troubleshooting issues whilst you have a non-stock setup.

Keep in mind that updating your install (e.g `pihole -up`) will discard any changes you make, so take a backup before updating to the next release!
