### ISSUE TITLE
PWA redirects to browser on ios

### ISSUE THREAD

**Issue by pniedzwiedzinski** [pi-hole/AdminLTE#963]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:** 

`1`

---
**Expected behaviour:**

`I would like to have working PWA on ios, that doesn’t redirects you to the browser.`

**Actual behaviour:**

`When I click login the link is open in browser instead of in application shell`

**Steps to reproduce:**

`1. Add pihole to homescreen on 
2. Click login`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`I found that: https://medium.com/@waelkdouh/preventing-single-sign-on-sso-redirects-inside-a-progressive-web-application-pwa-d0762223d2f7

There is also a fix but I have not tried it yet`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
The web interface is not a progressive web application. You may have more luck with the new web interface when it is released.

**Comment by pniedzwiedzinski** [comment]
Are you working on PWA? Or this is not planned?

**Comment by Mcat12** [comment]
The new web interface should work better in this situation. See https://github.com/pi-hole/web.

**Comment by pniedzwiedzinski** [comment]
thanks
