### ISSUE TITLE
Dashboard page cosmetic issues

### ISSUE THREAD

**Issue by jdquadrider** [pi-hole/AdminLTE#965]
The PiHole dashboard is missing values for the Y-axis.  There are also cosmetic issues with the floating "bubbles".  See screenshot for more details.
![image](https://user-images.githubusercontent.com/51855820/59552447-07f50100-8f55-11e9-98ae-11451a814e2a.png)

**Comment by DL6ER** [comment]
What browser and operating system are you using?

Do you observe the same with other, maybe more commonly used, browsers like Firefox, or Chrome?

**Comment by jdquadrider** [comment]
Good suggestion and it looks like you nailed it.  I'm using the Brave browser (which is chromium-based) and assumed it would work the same as it did in Chrome.  I tried it in Edge and it works fine.  I guess I'll just wait and see if Brave displays it properly with future updates.  Thanks for the response!

**Comment by DL6ER** [comment]
Thanks for your report. As the issue is not directly Pi-hole related, I will close the ticket.
