### ISSUE TITLE
web api (php) lack of documentation

### ISSUE THREAD

**Issue by ilyam8** [pi-hole/AdminLTE#970]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

Web API documentation 

i am openning the issue in this repo, because [pi-hole api repo](https://github.com/pi-hole/api) is another project, i have a question regarding PHP API.

**Actual behaviour:**

No Web API documentation 

**Steps to reproduce:**

Try to find Web API documentation 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`-`

**Troubleshooting undertaken, and/or other relevant information:**

 - [Googling](https://google.com)
 - reading [official documentation](https://docs.pi-hole.net/ftldns/in-depth/)

The most relevant source i find is this page

> https://discourse.pi-hole.net/t/pi-hole-api/1863

But it is outdated and it doesn't contain all iformation i need.

___

The question:

> ?summary,?topClients, ?topItems, etc

I am not clear about the timeframe. Is it 24 hr?

**Comment by Mcat12** [comment]
To answer your question, the default time frame is the last 24 hours. There are some other APIs accessed via `api_db.php` which allow custom time ranges, and use the database instead of FTL to retrieve the data.

**Comment by Mcat12** [comment]
If you have other questions about the API, we will gladly answer them here, but work on official documentation will be for the new API.

**Comment by ilyam8** [comment]
@technicalpyro @Mcat12 thanks for the quick response :+1: 	

> To answer your question, the default time frame is the last 24 hours. 

Just to make it clear.

So the time frame for **all** the metrics reported by `api.php` is the last 24 hrs by default?

How can i change the default?

I was confused by metrics names, some of them have `_today` suffix.

**Comment by ilyam8** [comment]
i am asking because there is [the request](https://github.com/netdata/netdata/issues/6204) to add a `pi-hole` collector the the [netdata](https://github.com/netdata/netdata)

**Comment by Mcat12** [comment]
Correct, as the data returned by FTL is all from the last 24 hours, the data returned by `api.php` is in that time range. In past releases we had support for adjusting the time range on the FTL side, but since then that functionality has been removed as it caused issues and made things too complex. For time ranges other than the last 24 hours, use `api_db.php` (note that it may be slower, as it queries the on-disk database instead of FTL's in-memory data).

Note that there is a time range option for `getAllQueries`, but that is the exception and is still limited to within the last 24 hours:
https://github.com/pi-hole/AdminLTE/blob/44aff727e59d129e6201341caa1d74c8b2954bd2/api_FTL.php#L265

Some of the field names are old, and are poorly named, especially in the summary. The new API tries to avoid those pitfalls.

**Comment by ilyam8** [comment]
> For time ranges other than the last 24 hours, use api_db.php

any docs on this apart from the source code? :smile:

**Comment by Mcat12** [comment]
I don't think there are any other docs. Generally, it is similar to `api.php` except you should pass at least one of `until` or `from`, which are UNIX timestamps.

**Comment by ilyam8** [comment]
i did a quick test and unfortunately i cant really use the `api_db.php` because data from it is not realtime.

**Comment by Mcat12** [comment]
It gets updated by FTL every minute (by default):
https://docs.pi-hole.net/ftldns/configfile/#dbinterval

Does `api.php` work for you? The database version is usually only used for historical stats.

**Comment by ilyam8** [comment]
Yes, it works, but all the data i get from it is `for the last 24 hr`. I was trying to understand if there is a possibility to get realtime data to have per seconds metrics (queries/s, etc). From what i understood there is no.

**Comment by Mcat12** [comment]
Right, we don't track rates. You might be interested in the calls used for the queries graph, though (`'overTimeData10mins`).
https://github.com/pi-hole/AdminLTE/blob/44aff727e59d129e6201341caa1d74c8b2954bd2/api_FTL.php#L69

That gives a map from timestamp to the number of queries in the 10 minute time range centered at that timestamp.

**Comment by ilyam8** [comment]
Hey @Mcat12 

I have a question regarding alarms, it would be nice to have some help from you.

We discussed the alarms with @modem7 (`Pi-hole` user, the one who [requested](https://github.com/netdata/netdata/issues/6204) pihole collector and a good guy in general).

PR with alarms: [link](https://github.com/netdata/netdata/pull/6320)

Alarms:
 - blocked dns queries precentage
   - warn: % > 50
   - crit: % > 75
 - blocklist last update time (update interval is 1 week)
   - warn: skipped 1 update interval
   - crit: skipped 2 update interval
 - gravity.list file existence
   - crit: if not exist
 - blocking functionality status
   - warn: if off


Info collected from:
 - `summaryRaw`
 - `getQueryTypes`
 - `getForwardDestinations`
 - `topClients`
 - `topItems`

___

What do you think? Are the alarms make sense? Should we add something/remove/change?

**Comment by Mcat12** [comment]
The blocked queries stat is very different across users, and highly dependent upon the user's network and the devices on it. Some users regularly have less than 5% blocked queries, while others have more than 60%. If possible, the blocked queries alarm should be user-configurable (unsure if this is a capability of your system). If it can not be configurable, then those defaults seem reasonable for most installs.

The blocklist update time alarm sounds reasonable.

The gravity.list existence may need some tweaking. When blocking is disabled, its contents are moved to `gravity.list.bck` (although the original file still exists). It may be better to check for if both `gravity.list` and `gravity.list.bck` are empty.

You should be able to check everything (besides the gravity.list existence) just from a summary call and maybe a `status` call too.

**Comment by ilyam8** [comment]
> just from a summary call

Yes, i use data from summary call for all checks (summary returns status). 

> The gravity.list existence may need some tweaking.

Current alarm just checks `file_exists`. We assumed that it is  always should be true.

```json
{
    "file_exists": true,
    "absolute": 1561159378,
    "relative": {
        "days": "0",
        "hours": "02",
        "minutes": "25"
    }
}
```
