### ISSUE TITLE
Feature Request: AD Authentication

### ISSUE THREAD

**Issue by knightowl1000** [pi-hole/AdminLTE#981]
Hi - Would it be possible to have AD authentication for Pihole. I'd like users to be able to log-in with their AD user/pass and perform whatever changes and changes should be logged. If you need a test AD server, I can spin a lab pihole and AD server. I use pihole at home (I have an AD server) but I also think this will benefit enterprise users.

**Comment by Mcat12** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net).

Thank you for your understanding.
