### ISSUE TITLE
whitelist button's icon missing on Query Log page

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/AdminLTE#983]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`6`

---
**Expected behaviour:**

There should be an icon on the 'Whitelist' buttons on the query log page (like it is on the 'Blacklist' buttons).

**Actual behaviour:**

The icon is missing after Font Awesome Update

**Steps to reproduce:**

- go to the Query Log
- have a look to the 'Whitelist' and 'Blacklist' Buttons and their icons

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`-`

**Troubleshooting undertaken, and/or other relevant information:**

In queries.js all `fa fa-pencil-square-o` should be replaced by `fa fa-edit` or some other icon from the [fa gallery](https://fontawesome.com/icons?d=gallery&m=free).

**Comment by Th3M3** [comment]
Hi there,
as I found out now there are much more icons not shown since the update to Font Awesome 5.
I have searched in all files, and here my results and suggestions:

- [settings.php#L49](https://github.com/pi-hole/AdminLTE/blob/devel/settings.php#L49): `fa-warning` -> <b>`fa-exclamation-triangle`</b>

- [daterangepicker.js](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/vendor/daterangepicker.js), Lines [109](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/vendor/daterangepicker.js#L109) and [120](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/vendor/daterangepicker.js#L120): `fa-clock-o` -> <b>`far fa-clock`</b>

- [loginpage.php#L19](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/pi-hole/php/loginpage.php#L19): `fa-times-circle-o` -> <b>`far fa-times-circle`</b>

- [auditlog.js#L63](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/pi-hole/js/auditlog.js#L63): `fa-pencil-square-o` -> <b>`fa fa-edit`</b>

- [db_queries.js](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/pi-hole/js/db_queries.js), Lines [253](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/pi-hole/js/db_queries.js#L253), [271](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/pi-hole/js/db_queries.js#L271) and [277](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/pi-hole/js/db_queries.js#L277): `fa-pencil-square-o` -> <b>`fa fa-edit`</b>

- [app.min.js](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/vendor/app.min.js): `fa fa-refresh` -> <b>`fa-sync`</b>
  (actually I am not sure if this is really needs to be updated)

**Comment by Mcat12** [comment]
@Th3M3 Do you want to open a PR with those changes?

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
