### ISSUE TITLE
time period since last gravity update is displayd incorrectly (in dev)

### ISSUE THREAD

**Issue by Th3M3** [pi-hole/AdminLTE#989]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Expected behaviour:**

Hovering the red tile on the dashboard with the pointer should show the time period since the last gravity update.

**Actual behaviour:**

The displayd time period is not correct, since the period is still calculated from the modification date of /etc/pihole/gravity.list in [`gravity.php`](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/pi-hole/php/gravity.php#L16).

**Steps to reproduce:**

1) checkout **dev** branch
2) hover the red tile on the dashboard with the pointer and notice the shown time period since last update.
3) update the gravity lists (whether via Web interface or CLI)
4) repeat step 2 again and notice that the shown period has not changed.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`-`

**Troubleshooting undertaken, and/or other relevant information:**
 
As I see it is not enough to use the modification date of `/ect/pihole/gravity.db` because it's timestamp also changes after changes are done do the White- or Blacklist.

**Comment by DL6ER** [comment]
Thanks for reminding us of this feature. We will add another field to the database with the timestamp of the last gravity run.

**Comment by Th3M3** [comment]
I have also have an little bit strange behavior when adding and removing entries from the wild- or blacklist:

If I delete them too quickly one after the other, they will not be deleted even though they disappear from the list.
An example: 
1) I add five domains `1.test 2.test 3.test 4.test 5.test` to the whitelist.
2) Afterwards I click on the delete button at `1.test`, `2.test` and `3.test`. They dissapear from the list.
3) But after a refresh the domains `2.test` and `3.test` are back in the list.
4) Repeating step 1 makes popup a message, that _at least one domain was already present, ..._, 
but the list does not get refreshed and needs a doing it manually.

**Comment by DL6ER** [comment]
@Th3M3 The list management is currently being completely rewritten to directly interact with the database. See https://github.com/pi-hole/AdminLTE/pull/986

**Comment by DL6ER** [comment]
Fixing this issue has to wait for #986 to go in as we will need to update the gravity database version which is also modified in this PR.
