### ISSUE TITLE
Admin Console Pie-charts are no longer "circular"

### ISSUE THREAD

**Issue by Tom999Hall** [pi-hole/AdminLTE#99]
Upgraded to latest pi-hole (2.7) 

The Query Types and Forwarded Destinations pie-charts were circular in shape, but they are now stretched vertically
##

**Comment by PromoFaux** [comment]
Silly question, what does it look like after you refresh the page? 

Also, could you provide a screenshot please? Thanks.

**Comment by Tom999Hall** [comment]
I tried to add a screenshot, but it didn't attach - Maybe it's the Edge browser ?

**Comment by Tom999Hall** [comment]
I've attached a screenshot to your email

**Comment by PromoFaux** [comment]
Which email address? Not seeing anything. Try hosting the screenshot on imgur and providing the link here :)

**Comment by Tom999Hall** [comment]
[https://onedrive.live.com/redir?resid=4A31FFD5E211D2D7!189451&authkey=!AId8eAofhESv0c4&ithint=folder%2cjpg](url)
Edge & IE screenshots

**Comment by PromoFaux** [comment]
Sorry, just edited those into your comment to make it easier to see...

**Comment by PromoFaux** [comment]
OK, so I've just tested this on Chrome, Firefox and IE 11, though I don't have edge installed...

The graphs all look fine on first load, but there is (a known) issue when you resize the page, in which the elements don't resize correctly, however a refresh will make them circular again.

**Comment by Tom999Hall** [comment]
Just re-tested IE/Chrome/Edge - initial page load still not circular, but refreshing the page made them circular again 
Btw - this is on Windows 10 Build 14361

**Comment by PromoFaux** [comment]
Hmm, I'm on build 10240 (Enterprise) And am not experiencing this.. Weird. Would be interesting to see if anyone else has this issue. You say you didn't have this issue before 2.7? As far as I'm aware there were no changes made to that page. @Mcat12 any ideas?

**Comment by Tom999Hall** [comment]
I always open my browser windows maximised, so I'm not re-sizing

I definitely haven't seen this with 2.6 on earlier builds, but then 2.7 & 14361 were quite close time-wise, so I may just have not noticed any issues with 2.6 & 14361 

But at least it's a known issue & a refresh fixes it

**Comment by PromoFaux** [comment]
It's either a fault with `charts.js` or something we're doing wrong with it!

**Comment by Mcat12** [comment]
I didn't change anything with relation to the graphs. (As far as I can remember)

**Comment by DonLexos** [comment]
Just tested this on win10 in Chrome and Edge. On initial load the charts are perfectly round. A resize in Edge would transform them (based on what direction you resize the window), same in Chrome.

**Comment by Tom999Hall** [comment]
(sorry, screenshots are still not uploading for me) 

Thanks for that Alex - but (for me), the charts are still non-circular 

Interestingly though, it’s only if I click the “Refresh” button that the charts go circular again 

If I click the “Restore Down” button, then Maximise again (or double-click the Title Bar),  or re-type the URL & hit Enter, they remain non-circular
Likewise if I grab the edge of the window and resize it that way the charts distort depending on the  shape of the window, but once I Maximise, they remain non-circular

It wouldn’t be a Display driver issue would it ?

**Comment by Mcat12** [comment]
Does this happen on all browsers?

**Comment by Tom999Hall** [comment]
I'm baaack !  - while I was away, a new Windows 10 build: 14366 dropped - I've clean-installed it, and here's what I'm seeing 
**Edge** - initial view, charts are stretched vertically, restore-down & grab to resize deforms charts according to window shape & size, maximise still remain non-circular - reload url - charts are stretched restore button: charts return to circular    
**Built-in IE** - (same as Edge)
**Chrome x64** - initial view, charts are circular !, restore-down & grab to resize deforms charts according to window shape & size, maximise: charts return to circular, reload url - still circular    

I hope this helps ?

**Comment by DL6ER** [comment]
We have updated the Chart.js engine to the latest version. There have been many changes. I think everything should have been fixed. I don't use a Windows machine, so I cannot do these tests myself. 

However, @Tom999Hall  feel free to reopen this issue if it will not be fixed in the next release.
