### ISSUE TITLE
Admin Dashboard not working in mobile device

### ISSUE THREAD

**Issue by alejandromav** [pi-hole/AdminLTE#994]
**In raising this issue, I confirm the following:**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

The admin dashboard should render properly in mobile devices, including iPhone.

**Actual behaviour:**

Admin dashboard isn't working properly in iPhone, and maybe other mobile phones. Some inline javascript [is blocked](https://www.html5rocks.com/en/tutorials/security/content-security-policy/#inline-code-considered-harmful) because of [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).

![image](https://user-images.githubusercontent.com/3041948/63858956-baf6c780-c9a6-11e9-86cf-db044a6665e4.png)

![image](https://user-images.githubusercontent.com/3041948/63860946-49207d00-c9aa-11e9-8bbd-06e27a4f2e69.png)

![image](https://user-images.githubusercontent.com/3041948/63861120-91d83600-c9aa-11e9-9f38-63425ab3c20c.png)

**Steps to reproduce:**

Just install Pi-hole and open the admin panel from an iPhone.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/sjfzcq82ie`

**Troubleshooting undertaken, and/or other relevant information:**

Added `inline-script` policy to `Content-Security-Policy` meta tag in `header.php`. Everything is working fine now.

![image](https://user-images.githubusercontent.com/3041948/63859008-d2ce4b80-c9a6-11e9-8247-738bbd8785f4.png)

**Comment by alejandromav** [comment]
@Mcat12 No, I just followed this guide: https://docs.pi-hole.net/guides/vpn/installation/.

My OS is `Debian GNU/Linux 10 \n \l` in Google Cloud. My php version is:

```bash
PHP 7.3.4-2 (cli) (built: Apr 13 2019 19:05:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4-2, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by Mcat12** [comment]
Did you see this before following that VPN guide? I am unable to reproduce with Debian 10 and the same PHP version, using Safari on an iPhone.

**Comment by alejandromav** [comment]
I didn't try, I installed everything at the same time. I'll test it without OpenVPN set up and I'll let you know.

Thanks.

**Comment by DL6ER** [comment]
@alejandromav Do you have any new info for us?

**Comment by alejandromav** [comment]
@DL6ER I guess this is an issues of my specific installation, I couldn't find more evidence, so you can close this issue.

Thanks.
