### ISSUE TITLE
Dashboard completly corrupt after installation

### ISSUE THREAD

**Issue by flok** [pi-hole/AdminLTE#996]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
---
**Expected behaviour:**
Dashboard fully loading

**Actual behaviour:**
Dashboard completly corrupt.

Console browser output :

$ is not defined (index.js:691:1)

char coding of html document was not declared

**Steps to reproduce:**
installing pi-hole with the installation guide from the website

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

4whm4hjolm

**Troubleshooting undertaken, and/or other relevant information:**

pihole -up
pihole -r
pihole uninstall and then reinstalling with the curl from installer

**Comment by Mcat12** [comment]
I am unable to reproduce. Please make a new debug token (they expire after 48 hours). Do you see the same issue on a fresh install?

**Comment by florian-ka** [comment]
new token : sc87mbbu0y


i tried a fresh install by uninstalling with : pihole uninstall and then using the normal curl to reinstall it. Is that the right way?

**Comment by Mcat12** [comment]
A fresh install starts from a fresh operating system install. Try installing Pi-hole on a fresh system.

Your current install is using Apache instead of Lighttpd. Stop Apache and restart Lighttpd so you are using the correct web server.

You also are not running FTL (the DNS server). It may be better to start from a fresh install as so many things are broken.
