### ISSUE TITLE
Dashboard does not display correctly

### ISSUE THREAD

**Issue by Creator-360** [pi-hole/AdminLTE#997]
Hello,
I just installed pi-hole but the admin dashbord does not display properly
![Annotation](https://user-images.githubusercontent.com/42955270/64057405-0d1a3180-cbcf-11e9-9166-71e7ae7f0e4f.png)

**Comment by dschaper** [comment]
Please run `pihole -d` and post the token. We are unable to troubleshoot with the limited amount of information provided.

**Comment by Creator-360** [comment]
There it is:
[pihole_debug.log](https://github.com/pi-hole/AdminLTE/files/3562178/pihole_debug.log)

**Comment by Creator-360** [comment]
There it is:
https://tricorder.pi-hole.net/llydvttfp7

**Comment by Creator-360** [comment]
Ok thanks I fixed the problem
It was a network card problem
